Arrow: bin/abtsp.c File Reference
bin/abtsp.c File Reference
Asymmetric Bottleneck TSP heuristic.
#include "arrow.h"
Defines
#define NUM_OPTS 12
#define SOLVE_STEPS 1
Functions
int main (int argc, char *argv[])
Variables
char * input_file = NULL
char * xml_file = NULL
char * tour_file = NULL
int random_restarts = -1
int stall_count = -1
int kicks = -1
int confirm_sol = ARROW_FALSE
int supress_ebst = ARROW_FALSE
int find_short_tour = ARROW_FALSE
int lower_bound = -1
int upper_bound = INT_MAX
int basic_attempts = ARROW_DEFAULT_BASIC_ATTEMPTS
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck traveling salesman problem (BTSP) solver"
char * usage = "-i tsplib.tsp [options]"
Detailed Description
Asymmetric Bottleneck TSP heuristic.
Runs the Bottleneck TSP heuristic on the given asymmetric input file.
Author:
John LaRusic
Definition in file abtsp.c.
Define Documentation
#define NUM_OPTS 12
Definition at line 26 of file abtsp.c.
#define SOLVE_STEPS 1
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 61 of file abtsp.c.
References arrow_btsp_fun_basic_atsp(), arrow_btsp_fun_destruct(), arrow_btsp_params_destruct(), arrow_btsp_params_init(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), ARROW_BTSP_SOLVE_PLAN_BASIC, arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_abtsp_to_sbtsp(), arrow_problem_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_lk_params_destruct(), arrow_tsp_lk_params_init(), arrow_util_create_int_array(), arrow_util_print_program_args(), arrow_util_sbtsp_to_abstp_tour(), arrow_util_write_tour(), arrow_util_zeit(), basic_attempts, arrow_btsp_result::bin_search_steps, confirm_sol, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list_length, desc, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, find_short_tour, arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_problem::get_cost, input_file, arrow_tsp_lk_params::kicks, kicks, arrow_tsp_lk_params::length_bound, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_params::lower_bound, lower_bound, arrow_problem_info::max_cost, arrow_problem_info::min_cost, NUM_OPTS, arrow_btsp_params::num_steps, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_tsp_lk_params::random_restarts, random_restarts, arrow_problem::size, SOLVE_STEPS, arrow_tsp_lk_params::stall_count, stall_count, arrow_btsp_params::steps, supress_ebst, arrow_btsp_params::supress_ebst, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, tour_file, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, upper_bound, usage, and xml_file.
Variable Documentation
int basic_attempts = ARROW_DEFAULT_BASIC_ATTEMPTS
Definition at line 23 of file abtsp.c.
Referenced by main().
int confirm_sol = ARROW_FALSE
Definition at line 18 of file abtsp.c.
Referenced by main().
char* desc = "Bottleneck traveling salesman problem (BTSP) solver"
Definition at line 56 of file abtsp.c.
int find_short_tour = ARROW_FALSE
Definition at line 20 of file abtsp.c.
Referenced by main().
char* input_file = NULL
Definition at line 12 of file abtsp.c.
int kicks = -1
Definition at line 17 of file abtsp.c.
Referenced by main(), and read_args().
int lower_bound = -1
Definition at line 21 of file abtsp.c.
Referenced by main().
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "file to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE},
    {'T', "tour", "file to write tour to",
        ARROW_OPTION_STRING, &tour_file, ARROW_FALSE, ARROW_TRUE},
    {'r', "restarts", "number of random restarts",
        ARROW_OPTION_INT, &random_restarts, ARROW_FALSE, ARROW_TRUE},
    {'s', "stall-count", "max number of 4-swaps w/o progress",
        ARROW_OPTION_INT, &stall_count, ARROW_FALSE, ARROW_TRUE},
    {'k', "kicks", "number of 4-swap kicks",
        ARROW_OPTION_INT, &kicks, ARROW_FALSE, ARROW_TRUE},
    {'c', "confirm-solution", "confirm solution with exact solver",
        ARROW_OPTION_INT, &confirm_sol, ARROW_FALSE, ARROW_FALSE},
    {'e', "supress-ebst", "supress binary search",
        ARROW_OPTION_INT, &supress_ebst, ARROW_FALSE, ARROW_FALSE},
    {'S', "find-short-tour", "finds a (relatively) short BTSP tour",
        ARROW_OPTION_INT, &find_short_tour, ARROW_FALSE, ARROW_FALSE},
    {'l', "lower-bound", "initial lower bound",
        ARROW_OPTION_INT, &lower_bound, ARROW_FALSE, ARROW_TRUE},
    {'u', "upper-bound", "initial upper bound",
        ARROW_OPTION_INT, &upper_bound, ARROW_FALSE, ARROW_TRUE},
    {'a', "basic-attempts", "number of basic attempts",
        ARROW_OPTION_INT, &basic_attempts, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 27 of file abtsp.c.
int random_restarts = -1
Definition at line 15 of file abtsp.c.
Referenced by main(), and read_args().
int stall_count = -1
Definition at line 16 of file abtsp.c.
Referenced by main(), and read_args().
int supress_ebst = ARROW_FALSE
Definition at line 19 of file abtsp.c.
Referenced by main().
char* tour_file = NULL
Definition at line 14 of file abtsp.c.
Referenced by main(), and print_xml_output().
int upper_bound = INT_MAX
Definition at line 22 of file abtsp.c.
Referenced by arrow_btsp_solve(), and main().
char* usage = "-i tsplib.tsp [options]"
Definition at line 57 of file abtsp.c.
char* xml_file = NULL
Definition at line 13 of file abtsp.c.