Arrow: bin/abtsp-rai.c File Reference
bin/abtsp-rai.c File Reference
Asymmetric Bottleneck TSP heuristic using RAI heuristic.
#include "common.h"
#include "lb.h"
#include "tsp.h"
#include "btsp.h"
Defines
#define NUM_OPTS 9
#define SOLVE_STEPS 1
Functions
int main (int argc, char *argv[])
Variables
char * input_file = NULL
char * xml_file = NULL
char * tour_file = NULL
int iterations = -1
int supress_ebst = ARROW_FALSE
int solve_btsp = ARROW_FALSE
int lower_bound = -1
int upper_bound = INT_MAX
int basic_attempts = 1
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck traveling salesman problem (BTSP) solver"
char * usage = "-i tsplib.tsp [options]"
Detailed Description
Asymmetric Bottleneck TSP heuristic using RAI heuristic.
Runs the Bottleneck TSP heuristic on the given asymmetric input file.
Author:
John LaRusic
Definition in file abtsp-rai.c.
Define Documentation
#define NUM_OPTS 9
Definition at line 26 of file abtsp-rai.c.
#define SOLVE_STEPS 1
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 56 of file abtsp-rai.c.
References arrow_btsp_fun_basic(), arrow_btsp_fun_destruct(), arrow_btsp_params_init(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_result_print_pretty(), arrow_btsp_result_print_xml(), arrow_btsp_solve(), ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_RAI, arrow_util_print_program_args(), arrow_util_random_seed(), arrow_util_write_tour(), arrow_util_zeit(), basic_attempts, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list_length, desc, arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_problem::get_cost, input_file, arrow_tsp_rai_params::iterations, iterations, arrow_btsp_params::lower_bound, lower_bound, arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_problem_info::min_cost, NUM_OPTS, arrow_btsp_params::num_steps, arrow_problem::size, solve_btsp, arrow_tsp_rai_params::solve_btsp, SOLVE_STEPS, arrow_btsp_params::steps, supress_ebst, arrow_btsp_params::supress_ebst, arrow_problem::symmetric, arrow_btsp_result::tour, tour_file, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, upper_bound, usage, and xml_file.
Variable Documentation
int basic_attempts = 1
Definition at line 23 of file abtsp-rai.c.
Referenced by main().
char* desc = "Bottleneck traveling salesman problem (BTSP) solver"
Definition at line 51 of file abtsp-rai.c.
char* input_file = NULL
Definition at line 15 of file abtsp-rai.c.
int iterations = -1
Definition at line 18 of file abtsp-rai.c.
Referenced by main().
int lower_bound = -1
Definition at line 21 of file abtsp-rai.c.
Referenced by main().
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "file to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE},
    {'T', "tour", "file to write tour to",
        ARROW_OPTION_STRING, &tour_file, ARROW_FALSE, ARROW_TRUE},
    {'r', "iterations", "number of RAI iterations",
        ARROW_OPTION_INT, &iterations, ARROW_FALSE, ARROW_TRUE},
    {'b', "solve-btsp", "use BTSP formulation in RAI algorithm",
        ARROW_OPTION_INT, &solve_btsp, ARROW_FALSE, ARROW_FALSE},
    {'e', "supress-ebst", "supress binary search",
        ARROW_OPTION_INT, &supress_ebst, ARROW_FALSE, ARROW_FALSE},
    {'l', "lower-bound", "initial lower bound",
        ARROW_OPTION_INT, &lower_bound, ARROW_FALSE, ARROW_TRUE},
    {'u', "upper-bound", "initial upper bound",
        ARROW_OPTION_INT, &upper_bound, ARROW_FALSE, ARROW_TRUE},
    {'a', "basic-attempts", "number of basic attempts",
        ARROW_OPTION_INT, &basic_attempts, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 27 of file abtsp-rai.c.
int solve_btsp = ARROW_FALSE
Definition at line 20 of file abtsp-rai.c.
Referenced by main().
int supress_ebst = ARROW_FALSE
Definition at line 19 of file abtsp-rai.c.
Referenced by main().
char* tour_file = NULL
Definition at line 17 of file abtsp-rai.c.
Referenced by main().
int upper_bound = INT_MAX
Definition at line 22 of file abtsp-rai.c.
Referenced by arrow_btsp_solve(), and main().
char* usage = "-i tsplib.tsp [options]"
Definition at line 52 of file abtsp-rai.c.
char* xml_file = NULL
Definition at line 16 of file abtsp-rai.c.