Arrow: lib/arrow.h File Reference
lib/arrow.h File Reference
Header file for the Arrow callable library.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <float.h>
#include <regex.h>
#include <getopt.h>
#include "concorde.h"
Data Structures
struct arrow_bound_result
A lower bound result.
struct arrow_bintree
Binary tree data structure.
struct arrow_bintree_node
Binary tree node.
struct arrow_problem
Problem data structure.
struct arrow_problem_info
Problem information data structure.
struct arrow_tsp_lk_params
LK algorithm parameters.
struct arrow_tsp_result
TSP result (including result from LK heuristic).
struct arrow_btsp_result
BTSP result.
struct arrow_btsp_fun
BTSP Cost matrix function definition.
struct arrow_btsp_solve_plan
BTSP feasibility solve step plan.
struct arrow_btsp_params
BTSP algorithm parameters.
struct arrow_option
Program options structure.
Defines
#define ARROW_DEBUG
#define arrow_debug printf
#define ARROW_VERSION "1.0"
#define ARROW_DEV_NULL "/dev/null"
#define ARROW_SUCCESS 1
#define ARROW_FAILURE 0
#define ARROW_ERROR_INPUT 0
#define ARROW_ERROR_FATAL -1
#define ARROW_ERROR_NON_FATAL -2
#define ARROW_TRUE 1
#define ARROW_FALSE 0
#define ARROW_BTSP_SOLVE_PLAN_BASIC 1
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED 2
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED_SHAKE 3
#define ARROW_DEFAULT_BASIC_ATTEMPTS 3
#define ARROW_OPTION_INT 1
#define ARROW_OPTION_DOUBLE 2
#define ARROW_OPTION_STRING 3
#define CONCORDE_SUCCESS 0
#define CONCORDE_FAILURE 1
#define arrow_print_error(message) arrow_util_print_error(__FILE__, __LINE__, message)
Functions
int arrow_2mb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the 2-max bound (2MB) on the given problem.
int arrow_dcbpb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the degree constrained bottleneck paths bound (DCBPB).
int arrow_bbssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
int arrow_bbssp_biconnected (arrow_problem *problem, int max_cost, int *result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
void arrow_bintree_init (arrow_bintree *tree)
Initializes the binary tree data structure.
void arrow_bintree_destruct (arrow_bintree *tree)
Destructs a binary tree data structure.
int arrow_bintree_insert (arrow_bintree *tree, int value)
Inserts a value into the binary tree.
int arrow_bintree_to_array (arrow_bintree *tree, int **array)
Initializes the binary tree data structure.
void arrow_bintree_print (arrow_bintree *tree)
Prints out the values of the binary tree.
int arrow_bscssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
int arrow_btsp_result_init (arrow_problem *problem, arrow_btsp_result *result)
Initializes the BTSP result structure.
void arrow_btsp_result_destruct (arrow_btsp_result *result)
Destructs a BTSP result structure.
int arrow_btsp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, arrow_btsp_result *result)
Solves TSP with Concorde's exact solver.
void arrow_btsp_params_init (arrow_btsp_params *params)
Inititalizes BTSP parameter structure.
void arrow_btsp_params_destruct (arrow_btsp_params *params)
Destructs a BTSP parameters structure.
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan *plan)
Inititalizes BTSP solve plan structure.
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan *plan)
Destructs a BTSP solve plan structure.
int arrow_btsp_fun_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies the given function to the given problem to create a new problem.
void arrow_btsp_fun_destruct (arrow_btsp_fun *fun)
Destructs a function structure.
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function.
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function for asymmetric problem instances.
int arrow_btsp_fun_constrained (int shallow, double feasible_length, int infinity, arrow_btsp_fun *fun)
Constrained BTSP to TSP function.
int arrow_btsp_fun_constrained_shake (int shallow, double feasible_length, int infinity, int rand_min, int rand_max, arrow_problem *problem, arrow_problem_info *info, arrow_btsp_fun *fun)
Constrained "Shake" BTSP to TSP function.
int arrow_options_parse (int num_opts, arrow_option options[], char *description, char *usage, int argc, char *argv[], int *opt_ind)
int arrow_problem_read (char *file_name, arrow_problem *problem)
Reads a problem from a TSPLIB file.
void arrow_problem_destruct (arrow_problem *problem)
Deallocates problem data structure.
int arrow_problem_info_get (arrow_problem *problem, arrow_problem_info *info)
Builds ordered cost list and finds min/max cost in a problem.
void arrow_problem_info_destruct (arrow_problem_info *info)
Deallocates problem info data structure.
void arrow_problem_print (arrow_problem *problem)
Prints out information about a problem.
int arrow_problem_get_cost (arrow_problem *problem, int i, int j)
Retrieves cost between nodes i and j.
int arrow_problem_read_tour (char *file_name, int size, int *tour)
Reads a TSPLIB tour file.
int arrow_problem_abtsp_to_sbtsp (arrow_problem *old_problem, int infinity, arrow_problem *new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
int arrow_tsp_result_init (arrow_problem *problem, arrow_tsp_result *result)
Initializes the TSP result structure.
void arrow_tsp_result_destruct (arrow_tsp_result *result)
Destructs a TSP result structure.
void arrow_tsp_lk_params_init (arrow_problem *problem, arrow_tsp_lk_params *params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
void arrow_tsp_lk_params_destruct (arrow_tsp_lk_params *params)
Destructs a LK parameters structure.
int arrow_tsp_exact_solve (arrow_problem *problem, int *initial_tour, arrow_tsp_result *result)
Solves TSP with Concorde's exact solver.
int arrow_tsp_lk_solve (arrow_problem *problem, arrow_tsp_lk_params *params, arrow_tsp_result *result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
int arrow_util_create_int_array (int size, int **array)
Creates an integer array.
int arrow_util_create_int_matrix (int rows, int cols, int ***matrix, int **space)
Creates a full integer matrix.
void arrow_util_print_error (const char *file_name, int line_num, const char *message)
Prints an error message to stderr with consistent formatting.
double arrow_util_zeit ()
Used to measure timings.
void arrow_util_redirect_stdout_to_file (const char *filename, int *old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup *from, CCdatagroup *to)
Makes a shallow copy of the Concorde CCdatagroup structure.
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup *dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
int arrow_util_binary_search (int *array, int size, int element, int *pos)
Performs a binary search to find the wanted element in a sorted integer array.
int arrow_util_regex_match (char *string, char *pattern)
Determines if the given string turns up a match for the given regular expression pattern.
void arrow_util_print_program_args (int argc, char *argv[], FILE *out)
Prints out the given program arguments to the specified file.
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
int arrow_util_random ()
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
int arrow_util_random_between (int min, int max)
Returns a random number between min and max.
void arrow_util_write_tour (arrow_problem *problem, char *comment, int *tour, FILE *out)
void arrow_util_sbtsp_to_abstp_tour (arrow_problem *problem, int *old_tour, int *new_tour)
Detailed Description
Header file for the Arrow callable library.
Function prototypes and structures exposed by the callable library.
Author:
John LaRusic
Definition in file arrow.h.
Define Documentation
#define ARROW_BTSP_SOLVE_PLAN_BASIC 1
Definition at line 53 of file arrow.h.
Referenced by main().
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED 2
Definition at line 54 of file arrow.h.
Referenced by main().
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED_SHAKE 3
Definition at line 55 of file arrow.h.
Referenced by main().
#define arrow_debug printf
Definition at line 33 of file arrow.h.
Referenced by arrow_btsp_solve(), arrow_problem_print(), arrow_problem_read(), arrow_tsp_lk_solve(), feasible(), main(), and read_atsp().
#define ARROW_DEBUG
Definition at line 31 of file arrow.h.
#define ARROW_DEFAULT_BASIC_ATTEMPTS 3
Definition at line 57 of file arrow.h.
#define ARROW_DEV_NULL "/dev/null"
Definition at line 42 of file arrow.h.
Referenced by main().
#define ARROW_ERROR_FATAL -1
Definition at line 48 of file arrow.h.
Referenced by arrow_bbssp_biconnected(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_fun_apply(), arrow_btsp_fun_constrained(), arrow_problem_read_tour(), arrow_tsp_result_init(), construct_node(), insert_at(), read_atsp(), and strongly_connected().
#define ARROW_ERROR_INPUT 0
Definition at line 47 of file arrow.h.
#define ARROW_ERROR_NON_FATAL -2
Definition at line 49 of file arrow.h.
#define ARROW_FAILURE 0
Definition at line 45 of file arrow.h.
Referenced by arrow_bap_solve(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_fun_apply(), arrow_btsp_fun_basic_atsp(), arrow_btsp_fun_constrained_shake(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_dcbpb_solve(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_read(), arrow_tsp_exact_solve(), arrow_tsp_lk_solve(), arrow_util_binary_search(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), basic_shallow_apply(), build_initial_tour(), constrained_shake_deep_apply(), constrained_shallow_apply(), feasible(), and main().
#define ARROW_FALSE 0
Definition at line 51 of file arrow.h.
Referenced by arrow_bbssp_biconnected(), arrow_btsp_fun_basic(), arrow_btsp_fun_basic_atsp(), arrow_btsp_fun_constrained(), arrow_btsp_fun_constrained_shake(), arrow_btsp_params_init(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_read(), arrow_tsp_result_init(), arrow_util_regex_match(), basic_atsp_feasible(), basic_feasible(), build_initial_tour(), constrained_shake_feasible(), construct_node(), feasible(), ford_fulkerson_labeling(), insert_at(), main(), shortest_augmenting_path(), and strongly_connected().
#define ARROW_OPTION_DOUBLE 2
Definition at line 60 of file arrow.h.
Referenced by arrow_options_parse().
#define ARROW_OPTION_INT 1
Definition at line 59 of file arrow.h.
Referenced by arrow_options_parse().
#define ARROW_OPTION_STRING 3
Definition at line 61 of file arrow.h.
Referenced by arrow_options_parse().
#define arrow_print_error (message) arrow_util_print_error(__FILE__, __LINE__, message)
Definition at line 70 of file arrow.h.
Referenced by arrow_bbssp_solve(), arrow_btsp_fun_apply(), arrow_btsp_fun_basic_atsp(), arrow_btsp_fun_constrained(), arrow_btsp_fun_constrained_shake(), arrow_btsp_solve(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_read(), arrow_tsp_lk_solve(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), basic_shallow_apply(), build_initial_tour(), constrained_shake_deep_apply(), constrained_shallow_apply(), construct_node(), main(), read_args(), and read_atsp().
#define ARROW_SUCCESS 1
Definition at line 44 of file arrow.h.
Referenced by arrow_2mb_solve(), arrow_bap_solve(), arrow_bbssp_solve(), arrow_bintree_to_array(), arrow_bscssp_solve(), arrow_btsp_fun_apply(), arrow_btsp_fun_basic(), arrow_btsp_fun_basic_atsp(), arrow_btsp_fun_constrained(), arrow_btsp_fun_constrained_shake(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_dcbpb_solve(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_get(), arrow_problem_read(), arrow_problem_read_tour(), arrow_tsp_exact_solve(), arrow_tsp_lk_solve(), arrow_tsp_result_init(), arrow_util_binary_search(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), basic_atsp_deep_apply(), basic_deep_apply(), basic_shallow_apply(), build_initial_tour(), constrained_deep_apply(), constrained_shake_deep_apply(), constrained_shallow_apply(), construct_node(), feasible(), find_art_points(), insert_at(), main(), read_atsp(), shortest_augmenting_path(), and strongly_connected().
#define ARROW_TRUE 1
Definition at line 50 of file arrow.h.
Referenced by arrow_bbssp_biconnected(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_fun_basic(), arrow_btsp_fun_constrained(), arrow_btsp_solve(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_get(), arrow_problem_read(), arrow_tsp_lk_solve(), arrow_util_regex_match(), basic_atsp_feasible(), basic_feasible(), constrained_shake_feasible(), destruct_node(), feasible(), ford_fulkerson_labeling(), insert_at(), main(), shortest_augmenting_path(), strongly_connected(), and strongly_connected_dfs().
#define ARROW_VERSION "1.0"
Definition at line 41 of file arrow.h.
Referenced by print_version().
#define CONCORDE_FAILURE 1
Definition at line 64 of file arrow.h.
Referenced by arrow_tsp_lk_solve(), and build_initial_tour().
#define CONCORDE_SUCCESS 0
Definition at line 63 of file arrow.h.
Referenced by arrow_problem_read_tour().
Function Documentation
int arrow_2mb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the 2-max bound (2MB) on the given problem.
Parameters:
problem [in] problem data
info [in] problem info
result [out] 2MB solution
Definition at line 16 of file 2mb.c.
References ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::get_cost, arrow_bound_result::obj_value, arrow_problem::size, arrow_problem::symmetric, and arrow_bound_result::total_time.
Referenced by main().
int arrow_bbssp_biconnected (arrow_problem * problem, int max_cost, int * result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
Parameters:
problem [in] problem data
max_cost [in] value to check biconnectivity question against
result [out] ARROW_TRUE if biconnected, ARROW_FALSE otherwise.
Definition at line 94 of file bbssp.c.
References ARROW_ERROR_FATAL, ARROW_FALSE, ARROW_TRUE, arrow_util_create_int_array(), find_art_points(), and arrow_problem::size.
Referenced by arrow_bbssp_solve().
int arrow_bbssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BBSSP solution
Definition at line 44 of file bbssp.c.
References arrow_bbssp_biconnected(), ARROW_ERROR_FATAL, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, arrow_problem::symmetric, and arrow_bound_result::total_time.
Referenced by main().
void arrow_bintree_destruct (arrow_bintree * tree)
Destructs a binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 59 of file bintree.c.
References destruct_node(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), and constrained_shake_deep_apply().
void arrow_bintree_init (arrow_bintree * tree)
Initializes the binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 52 of file bintree.c.
References arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), and constrained_shake_deep_apply().
int arrow_bintree_insert (arrow_bintree * tree, int value)
Inserts a value into the binary tree.
Parameters:
tree [out] binary tree structure
value [in] value to insert into tree
Definition at line 66 of file bintree.c.
References construct_node(), insert_at(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), and constrained_shake_deep_apply().
void arrow_bintree_print (arrow_bintree * tree)
Prints out the values of the binary tree.
Parameters:
tree [in] binary tree structure
int arrow_bintree_to_array (arrow_bintree * tree, int ** array)
Initializes the binary tree data structure.
Parameters:
tree [out] binary tree structure
array [out] array to be created and filled
Definition at line 86 of file bintree.c.
References ARROW_SUCCESS, arrow_util_create_int_array(), fill_array(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), and constrained_shake_deep_apply().
int arrow_bscssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BSCSSP solution
Definition at line 43 of file bscssp.c.
References ARROW_ERROR_FATAL, ARROW_FAILURE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, strongly_connected(), and arrow_bound_result::total_time.
Referenced by main().
int arrow_btsp_fun_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies the given function to the given problem to create a new problem.
Parameters:
fun [in] function structure
old_problem [in] existing problem
delta [in] delta parameter
new_problem [out] new problem to create
Definition at line 213 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_ERROR_FATAL, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_CCdatagroup_init_matrix(), arrow_problem::data, arrow_problem::get_cost, arrow_problem::name, arrow_btsp_fun::shallow, arrow_problem::shallow, and arrow_problem::size.
Referenced by feasible().
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 249 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, basic_deep_apply(), basic_destruct(), basic_feasible(), basic_shallow_apply(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function for asymmetric problem instances.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 270 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, basic_atsp_deep_apply(), basic_atsp_destruct(), basic_atsp_feasible(), arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_constrained (int shallow, double feasible_length, int infinity, arrow_btsp_fun * fun)
Constrained BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
fun [out] function structure
Definition at line 291 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_ERROR_FATAL, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, basic_feasible(), constrained_deep_apply(), constrained_destruct(), constrained_shallow_apply(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_constrained_shake (int shallow, double feasible_length, int infinity, int rand_min, int rand_max, arrow_problem * problem, arrow_problem_info * info, arrow_btsp_fun * fun)
Constrained "Shake" BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
rand_min [in] minimum random value to generate
rand_max [in] maximum random value to generate
problem [in] the problem the shake is based upon
info [in] information about the original problem
fun [out] function structure
Definition at line 319 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, constrained_shake_deep_apply(), constrained_shake_destruct(), constrained_shake_feasible(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, constrained_shake_data::infinity, constrained_shake_data::info, constrained_shake_data::problem, constrained_shake_data::rand_max, constrained_shake_data::rand_min, and arrow_btsp_fun::shallow.
Referenced by main().
void arrow_btsp_fun_destruct (arrow_btsp_fun * fun)
Destructs a function structure.
Parameters:
fun [out] function structure
Definition at line 243 of file btsp_fun.c.
References arrow_btsp_fun::destruct.
Referenced by arrow_btsp_solve_plan_destruct(), and main().
void arrow_btsp_params_destruct (arrow_btsp_params * params)
Destructs a BTSP parameters structure.
Parameters:
result [out] BTSP parameters structure
Definition at line 71 of file btsp.c.
References arrow_btsp_solve_plan_destruct(), arrow_btsp_params::num_steps, and arrow_btsp_params::steps.
Referenced by main().
void arrow_btsp_params_init (arrow_btsp_params * params)
Inititalizes BTSP parameter structure.
Parameters:
params [out] BTSP parameters structure
Definition at line 60 of file btsp.c.
References ARROW_FALSE, arrow_btsp_params::confirm_sol, arrow_btsp_params::find_short_tour, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_params::supress_ebst, and arrow_btsp_params::upper_bound.
Referenced by main().
void arrow_btsp_result_destruct (arrow_btsp_result * result)
Destructs a BTSP result structure.
Parameters:
result [out] BTSP result structure
Definition at line 53 of file btsp.c.
References arrow_btsp_result::tour.
Referenced by arrow_btsp_solve(), and main().
int arrow_btsp_result_init (arrow_problem * problem, arrow_btsp_result * result)
Initializes the BTSP result structure.
Parameters:
problem [in] problem to solve
result [out] BTSP result structure
Definition at line 33 of file btsp.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, arrow_btsp_result::found_tour, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_result::obj_value, arrow_problem::size, arrow_btsp_result::total_time, arrow_btsp_result::tour, and arrow_btsp_result::tour_length.
Referenced by arrow_btsp_solve(), and main().
int arrow_btsp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, arrow_btsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
info [in] extra problem info
params [in] parameters for solver (can be NULL)
result [out] BTSP solution
Definition at line 98 of file btsp.c.
References arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_binary_search(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, feasible(), arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_params::steps, arrow_btsp_params::supress_ebst, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, upper_bound, and arrow_btsp_params::upper_bound.
Referenced by main().
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan * plan)
Destructs a BTSP solve plan structure.
Parameters:
result [out] BTSP solve plan structure
Definition at line 91 of file btsp.c.
References arrow_btsp_fun_destruct(), arrow_tsp_lk_params_destruct(), arrow_btsp_solve_plan::fun, and arrow_btsp_solve_plan::lk_params.
Referenced by arrow_btsp_params_destruct().
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan * plan)
Inititalizes BTSP solve plan structure.
Parameters:
params [out] BTSP solve plan structure
Definition at line 84 of file btsp.c.
References arrow_btsp_solve_plan::attempts, and arrow_btsp_solve_plan::plan_type.
int arrow_dcbpb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the degree constrained bottleneck paths bound (DCBPB).
Parameters:
problem [in] problem data
info [in] problem info
result [out] BPB solution
Definition at line 29 of file dcbpb.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_matrix(), arrow_util_zeit(), bottleneck_paths(), arrow_problem::get_cost, arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
int arrow_options_parse (int num_opts, arrow_option options[], char * description, char * usage, int argc, char * argv[], int * opt_ind)
Definition at line 24 of file options.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_OPTION_DOUBLE, ARROW_OPTION_INT, ARROW_OPTION_STRING, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_option::long_option, print_help(), print_usage(), print_version(), and arrow_option::short_option.
Referenced by main().
int arrow_problem_abtsp_to_sbtsp (arrow_problem * old_problem, int infinity, arrow_problem * new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
Parameters:
old_problem [in] the asymmetric problem
infinity [in] value to use as "infinity"
new_problem [out] the new symmetric problem
Definition at line 228 of file problem.c.
References ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_get_cost(), ARROW_SUCCESS, ARROW_TRUE, arrow_util_CCdatagroup_init_matrix(), arrow_problem::data, arrow_problem::get_cost, arrow_problem::name, arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
void arrow_problem_destruct (arrow_problem * problem)
Deallocates problem data structure.
Parameters:
problem [out] problem data structure
Definition at line 98 of file problem.c.
References arrow_problem::data, and arrow_problem::shallow.
Referenced by feasible(), and main().
int arrow_problem_get_cost (arrow_problem * problem, int i, int j) [inline]
Retrieves cost between nodes i and j.
Parameters:
problem [in] pointer to arrow_problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
cost between node i and node j
Definition at line 213 of file problem.c.
References arrow_problem::data.
Referenced by arrow_problem_abtsp_to_sbtsp(), and arrow_problem_read().
void arrow_problem_info_destruct (arrow_problem_info * info)
Deallocates problem info data structure.
Parameters:
info [in] problem info data structure
Definition at line 158 of file problem.c.
References arrow_problem_info::cost_list.
Referenced by main().
int arrow_problem_info_get (arrow_problem * problem, arrow_problem_info * info)
Builds ordered cost list and finds min/max cost in a problem.
Parameters:
problem [in] problem data structure
info [out] problem info data structure
Definition at line 115 of file problem.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_SUCCESS, ARROW_TRUE, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem::get_cost, arrow_problem_info::max_cost, arrow_problem_info::min_cost, arrow_bintree::size, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
void arrow_problem_print (arrow_problem * problem)
Prints out information about a problem.
Parameters:
problem [in] problem data structure
Definition at line 165 of file problem.c.
References arrow_debug, arrow_problem::get_cost, and arrow_problem::size.
int arrow_problem_read (char * file_name, arrow_problem * problem)
Reads a problem from a TSPLIB file.
Parameters:
file_name [in] path to TSPLIB file
problem [out] problem data structure
Definition at line 54 of file problem.c.
References arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_get_cost(), ARROW_SUCCESS, ARROW_TRUE, arrow_problem::data, arrow_problem::get_cost, is_asymmetric(), is_symmetric(), arrow_problem::name, read_atsp(), arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
int arrow_problem_read_tour (char * file_name, int size, int * tour)
Reads a TSPLIB tour file.
Parameters:
file_name [in] the TSPLIB tour file to read
size [in] the number of cities in the tour
tour [out] an array to hold the tour in node-node format
Definition at line 219 of file problem.c.
References ARROW_ERROR_FATAL, ARROW_SUCCESS, and CONCORDE_SUCCESS.
Referenced by main().
int arrow_tsp_exact_solve (arrow_problem * problem, int * initial_tour, arrow_tsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
in_tour [in] an initial tour (can be NULL)
result [out] TSP solution
Definition at line 66 of file tsp.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::data, arrow_tsp_result::found_tour, arrow_problem::name, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
void arrow_tsp_lk_params_destruct (arrow_tsp_lk_params * params)
Destructs a LK parameters structure.
Parameters:
result [out] LK parameters structure
Definition at line 59 of file tsp.c.
References arrow_tsp_lk_params::initial_tour.
Referenced by arrow_btsp_solve_plan_destruct(), arrow_tsp_lk_solve(), and main().
void arrow_tsp_lk_params_init (arrow_problem * problem, arrow_tsp_lk_params * params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
Parameters:
problem [in] problem to solve
params [out] LK parameters structure
Definition at line 47 of file tsp.c.
References arrow_tsp_lk_params::initial_tour, arrow_tsp_lk_params::kick_type, arrow_tsp_lk_params::kicks, arrow_tsp_lk_params::length_bound, arrow_tsp_lk_params::random_restarts, arrow_problem::size, arrow_tsp_lk_params::stall_count, and arrow_tsp_lk_params::time_bound.
Referenced by arrow_tsp_lk_solve(), and main().
int arrow_tsp_lk_solve (arrow_problem * problem, arrow_tsp_lk_params * params, arrow_tsp_result * result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Parameters:
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 102 of file tsp.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_lk_params_destruct(), arrow_tsp_lk_params_init(), arrow_util_zeit(), build_initial_tour(), CONCORDE_FAILURE, arrow_problem::data, arrow_tsp_result::found_tour, arrow_tsp_lk_params::initial_tour, arrow_tsp_lk_params::kick_type, arrow_tsp_lk_params::kicks, arrow_tsp_lk_params::length_bound, arrow_tsp_result::obj_value, arrow_tsp_lk_params::random_restarts, arrow_problem::size, arrow_tsp_lk_params::stall_count, arrow_tsp_lk_params::time_bound, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
void arrow_tsp_result_destruct (arrow_tsp_result * result)
Destructs a TSP result structure.
Parameters:
result [out] TSP result structure
Definition at line 37 of file tsp.c.
References arrow_tsp_result::tour.
Referenced by feasible(), and main().
int arrow_tsp_result_init (arrow_problem * problem, arrow_tsp_result * result)
Initializes the TSP result structure.
Parameters:
problem [in] problem to solve
result [out] TSP result structure
Definition at line 23 of file tsp.c.
References ARROW_ERROR_FATAL, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_tsp_result::found_tour, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
int arrow_util_binary_search (int * array, int size, int element, int * pos)
Performs a binary search to find the wanted element in a sorted integer array.
Parameters:
array [in] the array to search (note: must be sorted in non-increasing order)
size [in] size of the array
element [in] the element to find in the array
pos [out] the index where the element can be found in the array
Definition at line 145 of file util.c.
References ARROW_FAILURE, and ARROW_SUCCESS.
Referenced by arrow_btsp_solve(), and constrained_shake_deep_apply().
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup * dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
Parameters:
size [in] the number of cities/vertices
dat [out] the CCdatagroup structure to create
Definition at line 115 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_btsp_fun_apply(), and arrow_problem_abtsp_to_sbtsp().
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup * from, CCdatagroup * to)
Makes a shallow copy of the Concorde CCdatagroup structure.
Parameters:
from [in] the CCdatagroup structure to copy from to [out] the CCdatagroup structure to copy to
Definition at line 89 of file util.c.
int arrow_util_create_int_array (int size, int ** array) [inline]
Creates an integer array.
Parameters:
size [in] size of array
array [out] pointer to array that will be created
Definition at line 15 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bintree_to_array(), arrow_btsp_result_init(), arrow_tsp_result_init(), arrow_util_create_int_matrix(), main(), and strongly_connected().
int arrow_util_create_int_matrix (int rows, int cols, int *** matrix, int ** space) [inline]
Creates a full integer matrix.
Parameters:
rows [in] number of rows
cols [in] number of columns
matrix [out] pointer to matrix that will be created
space [out] pointer to matrix space that will be created
Definition at line 27 of file util.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, and arrow_util_create_int_array().
Referenced by arrow_bap_solve(), and arrow_dcbpb_solve().
void arrow_util_print_error (const char * file_name, int line_num, const char * message) [inline]
Prints an error message to stderr with consistent formatting.
Parameters:
file_name [in] file error occured in
line_num [in] line number error occured at
message [in] error message to write
Definition at line 56 of file util.c.
void arrow_util_print_program_args (int argc, char * argv[], FILE * out)
Prints out the given program arguments to the specified file.
Parameters:
argc [in] the number of arguments
argv [in] the program arugment array
out [in] the file handle to print out to
Definition at line 195 of file util.c.
Referenced by main().
int arrow_util_random () [inline]
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
Returns:
a random integer.
Definition at line 215 of file util.c.
int arrow_util_random_between (int min, int max) [inline]
Returns a random number between min and max.
Parameters:
min [in] the minimum random number to return
max [in] the maximum random number to return
Returns:
a random integer in the range [min, max]
Definition at line 221 of file util.c.
Referenced by constrained_shake_deep_apply().
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
Parameters:
seed [in] the random number seed.
Definition at line 206 of file util.c.
Referenced by main().
void arrow_util_redirect_stdout_to_file (const char * filename, int * old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
Parameters:
filename [in] name of file to direct STDOUT to
old_stream [out] existing file handle for STDOUT stream (necessary for restoring stream afterwards)
Definition at line 69 of file util.c.
Referenced by main().
int arrow_util_regex_match (char * string, char * pattern)
Determines if the given string turns up a match for the given regular expression pattern.
Parameters:
string [in] the string to match against
pattern [in] the regular expression pattern to match
Returns:
ARROW_TRUE if a match is found, ARROW_FALSE if not.
Definition at line 177 of file util.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by is_asymmetric(), and is_symmetric().
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
Parameters:
old_stream [in] existing file handle for STDOUT stream
Definition at line 78 of file util.c.
Referenced by main().
void arrow_util_sbtsp_to_abstp_tour (arrow_problem * problem, int * old_tour, int * new_tour)
Definition at line 246 of file util.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by main().
void arrow_util_write_tour (arrow_problem * problem, char * comment, int * tour, FILE * out)
Definition at line 227 of file util.c.
References arrow_problem::name, and arrow_problem::size.
Referenced by main().
double arrow_util_zeit () [inline]
Used to measure timings.
Returns:
a value representing the CPU time in seconds
Definition at line 63 of file util.c.
Referenced by arrow_2mb_solve(), arrow_bap_solve(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_solve(), arrow_dcbpb_solve(), arrow_tsp_exact_solve(), arrow_tsp_lk_solve(), and main().