Arrow: include/baltsp.h File Reference
include/baltsp.h File Reference
Functions for solving the bottleneck TSP.
#include "lb.h"
#include "btsp.h"
Data Structures
struct arrow_baltsp_params
BTSP algorithm parameters.
Functions
int arrow_balanced_tsp_db (arrow_problem *btsp_problem, arrow_problem *mstsp_problem, arrow_problem_info *info, arrow_baltsp_params *params, arrow_btsp_params *btsp_params, double *lb_time, arrow_btsp_result *tour_result)
int arrow_balanced_tsp_dt (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, int lb_only, int with_improvements, arrow_bound_result *lb_result, arrow_btsp_result *tour_result)
int arrow_balanced_tsp_dt2 (arrow_problem *problem, arrow_problem_info *info, arrow_baltsp_params *params, double *lb_time, arrow_btsp_result *tour_result)
int arrow_balanced_tsp_ib (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, int lb_only, int with_improvements, arrow_bound_result *lb_result, arrow_btsp_result *tour_result)
int arrow_balanced_tsp_ib2 (arrow_problem *problem, arrow_problem_info *info, arrow_baltsp_params *params, arrow_btsp_params *btsp_params, double *lb_time, arrow_btsp_result *tour_result)
int arrow_balanced_tsp_lb (arrow_problem *problem, arrow_problem_info *info, int btsp_min_cost, int btsp_max_cost, int mstsp_min_cost, int *lb_result)
int arrow_baltsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BalTSP to TSP function.
int arrow_baltsp_fun_ut (int shallow, arrow_btsp_fun *fun)
BalTSP to TSP function that favours values closer to the max_cost.
int arrow_baltsp_fun_shake (int shallow, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
BalTSP Controled Shake.
int arrow_baltsp_fun_ib (int shallow, arrow_btsp_fun *fun)
BalTSP Iterative Bottleneck transformation.
int arrow_baltsp_fun_dt2 (int shallow, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
void arrow_baltsp_params_init (arrow_baltsp_params *params)
Detailed Description
Functions for solving the bottleneck TSP.
Functions for solving the bottleneck TSP.
Author:
John LaRusic
Definition in file baltsp.h.
Function Documentation
int arrow_balanced_tsp_db (arrow_problem * btsp_problem, arrow_problem * mstsp_problem, arrow_problem_info * info, arrow_baltsp_params * params, arrow_btsp_params * btsp_params, double * lb_time, arrow_btsp_result * tour_result)
Definition at line 100 of file baltsp-db.c.
References arrow_baltsp_fun_ib(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, btsp_lower_bound(), arrow_baltsp_params::btsp_max_cost, arrow_baltsp_params::btsp_min_cost, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::found_tour, arrow_btsp_params::infinity, arrow_btsp_params::lower_bound, arrow_baltsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_baltsp_params::mstsp_min_cost, arrow_baltsp_params::num_steps, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, and arrow_baltsp_params::with_improvements.
Referenced by main().
int arrow_balanced_tsp_dt (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, int lb_only, int with_improvements, arrow_bound_result * lb_result, arrow_btsp_result * tour_result)
Definition at line 35 of file baltsp-dt.c.
References arrow_btsp_feasible(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_abtsp_to_sbtsp(), arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), balanced_lb_feasible(), arrow_btsp_result::bin_search_steps, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_params::deep_copy, arrow_btsp_result::found_tour, arrow_btsp_params::infinity, arrow_btsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_btsp_params::num_steps, arrow_bound_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_params::steps, arrow_problem::symmetric, arrow_bound_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, and arrow_btsp_params::upper_bound.
Referenced by main().
int arrow_balanced_tsp_dt2 (arrow_problem * problem, arrow_problem_info * info, arrow_baltsp_params * params, double * lb_time, arrow_btsp_result * tour_result)
Definition at line 36 of file baltsp-dt2.c.
References arrow_btsp_feasible(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_abtsp_to_sbtsp(), arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, arrow_baltsp_params::btsp_max_cost, arrow_baltsp_params::btsp_min_cost, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_baltsp_params::deep_copy, dt2_lb_feasible(), arrow_btsp_result::found_tour, arrow_baltsp_params::infinity, arrow_baltsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_baltsp_params::mstsp_min_cost, arrow_baltsp_params::num_steps, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_baltsp_params::steps, arrow_problem::symmetric, arrow_baltsp_params::timebound, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, and arrow_baltsp_params::with_improvements.
Referenced by main().
int arrow_balanced_tsp_ib (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, int lb_only, int with_improvements, arrow_bound_result * lb_result, arrow_btsp_result * tour_result)
Definition at line 100 of file baltsp-ib.c.
References arrow_baltsp_fun_ib(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_create_int_array(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, btsp_bounds(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, find_cost_order(), arrow_btsp_result::found_tour, arrow_btsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_problem_info::min_cost, arrow_btsp_params::num_steps, arrow_bound_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_bound_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, and arrow_btsp_params::upper_bound.
Referenced by main().
int arrow_balanced_tsp_ib2 (arrow_problem * problem, arrow_problem_info * info, arrow_baltsp_params * params, arrow_btsp_params * btsp_params, double * lb_time, arrow_btsp_result * tour_result)
Definition at line 100 of file baltsp-ib2.c.
References arrow_baltsp_fun_ib(), arrow_btsp_feasible(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, btsp_lower_bound(), arrow_baltsp_params::btsp_max_cost, arrow_baltsp_params::btsp_min_cost, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::found_tour, arrow_baltsp_params::infinity, arrow_btsp_params::lower_bound, arrow_baltsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_baltsp_params::mstsp_min_cost, arrow_baltsp_params::num_steps, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_baltsp_params::steps, arrow_problem::symmetric, arrow_baltsp_params::timebound, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, and arrow_baltsp_params::with_improvements.
Referenced by main().
int arrow_balanced_tsp_lb (arrow_problem * problem, arrow_problem_info * info, int btsp_min_cost, int btsp_max_cost, int mstsp_min_cost, int * lb_result)
Definition at line 100 of file baltsp-lb.c.
References arrow_baltsp_fun_ib(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_debug, ARROW_FAILURE, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, btsp_lower_bound(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, max(), and arrow_problem_info::max_cost.
Referenced by main().
int arrow_baltsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BalTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 206 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_feasible(), baltsp_basic_get_cost(), baltsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_dt2 (int shallow, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Definition at line 278 of file fun_baltsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), baltsp_dt2_feasible(), baltsp_dt2_get_cost(), baltsp_dt2_initialize(), baltsp_shake_destruct(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, arrow_btsp_fun::initialize, baltsp_shake_data::random_list, baltsp_shake_data::random_list_length, baltsp_shake_data::random_max, baltsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_ib (int shallow, arrow_btsp_fun * fun)
BalTSP Iterative Bottleneck transformation.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 266 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_initialize(), baltsp_ib_feasible(), baltsp_ib_get_cost(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), and btsp_bounds().
int arrow_baltsp_fun_shake (int shallow, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
BalTSP Controled Shake.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 230 of file fun_baltsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), baltsp_basic_feasible(), baltsp_shake_destruct(), baltsp_shake_get_cost(), baltsp_shake_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, arrow_btsp_fun::initialize, baltsp_shake_data::random_list, baltsp_shake_data::random_list_length, baltsp_shake_data::random_max, baltsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_ut (int shallow, arrow_btsp_fun * fun)
BalTSP to TSP function that favours values closer to the max_cost.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 218 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_initialize(), baltsp_ut_feasible(), baltsp_ut_get_cost(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
void arrow_baltsp_params_init (arrow_baltsp_params * params)
Definition at line 16 of file params.c.
References ARROW_FALSE, arrow_baltsp_params::btsp_max_cost, arrow_baltsp_params::btsp_min_cost, arrow_baltsp_params::lower_bound, arrow_baltsp_params::mstsp_min_cost, arrow_baltsp_params::num_steps, arrow_baltsp_params::timebound, and arrow_baltsp_params::with_improvements.
Referenced by main().