Arrow: /Users/johnlarusic/Dev/arrow2/src/bin/bbssp.c File Reference
/Users/johnlarusic/Dev/arrow2/src/bin/bbssp.c File Reference
Bottleneck Biconnected Spanning Subgraph solver.
#include "arrow.h"
#include <getopt.h>
Functions
int main (int argc, char *argv[])
Entry point to program.
void print_help (char *program_name)
Prints usage/help message.
void print_version (char *program_name)
Prints version message.
void print_usage (char *program_name)
Prints usage message.
Variables
static char * short_options = "hV"
Short argument options to getopt.
static struct option long_options []
Long argument options to getopt.
Detailed Description
Bottleneck Biconnected Spanning Subgraph solver.
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) problem on the given input files.
Author:
John LaRusic
Definition in file bbssp.c.
Function Documentation
int main (int argc, char * argv[])
Entry point to program.
Definition at line 55 of file bbssp.c.
References long_options, print_help(), print_usage(), print_version(), and short_options.
void print_help (char * program_name)
Prints usage/help message.
Parameters:
program_name [in] name of program
Definition at line 98 of file bbssp.c.
References print_usage().
Referenced by main().
void print_usage (char * program_name)
Prints usage message.
Parameters:
program_name [in] name of program
Definition at line 126 of file bbssp.c.
Referenced by main(), and print_help().
void print_version (char * program_name)
Prints version message.
Parameters:
program_name [in] name of program
Definition at line 112 of file bbssp.c.
Referenced by main().
Variable Documentation
struct option long_options[] [static]
Initial value:
{
        {"help", no_argument, 0, 'h'},
        {"version", no_argument, 0, 'V'}
}
Long argument options to getopt.
Definition at line 44 of file bbssp.c.
Referenced by main().
char* short_options = "hV" [static]
Short argument options to getopt.
Definition at line 39 of file bbssp.c.
Referenced by main().