Arrow: bin/baltsp-lb.c File Reference
bin/baltsp-lb.c File Reference
Bottleneck Assignment Problem solver.
#include "common.h"
#include "baltsp.h"
Defines
#define NUM_OPTS 6
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
char * xml_file = NULL
int deep_copy = ARROW_FALSE
int btsp_min_cost = -1
int btsp_max_cost = -1
int mstsp_min_cost = -1
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck assignment problem solver"
char * usage = "-i tsplib.tsp [options] "
Detailed Description
Bottleneck Assignment Problem solver.
Solves the bottleneck assignment problem (BAP) on the given input file.
Author:
John LaRusic
Definition in file baltsp-lb.c.
Define Documentation
#define NUM_OPTS 6
Definition at line 22 of file baltsp-lb.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 44 of file baltsp-lb.c.
References arrow_balanced_tsp_lb(), ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_SUCCESS, arrow_util_print_program_args(), arrow_util_zeit(), btsp_max_cost, btsp_min_cost, desc, input_file, mstsp_min_cost, NUM_OPTS, usage, and xml_file.
Variable Documentation
int btsp_max_cost = -1
Definition at line 18 of file baltsp-lb.c.
int btsp_min_cost = -1
Definition at line 17 of file baltsp-lb.c.
int deep_copy = ARROW_FALSE
Definition at line 16 of file baltsp-lb.c.
char* desc = "Bottleneck assignment problem solver"
Definition at line 39 of file baltsp-lb.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 14 of file baltsp-lb.c.
int mstsp_min_cost = -1
Definition at line 19 of file baltsp-lb.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "File to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE},
    {'d', "deep-copy", "stores data in full cost-matrix",
        ARROW_OPTION_INT, &deep_copy, ARROW_FALSE, ARROW_FALSE},
    {'t', "btsp-min-cost", "min cost in BTSP tour",
        ARROW_OPTION_INT, &btsp_min_cost, ARROW_FALSE, ARROW_TRUE},
    {'u', "btsp-max-cost", "max cost in BTSP tour",
        ARROW_OPTION_INT, &btsp_max_cost, ARROW_FALSE, ARROW_TRUE},
    {'v', "mstsp-min-cost", "min cost in MSTSP tour",
        ARROW_OPTION_INT, &mstsp_min_cost, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 23 of file baltsp-lb.c.
char* program_name
Program name
Definition at line 13 of file baltsp-lb.c.
char* usage = "-i tsplib.tsp [options] "
Definition at line 40 of file baltsp-lb.c.
char* xml_file = NULL
Definition at line 15 of file baltsp-lb.c.