Arrow: bin/cbst.c File Reference
bin/cbst.c File Reference
Constrained bottleneck spanning tree solver.
#include "common.h"
#include "lb.h"
Defines
#define NUM_OPTS 3
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
char * xml_file = NULL
double max_length = -1.0
arrow_option options [NUM_OPTS]
char * desc = "Constrained bottleneck spanning tree solver"
char * usage = "-i tsplib.tsp [options] "
Detailed Description
Constrained bottleneck spanning tree solver.
Solves the constrained bottleneck spanning tree (CBST) problem the given input file.
Author:
John LaRusic
Definition in file cbst.c.
Define Documentation
#define NUM_OPTS 3
Definition at line 20 of file cbst.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file cbst.c.
References arrow_cbst_solve(), ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_SUCCESS, arrow_util_print_program_args(), desc, input_file, max_length, NUM_OPTS, arrow_bound_result::obj_value, arrow_bound_result::total_time, usage, and xml_file.
Variable Documentation
char* desc = "Constrained bottleneck spanning tree solver"
Definition at line 30 of file cbst.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 15 of file cbst.c.
double max_length = -1.0
Definition at line 17 of file cbst.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "File to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE},
    {'L', "length", "Maximum length of spanning tree",
        ARROW_OPTION_DOUBLE, &max_length, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 21 of file cbst.c.
char* program_name
Program name
Definition at line 14 of file cbst.c.
char* usage = "-i tsplib.tsp [options] "
Definition at line 31 of file cbst.c.
char* xml_file = NULL
Definition at line 16 of file cbst.c.