Arrow: bin/bbssp.c File Reference
bin/bbssp.c File Reference
Bottleneck Biconnected Spanning Subgraph solver.
#include "arrow.h"
#include <getopt.h>
Functions
void print_help ()
Prints help/usage message.
void print_version ()
Prints version message.
void print_usage ()
Prints usage message.
void read_args (int argc, char *argv[])
Reads program arguments.
void print_xml_output (int obj_value, double total_time, int argc, char *argv[])
Prints output in XML format.
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file
int xml_output = ARROW_FALSE
Detailed Description
Bottleneck Biconnected Spanning Subgraph solver.
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) problem on the given input files.
Author:
John LaRusic
Definition in file bbssp.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 52 of file bbssp.c.
References arrow_bbssp_solve(), ARROW_DEV_NULL, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), arrow_util_redirect_stdout_to_file(), arrow_util_restore_stdout(), input_file, arrow_bbssp_result::obj_value, print_xml_output(), program_name, read_args(), arrow_bbssp_result::total_time, and xml_output.
void print_help ()
Prints help/usage message.
Definition at line 100 of file bbssp.c.
References print_usage(), and program_name.
Referenced by read_args().
void print_usage ()
Prints usage message.
Definition at line 131 of file bbssp.c.
References program_name.
Referenced by print_help(), and read_args().
void print_version ()
Prints version message.
Definition at line 116 of file bbssp.c.
References program_name.
Referenced by read_args().
void print_xml_output (int obj_value, double total_time, int argc, char * argv[])
Prints output in XML format.
Definition at line 191 of file bbssp.c.
References input_file.
Referenced by main().
void read_args (int argc, char * argv[])
Reads program arguments.
Definition at line 137 of file bbssp.c.
References arrow_print_error, ARROW_TRUE, input_file, print_help(), print_usage(), print_version(), and xml_output.
Referenced by main().
Variable Documentation
char* input_file
Given input TSPLIB file
Definition at line 45 of file bbssp.c.
Referenced by main(), print_xml_output(), and read_args().
char* program_name
Program name
Definition at line 44 of file bbssp.c.
Referenced by main(), print_help(), print_usage(), and print_version().
int xml_output = ARROW_FALSE
Output output in XML format (or not)
Definition at line 46 of file bbssp.c.
Referenced by main(), and read_args().