Arrow: bin/2mb.c File Reference
bin/2mb.c File Reference
2-Max Bound solver.
#include "common.h"
#include "lb.h"
Defines
#define NUM_OPTS 4
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
char * xml_file = NULL
int solve_mstsp = ARROW_FALSE
int deep_copy = ARROW_FALSE
arrow_option options [NUM_OPTS]
char * desc = "2-Max Bound solver"
char * usage = "-i tsplib.tsp [options] "
Detailed Description
2-Max Bound solver.
Solves the 2-max bound (2MB) on the given input file.
Author:
John LaRusic
Definition in file 2mb.c.
Define Documentation
#define NUM_OPTS 4
Definition at line 20 of file 2mb.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file 2mb.c.
References arrow_2mb_solve(), ARROW_FAILURE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_max_cost(), arrow_problem_mstsp_to_btsp(), arrow_problem_read(), ARROW_SUCCESS, arrow_util_print_program_args(), deep_copy, desc, input_file, NUM_OPTS, arrow_bound_result::obj_value, solve_mstsp, arrow_bound_result::total_time, usage, and xml_file.
Variable Documentation
int deep_copy = ARROW_FALSE
Definition at line 17 of file 2mb.c.
Referenced by main().
char* desc = "2-Max Bound solver"
Definition at line 32 of file 2mb.c.
Referenced by main().
char* input_file = NULL
Given input TSPLIB file
Definition at line 14 of file 2mb.c.
Referenced by main(), and read_args().
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "File to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE},
    {'m', "solve-mstsp", "solves maximum scatter TSP",
        ARROW_OPTION_INT, &solve_mstsp, ARROW_FALSE, ARROW_FALSE},
    {'d', "deep-copy", "stores data in full cost-matrix",
        ARROW_OPTION_INT, &deep_copy, ARROW_FALSE, ARROW_FALSE}
}
Definition at line 21 of file 2mb.c.
char* program_name
Program name
Definition at line 13 of file 2mb.c.
Referenced by main(), print_help(), print_usage(), and print_version().
int solve_mstsp = ARROW_FALSE
Definition at line 16 of file 2mb.c.
Referenced by main().
char* usage = "-i tsplib.tsp [options] "
Definition at line 33 of file 2mb.c.
Referenced by main().
char* xml_file = NULL
Definition at line 15 of file 2mb.c.
Referenced by main().