Arrow: bin/tsp.c File Reference
bin/tsp.c File Reference
Traveling Salesman Problem solver.
#include "common.h"
#include "lb.h"
#include "tsp.h"
Functions
void print_help ()
Prints help/usage message.
void print_version ()
Prints version message.
void print_usage ()
Prints usage message.
void read_args (int argc, char *argv[])
Reads program arguments.
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file
Detailed Description
Traveling Salesman Problem solver.
Solves the traveling salesman problem (TSP) on the given input file. This is really nothing more than a wrapper to Concorde, and is for testing purposes only. Use Concorde's executable for access to solve options.
Author:
John LaRusic
Definition in file tsp.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 46 of file tsp.c.
References arrow_print_error, arrow_problem_destruct(), arrow_problem_read(), arrow_tsp_cc_exact_solve(), arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_tsp_result::found_tour, input_file, arrow_tsp_result::obj_value, program_name, read_args(), and arrow_tsp_result::total_time.
void print_help ()
Prints help/usage message.
void print_usage ()
Prints usage message.
void print_version ()
Prints version message.
void read_args (int argc, char * argv[])
Reads program arguments.
Variable Documentation
char* input_file
Given input TSPLIB file
Definition at line 40 of file tsp.c.
char* program_name
Program name
Definition at line 39 of file tsp.c.