Arrow: bin/bap.c File Reference
bin/bap.c File Reference
Bottleneck Assignment Problem solver.
#include "arrow.h"
Defines
#define NUM_OPTS 2
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
char * xml_file = NULL
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck assignment problem solver"
char * usage = "-i tsplib.tsp [options] "
Detailed Description
Bottleneck Assignment Problem solver.
Solves the bottleneck assignment problem (BAP) on the given input file.
Author:
John LaRusic
Definition in file bap.c.
Define Documentation
#define NUM_OPTS 2
Definition at line 17 of file bap.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 30 of file bap.c.
References arrow_bap_solve(), ARROW_FAILURE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_SUCCESS, arrow_util_print_program_args(), desc, input_file, NUM_OPTS, arrow_bound_result::obj_value, arrow_bound_result::total_time, usage, and xml_file.
Variable Documentation
char* desc = "Bottleneck assignment problem solver"
Definition at line 25 of file bap.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 13 of file bap.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'x', "xml", "File to write XML output to",
        ARROW_OPTION_STRING, &xml_file, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 18 of file bap.c.
char* program_name
Program name
Definition at line 12 of file bap.c.
char* usage = "-i tsplib.tsp [options] "
Definition at line 26 of file bap.c.
char* xml_file = NULL
Definition at line 14 of file bap.c.