Arrow: bin/baltsp-db.c File Reference
bin/baltsp-db.c File Reference
Balanced-DT TSP heuristic.
#include "common.h"
#include "lb.h"
#include "tsp.h"
#include "baltsp.h"
Defines
#define NUM_OPTS 19
#define BALTSP_SOLVE_STEPS 0
#define BTSP_SOLVE_STEPS 2
Functions
int main (int argc, char *argv[])
Variables
char * input_file = NULL
char * xml_file = NULL
char * tour_file = NULL
int edge_infinity = -1
int random_restarts = -1
int stall_count = -1
int kicks = -1
int supress_hash = ARROW_FALSE
int deep_copy = ARROW_FALSE
int lower_bound = -1
int btsp_min_cost = -1
int btsp_max_cost = -1
int mstsp_min_cost = -1
int basic_attempts = 1
int shake_attempts = 0
int shake_rand_min = 0
int shake_rand_max = -1
int random_seed = 0
int with_improvements = ARROW_FALSE
arrow_option options [NUM_OPTS]
char * desc = "Balanced traveling salesman problem (BalTSP) solver"
char * usage = "-i tsplib.tsp [options]"
Detailed Description
Balanced-DT TSP heuristic.
Runs the Balanced-DT TSP heuristic on the given input file.
Author:
John LaRusic
Definition in file baltsp-db.c.
Define Documentation
#define BALTSP_SOLVE_STEPS 0
Referenced by main().
#define BTSP_SOLVE_STEPS 2
Referenced by main().
#define NUM_OPTS 19
Definition at line 36 of file baltsp-db.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 87 of file baltsp-db.c.
References arrow_balanced_tsp_db(), arrow_baltsp_params_init(), arrow_btsp_fun_basic(), arrow_btsp_fun_destruct(), arrow_btsp_fun_shake_1(), arrow_btsp_params_init(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_get(), arrow_problem_mstsp_to_btsp(), arrow_problem_read(), ARROW_TSP_CC_LK, arrow_tsp_cc_lk_params_destruct(), arrow_tsp_cc_lk_params_init(), arrow_tsp_long_name(), arrow_tsp_short_name(), ARROW_TSP_SOLVER_COUNT, arrow_util_print_program_args(), arrow_util_random_seed(), arrow_util_write_tour(), arrow_util_zeit(), arrow_xml_attribute_end(), arrow_xml_attribute_int(), arrow_xml_attribute_start(), arrow_xml_element_bool(), arrow_xml_element_close(), arrow_xml_element_double(), arrow_xml_element_end(), arrow_xml_element_int(), arrow_xml_element_open(), arrow_xml_element_start(), BALTSP_SOLVE_STEPS, basic_attempts, arrow_btsp_result::bin_search_steps, arrow_baltsp_params::btsp_max_cost, btsp_max_cost, arrow_baltsp_params::btsp_min_cost, btsp_min_cost, BTSP_SOLVE_STEPS, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list_length, arrow_btsp_params::deep_copy, arrow_baltsp_params::deep_copy, deep_copy, desc, edge_infinity, arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_problem::get_cost, arrow_btsp_params::infinity, arrow_baltsp_params::infinity, input_file, arrow_tsp_cc_lk_params::kicks, kicks, arrow_tsp_cc_lk_params::length_bound, arrow_btsp_params::lower_bound, arrow_baltsp_params::lower_bound, lower_bound, arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_problem_info::min_cost, arrow_baltsp_params::mstsp_min_cost, mstsp_min_cost, NUM_OPTS, arrow_btsp_params::num_steps, arrow_baltsp_params::num_steps, arrow_tsp_cc_lk_params::random_restarts, random_restarts, random_seed, shake_attempts, shake_rand_max, shake_rand_min, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_tsp_cc_lk_params::stall_count, stall_count, arrow_btsp_params::steps, arrow_baltsp_params::steps, arrow_btsp_params::supress_ebst, supress_hash, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, tour_file, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, usage, with_improvements, arrow_baltsp_params::with_improvements, and xml_file.
Variable Documentation
int basic_attempts = 1
Definition at line 28 of file baltsp-db.c.
int btsp_max_cost = -1
Definition at line 26 of file baltsp-db.c.
Referenced by main().
int btsp_min_cost = -1
Definition at line 25 of file baltsp-db.c.
Referenced by main().
int deep_copy = ARROW_FALSE
Definition at line 23 of file baltsp-db.c.
char* desc = "Balanced traveling salesman problem (BalTSP) solver"
Definition at line 82 of file baltsp-db.c.
int edge_infinity = -1
Definition at line 18 of file baltsp-db.c.
Referenced by main().
char* input_file = NULL
Definition at line 15 of file baltsp-db.c.
int kicks = -1
Definition at line 21 of file baltsp-db.c.
Referenced by main(), and read_args().
int lower_bound = -1
Definition at line 24 of file baltsp-db.c.
int mstsp_min_cost = -1
Definition at line 27 of file baltsp-db.c.
Referenced by main().
arrow_option options[NUM_OPTS]
Definition at line 37 of file baltsp-db.c.
int random_restarts = -1
Definition at line 19 of file baltsp-db.c.
Referenced by main(), and read_args().
int random_seed = 0
Definition at line 32 of file baltsp-db.c.
Referenced by main().
int shake_attempts = 0
Definition at line 29 of file baltsp-db.c.
Referenced by main().
int shake_rand_max = -1
Definition at line 31 of file baltsp-db.c.
Referenced by main().
int shake_rand_min = 0
Definition at line 30 of file baltsp-db.c.
Referenced by main().
int stall_count = -1
Definition at line 20 of file baltsp-db.c.
Referenced by main(), and read_args().
int supress_hash = ARROW_FALSE
Definition at line 22 of file baltsp-db.c.
Referenced by main().
char* tour_file = NULL
Definition at line 17 of file baltsp-db.c.
char* usage = "-i tsplib.tsp [options]"
Definition at line 83 of file baltsp-db.c.
int with_improvements = ARROW_FALSE
Definition at line 33 of file baltsp-db.c.
Referenced by main().
char* xml_file = NULL
Definition at line 16 of file baltsp-db.c.