Arrow: bin/btsp.c File Reference
bin/btsp.c File Reference
Bottleneck TSP heuristic.
#include "common.h"
#include "lb.h"
#include "tsp.h"
#include "btsp.h"
Defines
#define NUM_OPTS 21
#define SOLVE_STEPS 2
Functions
int main (int argc, char *argv[])
Variables
char * input_file = NULL
char * xml_file = NULL
char * tour_file = NULL
int edge_infinity = -1
int stall_count = -1
int kicks = -1
int solve_mstsp = ARROW_FALSE
int confirm_sol = ARROW_FALSE
int supress_ebst = ARROW_FALSE
int find_short_tour = ARROW_FALSE
int supress_hash = ARROW_FALSE
int deep_copy = ARROW_FALSE
int lower_bound = -1
int upper_bound = INT_MAX
int basic_attempts = 3
int basic_restarts = 1
int shake_1_attempts = 1
int shake_1_restarts = 1
int shake_1_rand_min = 0
int shake_1_rand_max = -1
int random_seed = 0
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck traveling salesman problem (BTSP) solver"
char * usage = "-i tsplib.tsp [options]"
Detailed Description
Bottleneck TSP heuristic.
Runs the Bottleneck TSP heuristic on the given input file.
Author:
John LaRusic
Definition in file btsp.c.
Define Documentation
#define NUM_OPTS 21
Definition at line 38 of file btsp.c.
#define SOLVE_STEPS 2
Function Documentation
int main (int argc, char * argv[])
Definition at line 95 of file btsp.c.
References arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_destruct(), arrow_btsp_fun_shake_1(), arrow_btsp_params_init(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_result_print_pretty(), arrow_btsp_result_print_xml(), arrow_btsp_solve(), ARROW_FAILURE, arrow_options_parse(), arrow_print_error, arrow_problem_abtsp_to_sbtsp(), arrow_problem_destruct(), arrow_problem_info_get(), arrow_problem_max_cost(), arrow_problem_mstsp_to_btsp(), arrow_problem_read(), ARROW_SUCCESS, ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, arrow_tsp_cc_lk_params_destruct(), arrow_tsp_cc_lk_params_init(), arrow_util_create_int_array(), arrow_util_print_program_args(), arrow_util_random_seed(), arrow_util_sbtsp_to_abstp_tour(), arrow_util_write_tour(), arrow_util_zeit(), basic_attempts, basic_restarts, arrow_btsp_params::confirm_plan, confirm_sol, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list_length, deep_copy, desc, edge_infinity, find_short_tour, arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_problem::get_cost, input_file, arrow_tsp_cc_lk_params::kicks, kicks, arrow_tsp_cc_lk_params::length_bound, arrow_btsp_params::lower_bound, lower_bound, arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_problem_info::min_cost, NUM_OPTS, arrow_btsp_params::num_steps, arrow_tsp_cc_lk_params::random_restarts, random_seed, shake_1_attempts, shake_1_rand_max, shake_1_rand_min, shake_1_restarts, arrow_problem::size, solve_mstsp, SOLVE_STEPS, arrow_tsp_cc_lk_params::stall_count, stall_count, arrow_btsp_params::steps, supress_ebst, arrow_btsp_params::supress_ebst, supress_hash, arrow_problem::symmetric, arrow_btsp_result::tour, tour_file, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, upper_bound, usage, and xml_file.
Variable Documentation
int basic_attempts = 3
Definition at line 29 of file btsp.c.
int basic_restarts = 1
Definition at line 30 of file btsp.c.
Referenced by main().
int confirm_sol = ARROW_FALSE
Definition at line 22 of file btsp.c.
Referenced by main().
int deep_copy = ARROW_FALSE
Definition at line 26 of file btsp.c.
char* desc = "Bottleneck traveling salesman problem (BTSP) solver"
Definition at line 90 of file btsp.c.
int edge_infinity = -1
Definition at line 18 of file btsp.c.
int find_short_tour = ARROW_FALSE
Definition at line 24 of file btsp.c.
Referenced by main().
char* input_file = NULL
Definition at line 15 of file btsp.c.
int kicks = -1
Definition at line 20 of file btsp.c.
int lower_bound = -1
Definition at line 27 of file btsp.c.
arrow_option options[NUM_OPTS]
Definition at line 39 of file btsp.c.
int random_seed = 0
Definition at line 35 of file btsp.c.
int shake_1_attempts = 1
Definition at line 31 of file btsp.c.
Referenced by main().
int shake_1_rand_max = -1
Definition at line 34 of file btsp.c.
Referenced by main().
int shake_1_rand_min = 0
Definition at line 33 of file btsp.c.
Referenced by main().
int shake_1_restarts = 1
Definition at line 32 of file btsp.c.
Referenced by main().
int solve_mstsp = ARROW_FALSE
Definition at line 21 of file btsp.c.
int stall_count = -1
Definition at line 19 of file btsp.c.
int supress_ebst = ARROW_FALSE
Definition at line 23 of file btsp.c.
int supress_hash = ARROW_FALSE
Definition at line 25 of file btsp.c.
char* tour_file = NULL
Definition at line 17 of file btsp.c.
int upper_bound = INT_MAX
Definition at line 28 of file btsp.c.
char* usage = "-i tsplib.tsp [options]"
Definition at line 91 of file btsp.c.
char* xml_file = NULL
Definition at line 16 of file btsp.c.