Arrow: bin/hash.c File Reference
bin/hash.c File Reference
Hash testing.
#include <cmph.h>
#include "common.h"
Defines
#define NUM_OPTS 2
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
int supress_hash = ARROW_FALSE
arrow_option options [NUM_OPTS]
char * desc = "Tests the hashing functions."
char * usage = "-i tsplib.tsp"
Detailed Description
Hash testing.
Tests hashing functions.
Author:
John LaRusic
Definition in file hash.c.
Define Documentation
#define NUM_OPTS 2
Definition at line 18 of file hash.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 31 of file hash.c.
References arrow_hash_search(), arrow_options_parse(), arrow_problem_destruct(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, desc, arrow_problem_info::hash, input_file, arrow_hash::num_keys, NUM_OPTS, supress_hash, usage, and arrow_hash::vector.
Variable Documentation
char* desc = "Tests the hashing functions."
Definition at line 26 of file hash.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 14 of file hash.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'H', "supress-hash", "do not create hash table",
        ARROW_OPTION_INT, &supress_hash, ARROW_FALSE, ARROW_FALSE}
}
Definition at line 19 of file hash.c.
char* program_name
Program name
Definition at line 13 of file hash.c.
int supress_hash = ARROW_FALSE
Definition at line 15 of file hash.c.
char* usage = "-i tsplib.tsp"
Definition at line 27 of file hash.c.