Arrow: lib/common/bintree.c File Reference
lib/common/bintree.c File Reference
Binary tree implementation.
#include "common.h"
Functions
int construct_node (arrow_bintree_node **node, int value)
Constructs a new node structure with the given value.
void destruct_node (arrow_bintree_node *node)
Frees the memory of the given node and its child nodes.
int insert_at (arrow_bintree *tree, arrow_bintree_node *node, int value)
Inserts a given value into the tree at the given node, or one of its child nodes.
void fill_array (arrow_bintree_node *node, int *array, int *pos)
Recursive helper function to fill an array in nondecreasing order.
void arrow_bintree_init (arrow_bintree *tree)
Initializes the binary tree data structure.
void arrow_bintree_destruct (arrow_bintree *tree)
Destructs a binary tree data structure.
int arrow_bintree_insert (arrow_bintree *tree, int value)
Inserts a value into the binary tree.
void arrow_bintree_to_array (arrow_bintree *tree, int *array)
Initializes the binary tree data structure into an existing array.
int arrow_bintree_to_new_array (arrow_bintree *tree, int **array)
Initializes the binary tree data structure into a new array.
Detailed Description
Binary tree implementation.
Methods for working with Arrow's binary tree data structure.
Author:
John LaRusic
Definition in file bintree.c.
Function Documentation
void arrow_bintree_destruct (arrow_bintree * tree)
Destructs a binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 60 of file bintree.c.
References destruct_node(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get().
void arrow_bintree_init (arrow_bintree * tree)
Initializes the binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 53 of file bintree.c.
References arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), cbtsp_shake_initialize(), and sbtsp_shake_1_initialize().
int arrow_bintree_insert (arrow_bintree * tree, int value)
Inserts a value into the binary tree.
Parameters:
tree [out] binary tree structure
value [in] value to insert into tree
Definition at line 67 of file bintree.c.
References construct_node(), insert_at(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), cbtsp_shake_initialize(), and sbtsp_shake_1_initialize().
void arrow_bintree_to_array (arrow_bintree * tree, int * array)
Initializes the binary tree data structure into an existing array.
Parameters:
tree [out] binary tree structure
array [out] array to be filled
Definition at line 87 of file bintree.c.
References fill_array(), and arrow_bintree::root_node.
Referenced by arrow_bintree_to_new_array(), cbtsp_shake_initialize(), and sbtsp_shake_1_initialize().
int arrow_bintree_to_new_array (arrow_bintree * tree, int ** array)
Initializes the binary tree data structure into a new array.
Parameters:
tree [out] binary tree structure
array [out] array to be created and filled
Definition at line 94 of file bintree.c.
References arrow_bintree_to_array(), ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_array(), and arrow_bintree::size.
Referenced by arrow_problem_info_get().
int construct_node (arrow_bintree_node ** node, int value)
Constructs a new node structure with the given value.
Parameters:
node [out] pointer to node structure
value [in] value to assign to new node
Definition at line 107 of file bintree.c.
References ARROW_FAILURE, ARROW_FALSE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_bintree_insert(), and insert_at().
void destruct_node (arrow_bintree_node * node)
Frees the memory of the given node and its child nodes.
Parameters:
node [out] node structure
Definition at line 126 of file bintree.c.
References ARROW_TRUE, arrow_bintree_node::has_left_node, arrow_bintree_node::has_right_node, arrow_bintree_node::left_node, and arrow_bintree_node::right_node.
Referenced by arrow_bintree_destruct().
void fill_array (arrow_bintree_node * node, int * array, int * pos)
Recursive helper function to fill an array in nondecreasing order.
Parameters:
node [out] pointer to an node structure
array [out] array to fill
pos [out] current position in array
Definition at line 192 of file bintree.c.
References arrow_bintree_node::data, arrow_bintree_node::has_left_node, arrow_bintree_node::has_right_node, arrow_bintree_node::left_node, and arrow_bintree_node::right_node.
Referenced by arrow_bintree_to_array().
int insert_at (arrow_bintree * tree, arrow_bintree_node * node, int value)
Inserts a given value into the tree at the given node, or one of its child nodes.
Parameters:
tree [in] pointer to tree structure
node [out] pointer to node structure
value [in] value to assign to new node
Definition at line 143 of file bintree.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, construct_node(), arrow_bintree_node::data, arrow_bintree_node::has_left_node, arrow_bintree_node::has_right_node, arrow_bintree_node::left_node, arrow_bintree_node::right_node, and arrow_bintree::size.
Referenced by arrow_bintree_insert().