Arrow: lib/btsp_fun.c File Reference
lib/btsp_fun.c File Reference
Cost matrix transformation functions.
#include "arrow.h"
Data Structures
struct basic_data
Concorde userdat structure for basic cost matrix function.
struct constrained_data
Concorde userdat structure for constrained cost matrix function.
struct constrained_shake_data
Concorde userdat structure for constrained shake cost matrix function.
Functions
int basic_shallow_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies basic BTSP function to the cost matrix of the old problem to create the new problem (shallow copy).
int basic_deep_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies basic BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
void basic_destruct (arrow_btsp_fun *fun)
Destructs a basic BTSP function structure.
int basic_feasible (arrow_btsp_fun *fun, arrow_problem *problem, int delta, double tour_length, int *tour)
Determines if the given tour is feasible or not.
static int basic_edgelen (int i, int j, struct CCdatagroup *dat)
Concorde edge length function for the basic cost matrix function. Returns the cost C[i,j].
int basic_atsp_deep_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies basic ABTSP function to the cost matrix of the old problem to create the new problem (deep copy).
void basic_atsp_destruct (arrow_btsp_fun *fun)
Destructs a basic ABTSP function structure.
int basic_atsp_feasible (arrow_btsp_fun *fun, arrow_problem *problem, int delta, double tour_length, int *tour)
Determines if the given tour is feasible or not for the basic ATSP transformation.
int constrained_shallow_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies constrained BTSP function to the cost matrix of the old problem to create the new problem (shallow copy).
int constrained_deep_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies constrained BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
void constrained_destruct (arrow_btsp_fun *fun)
Destructs constrained BTSP function structure.
static int constrained_edgelen (int i, int j, struct CCdatagroup *dat)
Concorde edge length function for the constrained cost matrix function. Returns the cost C[i,j].
int constrained_shake_deep_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies constrained shake BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
void constrained_shake_destruct (arrow_btsp_fun *fun)
Destructs constrained shake BTSP function structure.
int constrained_shake_feasible (arrow_btsp_fun *fun, arrow_problem *problem, int delta, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int arrow_btsp_fun_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int delta, arrow_problem *new_problem)
Applies the given function to the given problem to create a new problem.
void arrow_btsp_fun_destruct (arrow_btsp_fun *fun)
Destructs a function structure.
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function.
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function for asymmetric problem instances.
int arrow_btsp_fun_constrained (int shallow, double feasible_length, int infinity, arrow_btsp_fun *fun)
Constrained BTSP to TSP function.
int arrow_btsp_fun_constrained_shake (int shallow, double feasible_length, int infinity, int rand_min, int rand_max, arrow_problem *problem, arrow_problem_info *info, arrow_btsp_fun *fun)
Constrained "Shake" BTSP to TSP function.
Detailed Description
Cost matrix transformation functions.
Cost matrix transformation functions for the bottleneck traveling salesman problem (BTSP).
Author:
John LaRusic
Definition in file btsp_fun.c.
Function Documentation
int arrow_btsp_fun_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies the given function to the given problem to create a new problem.
Parameters:
fun [in] function structure
old_problem [in] existing problem
delta [in] delta parameter
new_problem [out] new problem to create
Definition at line 213 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_ERROR_FATAL, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_CCdatagroup_init_matrix(), arrow_problem::data, arrow_problem::get_cost, arrow_problem::name, arrow_btsp_fun::shallow, arrow_problem::shallow, and arrow_problem::size.
Referenced by feasible().
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 249 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, basic_deep_apply(), basic_destruct(), basic_feasible(), basic_shallow_apply(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function for asymmetric problem instances.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 270 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, basic_atsp_deep_apply(), basic_atsp_destruct(), basic_atsp_feasible(), arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_constrained (int shallow, double feasible_length, int infinity, arrow_btsp_fun * fun)
Constrained BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
fun [out] function structure
Definition at line 291 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_ERROR_FATAL, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, basic_feasible(), constrained_deep_apply(), constrained_destruct(), constrained_shallow_apply(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_constrained_shake (int shallow, double feasible_length, int infinity, int rand_min, int rand_max, arrow_problem * problem, arrow_problem_info * info, arrow_btsp_fun * fun)
Constrained "Shake" BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
rand_min [in] minimum random value to generate
rand_max [in] maximum random value to generate
problem [in] the problem the shake is based upon
info [in] information about the original problem
fun [out] function structure
Definition at line 319 of file btsp_fun.c.
References arrow_btsp_fun::apply, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, constrained_shake_deep_apply(), constrained_shake_destruct(), constrained_shake_feasible(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::feasible_length, constrained_shake_data::infinity, constrained_shake_data::info, constrained_shake_data::problem, constrained_shake_data::rand_max, constrained_shake_data::rand_min, and arrow_btsp_fun::shallow.
Referenced by main().
void arrow_btsp_fun_destruct (arrow_btsp_fun * fun)
Destructs a function structure.
Parameters:
fun [out] function structure
Definition at line 243 of file btsp_fun.c.
References arrow_btsp_fun::destruct.
Referenced by arrow_btsp_solve_plan_destruct(), and main().
int basic_atsp_deep_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies basic ABTSP function to the cost matrix of the old problem to create the new problem (deep copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 422 of file btsp_fun.c.
References ARROW_SUCCESS, arrow_problem::data, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_basic_atsp().
void basic_atsp_destruct (arrow_btsp_fun * fun)
Destructs a basic ABTSP function structure.
Parameters:
fun [out] the function structure to destruct
Definition at line 442 of file btsp_fun.c.
Referenced by arrow_btsp_fun_basic_atsp().
int basic_atsp_feasible (arrow_btsp_fun * fun, arrow_problem * problem, int delta, double tour_length, int * tour)
Determines if the given tour is feasible or not for the basic ATSP transformation.
Parameters:
fun [in] function structure
problem [in] the problem to check against
delta [in] delta parameter
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 446 of file btsp_fun.c.
References ARROW_FALSE, ARROW_TRUE, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_basic_atsp().
int basic_deep_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies basic BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 387 of file btsp_fun.c.
References ARROW_SUCCESS, arrow_problem::data, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_basic().
void basic_destruct (arrow_btsp_fun * fun)
Destructs a basic BTSP function structure.
Parameters:
fun [out] the function structure to destruct
Definition at line 403 of file btsp_fun.c.
Referenced by arrow_btsp_fun_basic().
static int basic_edgelen (int i, int j, struct CCdatagroup * dat) [static]
Concorde edge length function for the basic cost matrix function. Returns the cost C[i,j].
Parameters:
i [in] node i
j [in] node j
dat [in] Concorde data structure.
Definition at line 414 of file btsp_fun.c.
References basic_data::dat.
Referenced by basic_shallow_apply().
int basic_feasible (arrow_btsp_fun * fun, arrow_problem * problem, int delta, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
delta [in] delta parameter
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 407 of file btsp_fun.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_btsp_fun_basic(), and arrow_btsp_fun_constrained().
int basic_shallow_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies basic BTSP function to the cost matrix of the old problem to create the new problem (shallow copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 364 of file btsp_fun.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, basic_edgelen(), basic_data::dat, arrow_problem::data, and basic_data::delta.
Referenced by arrow_btsp_fun_basic().
int constrained_deep_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies constrained BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 500 of file btsp_fun.c.
References ARROW_SUCCESS, arrow_problem::data, arrow_btsp_fun::data, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_constrained().
void constrained_destruct (arrow_btsp_fun * fun)
Destructs constrained BTSP function structure.
Parameters:
fun [out] the function structure to destruct
Definition at line 518 of file btsp_fun.c.
References arrow_btsp_fun::data.
Referenced by arrow_btsp_fun_constrained().
static int constrained_edgelen (int i, int j, struct CCdatagroup * dat) [static]
Concorde edge length function for the constrained cost matrix function. Returns the cost C[i,j].
Parameters:
i [in] node i
j [in] node j
dat [in] Concorde data structure.
Definition at line 528 of file btsp_fun.c.
References constrained_data::dat, and constrained_data::infinity.
Referenced by constrained_shallow_apply().
int constrained_shake_deep_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies constrained shake BTSP function to the cost matrix of the old problem to create the new problem (deep copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 536 of file btsp_fun.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_binary_search(), arrow_util_random_between(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem::data, arrow_btsp_fun::data, arrow_problem::get_cost, constrained_shake_data::infinity, constrained_shake_data::info, constrained_shake_data::rand_max, constrained_shake_data::rand_min, arrow_problem::size, and arrow_bintree::size.
Referenced by arrow_btsp_fun_constrained_shake().
void constrained_shake_destruct (arrow_btsp_fun * fun)
Destructs constrained shake BTSP function structure.
Parameters:
fun [out] the function structure to destruct
Definition at line 597 of file btsp_fun.c.
References arrow_btsp_fun::data.
Referenced by arrow_btsp_fun_constrained_shake().
int constrained_shake_feasible (arrow_btsp_fun * fun, arrow_problem * problem, int delta, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
delta [in] delta parameter
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 607 of file btsp_fun.c.
References ARROW_FALSE, ARROW_TRUE, arrow_btsp_fun::data, arrow_btsp_fun::feasible_length, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_constrained_shake().
int constrained_shallow_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int delta, arrow_problem * new_problem)
Applies constrained BTSP function to the cost matrix of the old problem to create the new problem (shallow copy).
Parameters:
fun [in] the cost matrix function
old_problem [in] the problem to apply the function to
delta [in] delta parameter
new_problem [out] the resulting new problem
Definition at line 476 of file btsp_fun.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, constrained_edgelen(), constrained_data::dat, arrow_btsp_fun::data, arrow_problem::data, constrained_data::delta, and constrained_data::infinity.
Referenced by arrow_btsp_fun_constrained().