Arrow: include/btsp.h File Reference
include/btsp.h File Reference
Functions for solving the bottleneck TSP.
#include "tsp.h"
Data Structures
struct arrow_btsp_result
BTSP result.
struct arrow_btsp_fun
BTSP Cost matrix function definition.
struct arrow_btsp_solve_plan
BTSP feasibility solve step plan.
struct arrow_btsp_params
BTSP algorithm parameters.
Defines
#define ARROW_BTSP_SOLVE_PLAN_BASIC 1
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED 2
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED_SHAKE 3
Functions
int arrow_btsp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, arrow_btsp_result *result)
Solves TSP with Concorde's exact solver.
int arrow_btsp_feasible (arrow_problem *problem, int num_steps, arrow_btsp_solve_plan *steps, int min_cost, int max_cost, int *feasible, arrow_btsp_result *result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using min_cost <= costs <= max_cost.
int arrow_btsp_fun_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int min_cost, int max_cost, arrow_problem *new_problem)
Applies the given function to the given problem to create a new problem.
void arrow_btsp_fun_destruct (arrow_btsp_fun *fun)
Destructs a function structure.
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function.
int arrow_btsp_fun_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Controlled Type I Shake.
int arrow_btsp_fun_asym_shift (int shallow, int shift, arrow_btsp_fun *fun)
Shifts all costs by given amount; used to remove negative costs.
int arrow_btsp_fun_cbtsp_basic (int shallow, double feasible_length, int infinity, arrow_btsp_fun *fun)
Constrained BTSP to TSP function.
int arrow_btsp_fun_cbtsp_shake (int shallow, double feasible_length, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Constrained "Shake" BTSP to TSP function.
void arrow_btsp_params_init (arrow_btsp_params *params)
Inititalizes BTSP parameter structure.
int arrow_btsp_result_init (arrow_problem *problem, arrow_btsp_result *result)
Initializes the BTSP result structure.
void arrow_btsp_result_destruct (arrow_btsp_result *result)
Destructs a BTSP result structure.
void arrow_btsp_result_print_xml (arrow_btsp_result *result, FILE *out)
Prints results out in XML format.
void arrow_btsp_result_print_pretty (arrow_btsp_result *result, FILE *out)
Prints results out.
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan *plan)
Inititalizes BTSP solve plan structure.
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan *plan)
Destructs a BTSP solve plan structure.
Detailed Description
Functions for solving the bottleneck TSP.
Functions for solving the bottleneck TSP.
Author:
John LaRusic
Definition in file btsp.h.
Define Documentation
#define ARROW_BTSP_SOLVE_PLAN_BASIC 1
Definition at line 20 of file btsp.h.
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED 2
Definition at line 21 of file btsp.h.
#define ARROW_BTSP_SOLVE_PLAN_CONSTRAINED_SHAKE 3
Definition at line 22 of file btsp.h.
Function Documentation
int arrow_btsp_feasible (arrow_problem * problem, int num_steps, arrow_btsp_solve_plan * steps, int min_cost, int max_cost, int * feasible, arrow_btsp_result * result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using min_cost <= costs <= max_cost.
Parameters:
problem [in] problem to solve
num_steps [in] total number of steps in solve plan
steps [in] solve plan step details
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
feasible [out] true if a feasible tour exists, false otherwise
result [out] resulting BTSP tour found
TODO: Find a better way of doing this upper bound update
Definition at line 16 of file feasible.c.
References arrow_btsp_fun_apply(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_problem_destruct(), ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_tsp_solve(), ARROW_TSP_SOLVER_COUNT, arrow_btsp_solve_plan::attempts, arrow_btsp_fun::feasible, arrow_btsp_result::found_tour, arrow_btsp_solve_plan::fun, arrow_problem::get_cost, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_tsp_result::obj_value, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_tsp_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_tsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_solve_plan::tsp_params, and arrow_btsp_solve_plan::tsp_solver.
Referenced by arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib2(), and arrow_btsp_solve().
int arrow_btsp_fun_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int min_cost, int max_cost, arrow_problem * new_problem)
Applies the given function to the given problem to create a new problem.
Parameters:
fun [in] function structure
old_problem [in] existing problem
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
new_problem [out] new problem to create
Definition at line 93 of file fun.c.
References apply_deep(), apply_shallow(), ARROW_FAILURE, arrow_print_error, arrow_problem::fixed_edges, arrow_btsp_fun::initialize, arrow_problem::name, arrow_btsp_fun::shallow, arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_feasible(), btsp_bounds(), and main().
int arrow_btsp_fun_asym_shift (int shallow, int shift, arrow_btsp_fun * fun)
Shifts all costs by given amount; used to remove negative costs.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
shift [in] value to shift all costs by
fun [out] function structure
Definition at line 191 of file fun_btsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, btsp_asym_shift_destruct(), btsp_asym_shift_feasible(), btsp_asym_shift_get_cost(), btsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 143 of file fun_btsp.c.
References ARROW_SUCCESS, btsp_basic_destruct(), btsp_basic_feasible(), btsp_basic_get_cost(), btsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_cbtsp_basic (int shallow, double feasible_length, int infinity, arrow_btsp_fun * fun)
Constrained BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
fun [out] function structure
Definition at line 132 of file fun_cbtsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, cbtsp_basic_destruct(), cbtsp_basic_feasible(), cbtsp_basic_get_cost(), cbtsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, cbtsp_basic_data::feasible_length, arrow_btsp_fun::get_cost, cbtsp_basic_data::infinity, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_cbtsp_shake (int shallow, double feasible_length, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Constrained "Shake" BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 156 of file fun_cbtsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), cbtsp_shake_destruct(), cbtsp_shake_feasible(), cbtsp_shake_get_cost(), cbtsp_shake_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, cbtsp_shake_data::feasible_length, arrow_btsp_fun::get_cost, cbtsp_shake_data::infinity, cbtsp_shake_data::info, arrow_btsp_fun::initialize, cbtsp_shake_data::random_list, cbtsp_shake_data::random_list_length, cbtsp_shake_data::random_max, cbtsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
void arrow_btsp_fun_destruct (arrow_btsp_fun * fun)
Destructs a function structure.
Parameters:
fun [out] function structure
Definition at line 115 of file fun.c.
References arrow_btsp_fun::destruct.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_solve_plan_destruct(), btsp_bounds(), and main().
int arrow_btsp_fun_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Controlled Type I Shake.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 155 of file fun_btsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), btsp_basic_feasible(), btsp_shake_1_destruct(), btsp_shake_1_get_cost(), btsp_shake_1_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, btsp_shake_1_data::infinity, btsp_shake_1_data::info, arrow_btsp_fun::initialize, btsp_shake_1_data::random_list, btsp_shake_1_data::random_list_length, btsp_shake_1_data::random_max, btsp_shake_1_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
void arrow_btsp_params_init (arrow_btsp_params * params)
Inititalizes BTSP parameter structure.
Parameters:
params [out] BTSP parameters structure
Definition at line 16 of file params.c.
References ARROW_FALSE, arrow_btsp_params::confirm_sol, arrow_btsp_params::find_short_tour, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_params::supress_ebst, and arrow_btsp_params::upper_bound.
Referenced by main().
void arrow_btsp_result_destruct (arrow_btsp_result * result)
Destructs a BTSP result structure.
Parameters:
result [out] BTSP result structure
Definition at line 41 of file result.c.
References arrow_btsp_result::tour.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_btsp_solve(), and main().
int arrow_btsp_result_init (arrow_problem * problem, arrow_btsp_result * result)
Initializes the BTSP result structure.
Parameters:
problem [in] problem to solve
result [out] BTSP result structure
Definition at line 16 of file result.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TSP_SOLVER_COUNT, arrow_util_create_int_array(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, and arrow_btsp_result::tour_length.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_btsp_solve(), and main().
void arrow_btsp_result_print_pretty (arrow_btsp_result * result, FILE * out)
Prints results out.
Parameters:
result [in] result structure
out [out] file to wrtie to
Definition at line 98 of file result.c.
References ARROW_TRUE, arrow_tsp_long_name(), ARROW_TSP_SOLVER_COUNT, arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_btsp_result::optimal, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, and arrow_btsp_result::tour_length.
Referenced by main().
void arrow_btsp_result_print_xml (arrow_btsp_result * result, FILE * out)
Prints results out in XML format.
Parameters:
result [in] result structure
out [out] file to wrtie to
Definition at line 48 of file result.c.
References arrow_tsp_short_name(), ARROW_TSP_SOLVER_COUNT, arrow_xml_attribute_end(), arrow_xml_attribute_int(), arrow_xml_attribute_start(), arrow_xml_element_bool(), arrow_xml_element_close(), arrow_xml_element_double(), arrow_xml_element_end(), arrow_xml_element_int(), arrow_xml_element_open(), arrow_xml_element_start(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_btsp_result::optimal, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, and arrow_btsp_result::tour_length.
Referenced by main().
int arrow_btsp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, arrow_btsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
info [in] extra problem info
params [in] parameters for solver (can be NULL)
result [out] BTSP solution
Definition at line 16 of file btsp.c.
References arrow_btsp_feasible(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_CC_EXACT, ARROW_TSP_SOLVER_COUNT, arrow_util_binary_search(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, arrow_btsp_params::confirm_plan, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::found_tour, arrow_btsp_params::lower_bound, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_btsp_params::num_steps, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_params::steps, arrow_btsp_params::supress_ebst, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, and upper_bound.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), and main().
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan * plan)
Destructs a BTSP solve plan structure.
Parameters:
plan [out] BTSP solve plan structure
Definition at line 22 of file solve_plan.c.
References arrow_btsp_fun_destruct(), ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, arrow_tsp_cc_lk_params_destruct(), arrow_btsp_solve_plan::fun, arrow_btsp_solve_plan::tsp_params, and arrow_btsp_solve_plan::tsp_solver.
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan * plan)
Inititalizes BTSP solve plan structure.
Parameters:
plan [out] BTSP solve plan structure
Definition at line 16 of file solve_plan.c.
References arrow_btsp_solve_plan::attempts.