Arrow: lib/btsp/result.c File Reference
lib/btsp/result.c File Reference
BTSP result structure and methods.
#include "common.h"
#include "btsp.h"
Functions
int arrow_btsp_result_init (arrow_problem *problem, arrow_btsp_result *result)
Initializes the BTSP result structure.
void arrow_btsp_result_destruct (arrow_btsp_result *result)
Destructs a BTSP result structure.
void arrow_btsp_result_print_xml (arrow_btsp_result *result, FILE *out)
Prints results out in XML format.
void arrow_btsp_result_print_pretty (arrow_btsp_result *result, FILE *out)
Prints results out.
Detailed Description
BTSP result structure and methods.
Bottleneck traveling salesman problem results structure.
Author:
John LaRusic
Definition in file result.c.
Function Documentation
void arrow_btsp_result_destruct (arrow_btsp_result * result)
Destructs a BTSP result structure.
Parameters:
result [out] BTSP result structure
Definition at line 40 of file result.c.
References arrow_btsp_result::tour.
Referenced by arrow_btsp_solve(), and main().
int arrow_btsp_result_init (arrow_problem * problem, arrow_btsp_result * result)
Initializes the BTSP result structure.
Parameters:
problem [in] problem to solve
result [out] BTSP result structure
Definition at line 16 of file result.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TSP_SOLVER_COUNT, arrow_util_create_int_array(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::obj_value, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, and arrow_btsp_result::tour_length.
Referenced by arrow_btsp_solve(), and main().
void arrow_btsp_result_print_pretty (arrow_btsp_result * result, FILE * out)
Prints results out.
Parameters:
result [in] result structure
out [out] file to wrtie to
Definition at line 95 of file result.c.
References ARROW_TRUE, arrow_tsp_long_name(), ARROW_TSP_SOLVER_COUNT, arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, and arrow_btsp_result::tour_length.
Referenced by main().
void arrow_btsp_result_print_xml (arrow_btsp_result * result, FILE * out)
Prints results out in XML format.
Parameters:
result [in] result structure
out [out] file to wrtie to
Definition at line 47 of file result.c.
References arrow_tsp_short_name(), ARROW_TSP_SOLVER_COUNT, arrow_xml_attribute_end(), arrow_xml_attribute_int(), arrow_xml_attribute_start(), arrow_xml_element_bool(), arrow_xml_element_close(), arrow_xml_element_double(), arrow_xml_element_end(), arrow_xml_element_int(), arrow_xml_element_open(), arrow_xml_element_start(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::found_tour, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_result::total_time, and arrow_btsp_result::tour_length.
Referenced by main().