Arrow: bin/cbtsp.c File Reference
bin/cbtsp.c File Reference
Constrained Bottleneck TSP heuristic.
#include "arrow.h"
Defines
#define NUM_OPTS 17
#define SOLVE_STEPS 2
Functions
int main (int argc, char *argv[])
Variables
char * input_file = NULL
char * xml_file = NULL
char * tour_file = NULL
double length = DBL_MAX
int random_restarts = 5
int stall_count = -1
int kicks = -1
int confirm_sol = ARROW_FALSE
int supress_ebst = ARROW_FALSE
int find_short_tour = ARROW_FALSE
int lower_bound = -1
int upper_bound = INT_MAX
int basic_attempts = 3
int shake_attempts = 2
int shake_rand_min = 0
int shake_rand_max = -1
int random_seed = 0
arrow_option options [NUM_OPTS]
char * desc = "Bottleneck traveling salesman problem (BTSP) solver"
char * usage = "-i tsplib.tsp -L max_length [options]"
Detailed Description
Constrained Bottleneck TSP heuristic.
Runs the Constrained Bottleneck TSP heuristic on the given input file.
Author:
John LaRusic
Definition in file cbtsp.c.
Define Documentation
#define NUM_OPTS 17
Definition at line 32 of file cbtsp.c.
#define SOLVE_STEPS 2
Function Documentation
int main (int argc, char * argv[])
Definition at line 81 of file cbtsp.c.
References arrow_bbssp_solve(), arrow_btsp_fun_constrained(), arrow_btsp_fun_constrained_shake(), arrow_btsp_params_destruct(), arrow_btsp_params_init(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), ARROW_BTSP_SOLVE_PLAN_CONSTRAINED, ARROW_BTSP_SOLVE_PLAN_CONSTRAINED_SHAKE, ARROW_FAILURE, ARROW_FALSE, arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_TRUE, arrow_tsp_lk_params_destruct(), arrow_tsp_lk_params_init(), arrow_util_print_program_args(), arrow_util_random_seed(), arrow_util_write_tour(), arrow_util_zeit(), basic_attempts, arrow_btsp_result::bin_search_steps, confirm_sol, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list_length, desc, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, find_short_tour, arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_problem::get_cost, input_file, arrow_tsp_lk_params::kicks, kicks, length, arrow_tsp_lk_params::length_bound, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_params::lower_bound, lower_bound, NUM_OPTS, arrow_btsp_params::num_steps, arrow_btsp_result::obj_value, arrow_bound_result::obj_value, arrow_btsp_result::optimal, arrow_tsp_lk_params::random_restarts, random_restarts, random_seed, shake_attempts, shake_rand_max, shake_rand_min, arrow_problem::size, SOLVE_STEPS, arrow_tsp_lk_params::stall_count, stall_count, arrow_btsp_params::steps, supress_ebst, arrow_btsp_params::supress_ebst, arrow_btsp_result::total_time, arrow_bound_result::total_time, arrow_btsp_result::tour, tour_file, arrow_btsp_result::tour_length, upper_bound, arrow_btsp_params::upper_bound, usage, and xml_file.
Variable Documentation
int basic_attempts = 3
Definition at line 24 of file cbtsp.c.
int confirm_sol = ARROW_FALSE
Definition at line 19 of file cbtsp.c.
char* desc = "Bottleneck traveling salesman problem (BTSP) solver"
Definition at line 76 of file cbtsp.c.
int find_short_tour = ARROW_FALSE
Definition at line 21 of file cbtsp.c.
char* input_file = NULL
Definition at line 12 of file cbtsp.c.
int kicks = -1
Definition at line 18 of file cbtsp.c.
double length = DBL_MAX
Definition at line 15 of file cbtsp.c.
Referenced by main().
int lower_bound = -1
Definition at line 22 of file cbtsp.c.
arrow_option options[NUM_OPTS]
Definition at line 33 of file cbtsp.c.
int random_restarts = 5
Definition at line 16 of file cbtsp.c.
int random_seed = 0
Definition at line 28 of file cbtsp.c.
Referenced by main().
int shake_attempts = 2
Definition at line 25 of file cbtsp.c.
Referenced by main().
int shake_rand_max = -1
Definition at line 27 of file cbtsp.c.
Referenced by main().
int shake_rand_min = 0
Definition at line 26 of file cbtsp.c.
Referenced by main().
int stall_count = -1
Definition at line 17 of file cbtsp.c.
int supress_ebst = ARROW_FALSE
Definition at line 20 of file cbtsp.c.
char* tour_file = NULL
Definition at line 14 of file cbtsp.c.
int upper_bound = INT_MAX
Definition at line 23 of file cbtsp.c.
char* usage = "-i tsplib.tsp -L max_length [options]"
Definition at line 77 of file cbtsp.c.
char* xml_file = NULL
Definition at line 13 of file cbtsp.c.