Arrow: lib/tsp/cc.c File Reference
lib/tsp/cc.c File Reference
TSP solver and Lin-Kernighan heuristic.
#include "common.h"
#include "tsp.h"
Functions
int build_initial_tour (int ncount, CCdatagroup *dat, CCedgegengroup *plan, CCrandstate *rstate, int *initial_tour)
static int arrow_edgelen (int i, int j, struct CCdatagroup *dat)
Concorde edge length function for Arrow problem strutures.
static int arrow_copy (int ncount, struct CCdatagroup *in, struct CCdatagroup *out)
Creates a copy of the user data.
void arrow_tsp_cc_lk_params_init (arrow_problem *problem, arrow_tsp_cc_lk_params *params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
void arrow_tsp_cc_lk_params_destruct (arrow_tsp_cc_lk_params *params)
Destructs a LK parameters structure.
int arrow_tsp_cc_exact_solve (arrow_problem *problem, int *initial_tour, arrow_tsp_result *result)
Solves TSP with Concorde's exact solver.
int arrow_tsp_cc_lk_solve (arrow_problem *problem, arrow_tsp_cc_lk_params *params, arrow_tsp_result *result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Detailed Description
TSP solver and Lin-Kernighan heuristic.
Wrapper for calling Concorde's TSP solver and Lin-Kernighan heuristic.
Author:
John LaRusic
Definition in file cc.c.
Function Documentation
static int arrow_copy (int ncount, struct CCdatagroup * in, struct CCdatagroup * out) [static]
Creates a copy of the user data.
Parameters:
ncount [in] number of nodes
in [in] source data group
out [out] destination data group
Definition at line 361 of file cc.c.
Referenced by arrow_tsp_cc_exact_solve(), and arrow_tsp_cc_lk_solve().
static int arrow_edgelen (int i, int j, struct CCdatagroup * dat) [static]
Concorde edge length function for Arrow problem strutures.
Parameters:
i [in] node i
j [in] node j
dat [in] Concorde data structure.
Definition at line 354 of file cc.c.
References arrow_problem::get_cost.
Referenced by arrow_tsp_cc_exact_solve(), and arrow_tsp_cc_lk_solve().
int arrow_tsp_cc_exact_solve (arrow_problem * problem, int * initial_tour, arrow_tsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
initial_tour [in] an initial tour (can be NULL)
result [out] TSP solution
Definition at line 62 of file cc.c.
References arrow_copy(), arrow_debug, arrow_edgelen(), ARROW_FAILURE, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::data, arrow_tsp_result::found_tour, arrow_problem::name, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, arrow_tsp_result::tour, and arrow_problem::type.
Referenced by arrow_tsp_solve(), and main().
void arrow_tsp_cc_lk_params_destruct (arrow_tsp_cc_lk_params * params)
Destructs a LK parameters structure.
Parameters:
params [out] LK parameters structure
Definition at line 55 of file cc.c.
References arrow_tsp_cc_lk_params::initial_tour.
Referenced by arrow_btsp_solve_plan_destruct(), arrow_tsp_cc_lk_solve(), and main().
void arrow_tsp_cc_lk_params_init (arrow_problem * problem, arrow_tsp_cc_lk_params * params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
Parameters:
problem [in] problem to solve
params [out] LK parameters structure
Definition at line 42 of file cc.c.
References arrow_tsp_cc_lk_params::initial_tour, arrow_tsp_cc_lk_params::kick_type, arrow_tsp_cc_lk_params::kicks, arrow_tsp_cc_lk_params::length_bound, arrow_tsp_cc_lk_params::random_restarts, arrow_problem::size, arrow_tsp_cc_lk_params::stall_count, and arrow_tsp_cc_lk_params::time_bound.
Referenced by arrow_tsp_cc_lk_solve(), and main().
int arrow_tsp_cc_lk_solve (arrow_problem * problem, arrow_tsp_cc_lk_params * params, arrow_tsp_result * result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Parameters:
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 118 of file cc.c.
References arrow_copy(), arrow_debug, arrow_edgelen(), ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_cc_lk_params_destruct(), arrow_tsp_cc_lk_params_init(), arrow_util_zeit(), build_initial_tour(), CONCORDE_FAILURE, arrow_problem::data, arrow_tsp_result::found_tour, arrow_tsp_cc_lk_params::initial_tour, arrow_tsp_cc_lk_params::kick_type, arrow_tsp_cc_lk_params::kicks, arrow_tsp_cc_lk_params::length_bound, arrow_tsp_result::obj_value, arrow_tsp_cc_lk_params::random_restarts, arrow_problem::size, arrow_tsp_cc_lk_params::stall_count, arrow_tsp_cc_lk_params::time_bound, arrow_tsp_result::total_time, arrow_tsp_result::tour, and arrow_problem::type.
Referenced by arrow_tsp_solve().
int build_initial_tour (int ncount, CCdatagroup * dat, CCedgegengroup * plan, CCrandstate * rstate, int * initial_tour)
Definition at line 312 of file cc.c.
References ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, and CONCORDE_FAILURE.
Referenced by arrow_tsp_cc_lk_solve().