Arrow: include/common.h File Reference
include/common.h File Reference
Common functions and data structures.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include <float.h>
#include <regex.h>
#include <getopt.h>
#include "concorde.h"
#include <cmph.h>
Data Structures
struct arrow_bintree
Binary tree data structure.
struct arrow_bintree_node
Binary tree node.
struct arrow_hash
Hashtable.
struct arrow_heap
Binary heap.
struct arrow_llist_item
Linked list item.
struct arrow_llist
Linked list data structure.
struct arrow_option
Program options structure.
struct arrow_problem
Problem data structure.
struct arrow_problem_info
Problem information data structure.
Defines
#define ARROW_DEBUG
#define arrow_debug printf
#define arrow_print_error(args...)
#define ARROW_VERSION "1.0"
#define ARROW_DEV_NULL "/dev/null"
#define ARROW_SUCCESS 1
#define ARROW_FAILURE 0
#define ARROW_TRUE 1
#define ARROW_FALSE 0
#define ARROW_PROBLEM_NAME_LENGTH 64
#define ARROW_HASH_BUFFER_LENGTH 16
#define ARROW_PROBLEM_DATA_FULL_MATRIX 1
#define ARROW_PROBLEM_DATA_CONCORDE 2
#define ARROW_PROBLEM_DATA_BTSP_FUN 3
#define ARROW_PROBLEM_ABTSP_TO_SBTSP 4
#define ARROW_PROBLEM_MSTSP_TO_BTSP 5
#define ARROW_OPTION_INT 1
#define ARROW_OPTION_DOUBLE 2
#define ARROW_OPTION_STRING 3
#define CONCORDE_SUCCESS 0
#define CONCORDE_FAILURE 1
Functions
void arrow_bintree_init (arrow_bintree *tree)
Initializes the binary tree data structure.
void arrow_bintree_destruct (arrow_bintree *tree)
Destructs a binary tree data structure.
int arrow_bintree_insert (arrow_bintree *tree, int value)
Inserts a value into the binary tree.
void arrow_bintree_to_array (arrow_bintree *tree, int *array)
Initializes the binary tree data structure into an existing array.
int arrow_bintree_to_new_array (arrow_bintree *tree, int **array)
Initializes the binary tree data structure into a new array.
void arrow_bintree_print (arrow_bintree *tree)
Prints out the values of the binary tree.
int arrow_hash_cost_list (int *cost_list, int cost_list_length, arrow_hash *hash)
Creates a hash table from a list of unique costs.
void arrow_hash_destruct (arrow_hash *hash)
Destructs a hashtable data structure.
unsigned int arrow_hash_search (arrow_hash *hash, int key)
Finds id associated with key in hashtable.
int arrow_heap_init (arrow_heap *heap, int max_size)
Initializes a new binary heap.
void arrow_heap_destruct (arrow_heap *heap)
Destructs a binary heap.
void arrow_heap_empty (arrow_heap *heap)
Empties the heap of items.
int arrow_heap_insert (arrow_heap *heap, int key, int value)
Inserts a new (key,value) pair into the heap.
int arrow_heap_in (arrow_heap *heap, int value)
Determines if the given value is present in the heap.
void arrow_heap_change_key (arrow_heap *heap, int key, int value)
Changes the key for the given value in the heap.
int arrow_heap_get_min (arrow_heap *heap)
Returns the value with the smallest key in the heap.
void arrow_heap_delete_min (arrow_heap *heap)
Removes the value with the smallest key from the heap.
void arrow_heap_print (arrow_heap *heap)
Prints heap structure.
void arrow_llist_init (arrow_llist *list)
Initializes a new linked list.
void arrow_llist_destruct (arrow_llist *list)
Destructs contents of a linked list.
void arrow_llist_swap (arrow_llist *a, arrow_llist *b)
Swaps the two given lists.
int arrow_llist_insert_head (arrow_llist *list, int value)
Inserts a new item at the head of the list.
int arrow_llist_insert_tail (arrow_llist *list, int value)
Inserts a new item at the tail of the list.
int arrow_llist_insert_after (arrow_llist *list, arrow_llist_item *item, int value)
Inserts a new item after the given item in the list. NOTE: procedure makes no attempt to verify given item is in the list!
void arrow_llist_remove_head (arrow_llist *list, int *value)
Removes the head item in the list.
void arrow_llist_remove_tail (arrow_llist *list, int *value)
Removes the tail item in the list. NOTE: O(n) procedure!
void arrow_llist_remove_after (arrow_llist *list, arrow_llist_item *item, int *value)
Removes the item after the given one in the list. NOTE: procedure makes no attempt to verify given item is in the list!
void arrow_llist_print (arrow_llist *list)
Prints a list of items in the list.
void arrow_llist_to_array (arrow_llist *list, int *array)
Copys data from linked list into array. Assume array is big enough to handle linked list!
int arrow_options_parse (int num_opts, arrow_option options[], char *description, char *usage, int argc, char *argv[], int *opt_ind)
Parses program options.
int arrow_problem_read (char *file_name, arrow_problem *problem)
Reads a problem from a TSPLIB file.
void arrow_problem_destruct (arrow_problem *problem)
Deallocates problem data structure.
int arrow_problem_info_get (arrow_problem *problem, int create_hash, arrow_problem_info *info)
Builds ordered cost list and finds min/max cost in a problem.
void arrow_problem_info_destruct (arrow_problem_info *info)
Deallocates problem info data structure.
int arrow_problem_info_cost_index (arrow_problem_info *info, int cost, int *pos)
Finds the position of the given cost into the sorted list.
int arrow_problem_max_cost (arrow_problem *problem)
Finds the largest cost in a problem (cheaper than calling arrow_problem_info_get).
void arrow_problem_print (arrow_problem *problem, int pretty)
Prints out information about a problem.
int arrow_problem_read_tour (char *file_name, int size, int *tour)
Reads a TSPLIB tour file.
int arrow_problem_abtsp_to_sbtsp (int shallow, arrow_problem *old_problem, int infinity, arrow_problem *new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
int arrow_problem_mstsp_to_btsp (int shallow, arrow_problem *old_problem, int max_cost, arrow_problem *new_problem)
Transforms a MSTSP problem into the equivalent BTSP problem.
int arrow_util_create_int_array (int size, int **array)
Creates an integer array.
int arrow_util_create_int_matrix (int rows, int cols, int ***matrix, int **space)
Creates a full integer matrix.
void arrow_util_print_error (const char *file_name, int line_num, const char *message)
Prints an error message to stderr with consistent formatting.
double arrow_util_zeit ()
Used to measure timings.
void arrow_util_redirect_stdout_to_file (const char *filename, int *old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup *from, CCdatagroup *to)
Makes a shallow copy of the Concorde CCdatagroup structure.
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup *dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
int arrow_util_binary_search (int *array, int size, int element, int *pos)
Performs a binary search to find the wanted element in a sorted integer array.
int arrow_util_regex_match (char *string, char *pattern)
Determines if the given string turns up a match for the given regular expression pattern.
void arrow_util_print_program_args (int argc, char *argv[], FILE *out)
Prints out the given program arguments to the specified file.
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
int arrow_util_random ()
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
int arrow_util_random_between (int min, int max)
Returns a random number between min and max.
void arrow_util_permute_array (int size, int *array)
Randomly permutes the elements of the given array.
void arrow_util_write_tour (arrow_problem *problem, char *comment, int *tour, FILE *out)
Writes a tour in TSPLIB format.
void arrow_util_sbtsp_to_abstp_tour (arrow_problem *problem, int *old_tour, int *new_tour)
Converts a symmetric tour to an asymmetric tour.
void arrow_util_write_problem (arrow_problem *problem, char *comment, FILE *out)
Writes a problem in TSPLIB format as a lower diagonal matrix.
void arrow_xml_element_int (char *name, int value, FILE *out)
Writes an XML tag out for an integer value.
void arrow_xml_element_double (char *name, double value, FILE *out)
Writes an XML tag out for a double value.
void arrow_xml_element_string (char *name, char *value, FILE *out)
Writes an XML tag out for a string value.
void arrow_xml_element_bool (char *name, int value, FILE *out)
Writes an XML tag out for a boolean value.
void arrow_xml_attribute_int (char *name, int value, FILE *out)
void arrow_xml_attribute_string (char *name, char *value, FILE *out)
void arrow_xml_element_start (char *name, FILE *out)
void arrow_xml_element_end (FILE *out)
void arrow_xml_element_open (char *name, FILE *out)
void arrow_xml_element_close (char *name, FILE *out)
void arrow_xml_attribute_start (char *name, FILE *out)
void arrow_xml_attribute_end (FILE *out)
Detailed Description
Common functions and data structures.
Common functions and data structures exposed by the callable library.
Author:
John LaRusic
Definition in file common.h.
Define Documentation
#define arrow_debug printf
Definition at line 38 of file common.h.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_feasible(), arrow_btsp_solve(), arrow_cbap_solve(), arrow_cbst_solve(), arrow_tsp_cc_exact_solve(), arrow_tsp_cc_lk_solve(), arrow_tsp_rai_solve(), btsp_basic_feasible(), btsp_bounds(), btsp_lower_bound(), improve_tour(), read_atsp(), and read_stsp().
#define ARROW_DEBUG
Definition at line 36 of file common.h.
#define ARROW_DEV_NULL "/dev/null"
Definition at line 56 of file common.h.
Referenced by main().
#define ARROW_FAILURE 0
Definition at line 58 of file common.h.
Referenced by apply_deep(), apply_shallow(), arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_shake(), arrow_bap_has_assignment(), arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bbssp_solve(), arrow_bintree_to_new_array(), arrow_bscssp_connected(), arrow_bscssp_solve(), arrow_btsp_feasible(), arrow_btsp_fun_apply(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_cbap_lap(), arrow_cbap_solve(), arrow_cbst_mst_solve(), arrow_cbst_solve(), arrow_dcbpb_solve(), arrow_heap_init(), arrow_heap_insert(), arrow_llist_insert_after(), arrow_llist_insert_head(), arrow_llist_insert_tail(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_cost_index(), arrow_problem_mstsp_to_btsp(), arrow_problem_read(), arrow_problem_read_tour(), arrow_tsp_cc_exact_solve(), arrow_tsp_cc_lk_solve(), arrow_tsp_rai_solve(), arrow_tsp_result_init(), arrow_tsp_solve(), arrow_util_binary_search(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), balanced_lb_feasible(), baltsp_bounds_tree(), baltsp_dt2_initialize(), btsp_bounds(), btsp_lower_bound(), build_initial_tour(), construct_item(), construct_node(), dt2_lb_feasible(), find_cost_order(), init_data(), init_tiers(), insert_at(), main(), read_atsp(), and read_stsp().
#define ARROW_FALSE 0
Definition at line 60 of file common.h.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_baltsp_params_init(), arrow_bap_has_assignment(), arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bscssp_connected(), arrow_btsp_feasible(), arrow_btsp_params_init(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_heap_in(), arrow_options_parse(), arrow_tsp_result_init(), arrow_util_regex_match(), balanced_lb_feasible(), baltsp_basic_feasible(), baltsp_dt2_feasible(), baltsp_ib_feasible(), baltsp_ut_feasible(), btsp_basic_feasible(), build_initial_tour(), cbtsp_basic_feasible(), cbtsp_shake_feasible(), construct_node(), dt2_lb_feasible(), ford_fulkerson_labeling(), insert_at(), is_leaf(), main(), read_atsp(), read_stsp(), and shortest_augmenting_path().
#define ARROW_HASH_BUFFER_LENGTH 16
Definition at line 62 of file common.h.
Referenced by arrow_hash_cost_list(), and arrow_hash_search().
#define ARROW_OPTION_DOUBLE 2
Definition at line 71 of file common.h.
Referenced by arrow_options_parse().
#define ARROW_OPTION_INT 1
Definition at line 70 of file common.h.
Referenced by arrow_options_parse().
#define ARROW_OPTION_STRING 3
Definition at line 72 of file common.h.
Referenced by arrow_options_parse().
#define arrow_print_error (args...)
Value:
fprintf(stderr, "%s:%d: ", __FILE__, __LINE__); fprintf(stderr, args); \
    fprintf(stderr, "\n")
Definition at line 47 of file common.h.
Referenced by apply_deep(), apply_shallow(), arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_shake(), arrow_btsp_fun_apply(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), arrow_cbap_solve(), arrow_cbst_mst_solve(), arrow_cbst_solve(), arrow_heap_insert(), arrow_llist_insert_after(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_cost_index(), arrow_problem_mstsp_to_btsp(), arrow_problem_read(), arrow_tsp_cc_lk_solve(), arrow_tsp_long_name(), arrow_tsp_rai_solve(), arrow_tsp_short_name(), arrow_tsp_solve(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), balanced_lb_feasible(), baltsp_bounds_tree(), baltsp_dt2_get_cost(), baltsp_dt2_initialize(), baltsp_shake_get_cost(), btsp_bounds(), btsp_shake_1_get_cost(), build_initial_tour(), cbtsp_shake_get_cost(), construct_item(), construct_node(), dijkstra(), dt2_lb_feasible(), fill_tiers(), find_cost_order(), init_tiers(), main(), read_args(), read_atsp(), and read_stsp().
#define ARROW_PROBLEM_ABTSP_TO_SBTSP 4
Definition at line 67 of file common.h.
Referenced by arrow_problem_abtsp_to_sbtsp().
#define ARROW_PROBLEM_DATA_BTSP_FUN 3
Definition at line 66 of file common.h.
Referenced by apply_shallow().
#define ARROW_PROBLEM_DATA_CONCORDE 2
Definition at line 65 of file common.h.
Referenced by apply_deep(), arrow_tsp_cc_exact_solve(), arrow_tsp_cc_lk_solve(), and read_stsp().
#define ARROW_PROBLEM_DATA_FULL_MATRIX 1
Definition at line 64 of file common.h.
Referenced by read_atsp().
#define ARROW_PROBLEM_MSTSP_TO_BTSP 5
Definition at line 68 of file common.h.
Referenced by arrow_problem_mstsp_to_btsp().
#define ARROW_PROBLEM_NAME_LENGTH 64
Definition at line 61 of file common.h.
#define ARROW_SUCCESS 1
Definition at line 57 of file common.h.
Referenced by apply_deep(), apply_shallow(), arrow_2mb_solve(), arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_bap_has_assignment(), arrow_bap_solve(), arrow_bbssp_solve(), arrow_bintree_to_new_array(), arrow_bscssp_connected(), arrow_bscssp_solve(), arrow_btsp_feasible(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_cbap_lap(), arrow_cbap_solve(), arrow_cbst_mst_solve(), arrow_cbst_solve(), arrow_dcbpb_solve(), arrow_hash_cost_list(), arrow_heap_init(), arrow_heap_insert(), arrow_llist_insert_after(), arrow_llist_insert_head(), arrow_llist_insert_tail(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_cost_index(), arrow_problem_info_get(), arrow_problem_mstsp_to_btsp(), arrow_problem_read_tour(), arrow_tsp_cc_exact_solve(), arrow_tsp_cc_lk_solve(), arrow_tsp_rai_solve(), arrow_tsp_result_init(), arrow_util_binary_search(), arrow_util_CCdatagroup_init_matrix(), arrow_util_create_int_array(), arrow_util_create_int_matrix(), balanced_lb_feasible(), baltsp_basic_initialize(), baltsp_bounds_tree(), baltsp_dt2_initialize(), baltsp_shake_initialize(), btsp_basic_initialize(), btsp_bounds(), btsp_lower_bound(), btsp_shake_1_initialize(), build_initial_tour(), cbtsp_basic_initialize(), cbtsp_shake_initialize(), construct_item(), construct_node(), dt2_lb_feasible(), fill_tiers(), find_art_points(), find_cost_order(), init_data(), init_tiers(), insert_at(), main(), read_atsp(), and read_stsp().
#define ARROW_TRUE 1
Definition at line 59 of file common.h.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_bap_has_assignment(), arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bbssp_solve(), arrow_bscssp_connected(), arrow_bscssp_solve(), arrow_btsp_feasible(), arrow_btsp_result_print_pretty(), arrow_btsp_solve(), arrow_heap_in(), arrow_options_parse(), arrow_problem_abtsp_to_sbtsp(), arrow_problem_info_get(), arrow_problem_max_cost(), arrow_tsp_cc_lk_solve(), arrow_tsp_rai_solve(), arrow_util_regex_match(), baltsp_basic_feasible(), baltsp_dt2_feasible(), baltsp_ib_feasible(), baltsp_ut_feasible(), btsp_basic_feasible(), btsp_bounds(), cbtsp_basic_feasible(), cbtsp_shake_feasible(), destruct_node(), ford_fulkerson_labeling(), insert_at(), is_leaf(), main(), read_stsp(), shortest_augmenting_path(), and strongly_connected_dfs().
#define ARROW_VERSION "1.0"
Definition at line 55 of file common.h.
Referenced by print_version().
#define CONCORDE_FAILURE 1
Definition at line 75 of file common.h.
Referenced by arrow_tsp_cc_lk_solve(), and build_initial_tour().
#define CONCORDE_SUCCESS 0
Definition at line 74 of file common.h.
Referenced by arrow_problem_read_tour().
Function Documentation
void arrow_bintree_destruct (arrow_bintree * tree)
Destructs a binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 60 of file bintree.c.
References destruct_node(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), baltsp_bounds_tree(), baltsp_shake_initialize(), btsp_shake_1_initialize(), and find_cost_order().
void arrow_bintree_init (arrow_bintree * tree)
Initializes the binary tree data structure.
Parameters:
tree [out] binary tree structure
Definition at line 53 of file bintree.c.
References arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), baltsp_bounds_tree(), baltsp_shake_initialize(), btsp_shake_1_initialize(), and cbtsp_shake_initialize().
int arrow_bintree_insert (arrow_bintree * tree, int value)
Inserts a value into the binary tree.
Parameters:
tree [out] binary tree structure
value [in] value to insert into tree
Definition at line 70 of file bintree.c.
References construct_node(), insert_at(), arrow_bintree::root_node, and arrow_bintree::size.
Referenced by arrow_problem_info_get(), baltsp_bounds_tree(), baltsp_shake_initialize(), btsp_shake_1_initialize(), and cbtsp_shake_initialize().
void arrow_bintree_print (arrow_bintree * tree)
Prints out the values of the binary tree.
Parameters:
tree [in] binary tree structure
void arrow_bintree_to_array (arrow_bintree * tree, int * array)
Initializes the binary tree data structure into an existing array.
Parameters:
tree [out] binary tree structure
array [out] array to be filled
Definition at line 90 of file bintree.c.
References fill_array(), and arrow_bintree::root_node.
Referenced by arrow_bintree_to_new_array(), baltsp_shake_initialize(), btsp_shake_1_initialize(), cbtsp_shake_initialize(), and find_cost_order().
int arrow_bintree_to_new_array (arrow_bintree * tree, int ** array)
Initializes the binary tree data structure into a new array.
Parameters:
tree [out] binary tree structure
array [out] array to be created and filled
Definition at line 97 of file bintree.c.
References arrow_bintree_to_array(), ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_array(), and arrow_bintree::size.
Referenced by arrow_problem_info_get().
int arrow_hash_cost_list (int * cost_list, int cost_list_length, arrow_hash * hash)
Creates a hash table from a list of unique costs.
Parameters:
cost_list [in] list of costs
cost_list_length [in] length of cost list
hash [out] hashtable data structure
Definition at line 12 of file hash.c.
References ARROW_HASH_BUFFER_LENGTH, ARROW_SUCCESS, arrow_hash::data, arrow_hash::num_keys, arrow_hash::source, arrow_hash::vector, and arrow_hash::vector_space.
Referenced by arrow_problem_info_get(), and fill_tiers().
void arrow_hash_destruct (arrow_hash * hash)
Destructs a hashtable data structure.
Parameters:
hash [out] hashtable data structure
Definition at line 40 of file hash.c.
References arrow_hash::data, arrow_hash::num_keys, arrow_hash::source, arrow_hash::vector, and arrow_hash::vector_space.
Referenced by arrow_problem_info_destruct(), and fill_tiers().
unsigned int arrow_hash_search (arrow_hash * hash, int key)
Finds id associated with key in hashtable.
Parameters:
hash [in] hash table data structure
key [in] key to look up
Returns:
the id of the associated key
Definition at line 50 of file hash.c.
References ARROW_HASH_BUFFER_LENGTH, and arrow_hash::data.
Referenced by arrow_problem_info_cost_index(), fill_tiers(), and main().
void arrow_heap_change_key (arrow_heap * heap, int key, int value)
Changes the key for the given value in the heap.
Parameters:
heap [out] heap structure
key [in] the new key
value [in] node value to change
Definition at line 177 of file heap.c.
References arrow_heap::keys, arrow_heap::pos, siftdown(), and siftup().
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_delete_min (arrow_heap * heap)
Removes the value with the smallest key from the heap.
heap [out] heap structure
Definition at line 196 of file heap.c.
References arrow_heap::pos, siftdown(), arrow_heap::size, swap_nodes(), and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_destruct (arrow_heap * heap)
Destructs a binary heap.
Parameters:
heap [out] heap structure
Definition at line 117 of file heap.c.
References arrow_heap::keys, arrow_heap::pos, and arrow_heap::values.
Referenced by arrow_heap_init(), destroy_data(), and destruct_data().
void arrow_heap_empty (arrow_heap * heap)
Empties the heap of items.
Parameters:
heap [out] heap structure
Definition at line 128 of file heap.c.
References arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
int arrow_heap_get_min (arrow_heap * heap) [inline]
Returns the value with the smallest key in the heap.
heap [in] heap structure
Returns:
The value with the smallest key in the heap.
Definition at line 190 of file heap.c.
References arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
int arrow_heap_in (arrow_heap * heap, int value)
Determines if the given value is present in the heap.
Parameters:
heap [in] heap structure
value [in] value to check
Returns:
True or false, if the value is present in the heap
Definition at line 171 of file heap.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_heap::pos.
Referenced by dijkstra().
int arrow_heap_init (arrow_heap * heap, int max_size)
Initializes a new binary heap.
Parameters:
heap [out] heap structure
max_size [in] maximum size of heap
Definition at line 89 of file heap.c.
References ARROW_FAILURE, arrow_heap_destruct(), ARROW_SUCCESS, arrow_util_create_int_array(), arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
Referenced by init_data().
int arrow_heap_insert (arrow_heap * heap, int key, int value)
Inserts a new (key,value) pair into the heap.
Parameters:
heap [out] heap structure
key [in] key to insert
value [in] value to insert -- must be between 0 and [n-1] and not a duplicate value.
Definition at line 141 of file heap.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, siftup(), arrow_heap::size, and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_print (arrow_heap * heap)
Prints heap structure.
heap [in] heap structure
Definition at line 206 of file heap.c.
References arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
void arrow_llist_destruct (arrow_llist * list)
Destructs contents of a linked list.
Parameters:
list [out] list structure
Definition at line 31 of file llist.c.
References arrow_llist_remove_head(), and arrow_llist::size.
Referenced by arrow_tsp_rai_solve(), destruct_tiers(), and improve_tour().
void arrow_llist_init (arrow_llist * list)
Initializes a new linked list.
Parameters:
list [out] linked list structure
Definition at line 23 of file llist.c.
References arrow_llist::head, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_tsp_rai_solve(), and init_tiers().
int arrow_llist_insert_after (arrow_llist * list, arrow_llist_item * item, int value)
Inserts a new item after the given item in the list. NOTE: procedure makes no attempt to verify given item is in the list!
Parameters:
list [out] linked list structure
item [in] linked list item
value [in] value to insert
Definition at line 101 of file llist.c.
References ARROW_FAILURE, arrow_llist_insert_tail(), arrow_print_error, ARROW_SUCCESS, construct_item(), arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by construct_tour().
int arrow_llist_insert_head (arrow_llist * list, int value)
Inserts a new item at the head of the list.
Parameters:
list [out] linked list structure
value [in] value to insert
Definition at line 55 of file llist.c.
References ARROW_FAILURE, ARROW_SUCCESS, construct_item(), arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
int arrow_llist_insert_tail (arrow_llist * list, int value)
Inserts a new item at the tail of the list.
Parameters:
list [out] linked list structure
value [in] value to insert
Definition at line 78 of file llist.c.
References ARROW_FAILURE, ARROW_SUCCESS, construct_item(), arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_llist_insert_after(), arrow_tsp_rai_solve(), construct_tour(), fill_tiers(), and improve_tour().
void arrow_llist_print (arrow_llist * list)
Prints a list of items in the list.
Parameters:
list [in] linked list structure
Definition at line 201 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, and arrow_llist::size.
void arrow_llist_remove_after (arrow_llist * list, arrow_llist_item * item, int * value)
Removes the item after the given one in the list. NOTE: procedure makes no attempt to verify given item is in the list!
Parameters:
list [out] linked list structure
item [in] linked list item
value [out] value of removed item
Definition at line 179 of file llist.c.
References arrow_llist_remove_head(), arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
void arrow_llist_remove_head (arrow_llist * list, int * value)
Removes the head item in the list.
Parameters:
list [out] linked list structure
value [out] value of removed item
Definition at line 128 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_llist_destruct(), arrow_llist_remove_after(), arrow_llist_remove_tail(), and find_cost_order().
void arrow_llist_remove_tail (arrow_llist * list, int * value)
Removes the tail item in the list. NOTE: O(n) procedure!
Parameters:
list [out] linked list structure
value [out] value of removed item
Definition at line 153 of file llist.c.
References arrow_llist_remove_head(), arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
void arrow_llist_swap (arrow_llist * a, arrow_llist * b)
Swaps the two given lists.
Parameters:
a [out] the first list
b [out] the second list
Definition at line 39 of file llist.c.
References arrow_llist::head, arrow_llist::size, and arrow_llist::tail.
Referenced by improve_tour().
void arrow_llist_to_array (arrow_llist * list, int * array)
Copys data from linked list into array. Assume array is big enough to handle linked list!
Parameters:
list [in] linked list structure
array [out] array to copy items into
Definition at line 214 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, and arrow_llist_item::next.
Referenced by arrow_tsp_rai_solve().
int arrow_options_parse (int num_opts, arrow_option options[], char * description, char * usage, int argc, char * argv[], int * opt_ind)
Parses program options.
Parameters:
num_opts [in] the number of program options
options [out] array of program options
description [in] description of program
usage [in] usage message
argc [in] number of program arguments
argv [out] array of program arguments (might be rearranged)
opt_ind [out] index first program option appears at
Definition at line 24 of file options.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_OPTION_DOUBLE, ARROW_OPTION_INT, ARROW_OPTION_STRING, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_option::long_option, print_help(), print_usage(), print_version(), and arrow_option::short_option.
Referenced by main().
int arrow_problem_abtsp_to_sbtsp (int shallow, arrow_problem * old_problem, int infinity, arrow_problem * new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
Parameters:
shallow [in] if true only a shallow copy of data will be created
old_problem [in] the asymmetric problem
infinity [in] value to use as "infinity"
new_problem [out] the new symmetric problem
Definition at line 379 of file problem.c.
References abtsp_destruct(), abtsp_get_cost(), ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_ABTSP_TO_SBTSP, ARROW_SUCCESS, ARROW_TRUE, abtsp_data::base, arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, arrow_problem::get_cost, abtsp_data::infinity, arrow_problem::name, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), and main().
void arrow_problem_destruct (arrow_problem * problem)
Deallocates problem data structure.
Parameters:
problem [out] problem data structure
Definition at line 176 of file problem.c.
References arrow_problem::data, and arrow_problem::destruct.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_feasible(), btsp_bounds(), and main().
int arrow_problem_info_cost_index (arrow_problem_info * info, int cost, int * pos)
Finds the position of the given cost into the sorted list.
Parameters:
info [in] problem info data structure
cost [in] cost to look up
pos [out] position of given cost in sorted list
Definition at line 247 of file problem.c.
References ARROW_FAILURE, arrow_hash_search(), arrow_print_error, ARROW_SUCCESS, arrow_util_binary_search(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem_info::hash, and arrow_hash::num_keys.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), baltsp_dt2_get_cost(), baltsp_shake_get_cost(), btsp_shake_1_get_cost(), cbtsp_shake_get_cost(), and main().
void arrow_problem_info_destruct (arrow_problem_info * info)
Deallocates problem info data structure.
Parameters:
info [in] problem info data structure
Definition at line 238 of file problem.c.
References arrow_hash_destruct(), arrow_problem_info::cost_list, arrow_problem_info::hash, and arrow_hash::num_keys.
Referenced by main().
int arrow_problem_info_get (arrow_problem * problem, int create_hash, arrow_problem_info * info)
Builds ordered cost list and finds min/max cost in a problem.
Parameters:
problem [in] problem data structure
create_hash [in] if true will also create hash table of cost list
info [out] problem info data structure
Definition at line 186 of file problem.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_new_array(), arrow_hash_cost_list(), ARROW_SUCCESS, ARROW_TRUE, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem::get_cost, arrow_problem_info::hash, arrow_problem_info::max_cost, arrow_problem_info::min_cost, arrow_hash::num_keys, arrow_bintree::size, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
int arrow_problem_max_cost (arrow_problem * problem)
Finds the largest cost in a problem (cheaper than calling arrow_problem_info_get).
Parameters:
problem [in] problem data structure
Returns:
The largest cost in the problem.
Definition at line 272 of file problem.c.
References ARROW_TRUE, arrow_problem::get_cost, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
int arrow_problem_mstsp_to_btsp (int shallow, arrow_problem * old_problem, int max_cost, arrow_problem * new_problem)
Transforms a MSTSP problem into the equivalent BTSP problem.
Parameters:
shallow [in] if true only a shallow copy of data will be created
old_problem [in] the MSTSP problem
max_cost [in] the maximum cost in old_problem
new_problem [out] the new BTSP problem
Definition at line 406 of file problem.c.
References ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_MSTSP_TO_BTSP, ARROW_SUCCESS, mstsp_data::base, arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, arrow_problem::get_cost, mstsp_data::max_cost, mstsp_destruct(), mstsp_get_cost(), arrow_problem::name, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by main().
void arrow_problem_print (arrow_problem * problem, int pretty)
Prints out information about a problem.
Parameters:
problem [in] problem data structure
pretty [in] if ARROW_TRUE, formats output to 8 nodes/row
Definition at line 295 of file problem.c.
References arrow_problem::get_cost, arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
int arrow_problem_read (char * file_name, arrow_problem * problem)
Reads a problem from a TSPLIB file.
Parameters:
file_name [in] path to TSPLIB file
problem [out] problem data structure
Definition at line 141 of file problem.c.
References ARROW_FAILURE, arrow_print_error, is_asymmetric(), is_symmetric(), arrow_problem::name, read_atsp(), and read_stsp().
Referenced by main().
int arrow_problem_read_tour (char * file_name, int size, int * tour)
Reads a TSPLIB tour file.
Parameters:
file_name [in] the TSPLIB tour file to read
size [in] the number of cities in the tour
tour [out] an array to hold the tour in node-node format
Definition at line 370 of file problem.c.
References ARROW_FAILURE, ARROW_SUCCESS, and CONCORDE_SUCCESS.
Referenced by main().
int arrow_util_binary_search (int * array, int size, int element, int * pos)
Performs a binary search to find the wanted element in a sorted integer array.
Parameters:
array [in] the array to search (note: must be sorted in non-increasing order)
size [in] size of the array
element [in] the element to find in the array
pos [out] the index where the element can be found in the array
Definition at line 145 of file util.c.
References ARROW_FAILURE, and ARROW_SUCCESS.
Referenced by arrow_btsp_solve(), arrow_cbap_solve(), and arrow_problem_info_cost_index().
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup * dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
Parameters:
size [in] the number of cities/vertices
dat [out] the CCdatagroup structure to create
Definition at line 115 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by apply_deep().
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup * from, CCdatagroup * to)
Makes a shallow copy of the Concorde CCdatagroup structure.
Parameters:
from [in] the CCdatagroup structure to copy from
to [out] the CCdatagroup structure to copy to
Definition at line 89 of file util.c.
int arrow_util_create_int_array (int size, int ** array) [inline]
Creates an integer array.
Parameters:
size [in] size of array
array [out] pointer to array that will be created
Definition at line 15 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_balanced_tsp_ib(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_shake(), arrow_bap_has_assignment(), arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bintree_to_new_array(), arrow_bscssp_connected(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), arrow_btsp_result_init(), arrow_cbst_solve(), arrow_dcbpb_solve(), arrow_heap_init(), arrow_tsp_rai_solve(), arrow_tsp_result_init(), arrow_util_create_int_matrix(), find_cost_order(), init_data(), and main().
int arrow_util_create_int_matrix (int rows, int cols, int *** matrix, int ** space) [inline]
Creates a full integer matrix.
Parameters:
rows [in] number of rows
cols [in] number of columns
matrix [out] pointer to matrix that will be created
space [out] pointer to matrix space that will be created
Definition at line 27 of file util.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, and arrow_util_create_int_array().
Referenced by arrow_bap_has_assignment(), arrow_bap_solve(), and arrow_dcbpb_solve().
void arrow_util_permute_array (int size, int * array)
Randomly permutes the elements of the given array.
Parameters:
size [in] the size of the array.
array [out] the array to permute.
Definition at line 228 of file util.c.
References arrow_util_random_between().
Referenced by arrow_tsp_rai_solve(), and improve_tour().
void arrow_util_print_error (const char * file_name, int line_num, const char * message) [inline]
Prints an error message to stderr with consistent formatting.
Parameters:
file_name [in] file error occured in
line_num [in] line number error occured at
message [in] error message to write
Definition at line 56 of file util.c.
void arrow_util_print_program_args (int argc, char * argv[], FILE * out)
Prints out the given program arguments to the specified file.
Parameters:
argc [in] the number of arguments
argv [in] the program arugment array
out [in] the file handle to print out to
Definition at line 195 of file util.c.
Referenced by main().
int arrow_util_random () [inline]
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
Returns:
a random integer.
Definition at line 215 of file util.c.
int arrow_util_random_between (int min, int max) [inline]
Returns a random number between min and max.
Parameters:
min [in] the minimum random number to return
max [in] the maximum random number to return
Returns:
a random integer in the range [min, max]
Definition at line 221 of file util.c.
Referenced by arrow_util_permute_array(), baltsp_dt2_get_cost(), baltsp_shake_initialize(), btsp_shake_1_initialize(), cbtsp_shake_initialize(), construct_tour(), and improve_tour().
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
Parameters:
seed [in] the random number seed.
Definition at line 206 of file util.c.
Referenced by main().
void arrow_util_redirect_stdout_to_file (const char * filename, int * old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
Parameters:
filename [in] name of file to direct STDOUT to
old_stream [out] existing file handle for STDOUT stream (necessary for restoring stream afterwards)
Definition at line 69 of file util.c.
Referenced by main().
int arrow_util_regex_match (char * string, char * pattern)
Determines if the given string turns up a match for the given regular expression pattern.
Parameters:
string [in] the string to match against
pattern [in] the regular expression pattern to match
Returns:
ARROW_TRUE if a match is found, ARROW_FALSE if not.
Definition at line 177 of file util.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by is_asymmetric(), and is_symmetric().
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
Parameters:
old_stream [in] existing file handle for STDOUT stream
Definition at line 78 of file util.c.
Referenced by main().
void arrow_util_sbtsp_to_abstp_tour (arrow_problem * problem, int * old_tour, int * new_tour)
Converts a symmetric tour to an asymmetric tour.
Parameters:
problem [in] problem associated with tour.
old_tour [in] the symmetric tour.
new_tour [out] the asymmetric tour.
Definition at line 260 of file util.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib2(), and main().
void arrow_util_write_problem (arrow_problem * problem, char * comment, FILE * out)
Writes a problem in TSPLIB format as a lower diagonal matrix.
Parameters:
problem [in] problem to print out.
comment [in] additional comment (optional).
out [out] the file descriptor id to print out to.
Definition at line 277 of file util.c.
References arrow_problem::get_cost, arrow_problem::name, and arrow_problem::size.
Referenced by main().
void arrow_util_write_tour (arrow_problem * problem, char * comment, int * tour, FILE * out)
Writes a tour in TSPLIB format.
Parameters:
problem [in] problem associated with tour.
comment [in] additional comment (optional).
tour [in] the tour to print out.
out [out] the file descriptor id to print out to.
Definition at line 241 of file util.c.
References arrow_problem::name, and arrow_problem::size.
Referenced by main().
double arrow_util_zeit () [inline]
Used to measure timings.
Returns:
a value representing the CPU time in seconds
Definition at line 63 of file util.c.
Referenced by arrow_2mb_solve(), arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_bap_solve(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_solve(), arrow_cbap_solve(), arrow_cbst_solve(), arrow_dcbpb_solve(), arrow_tsp_cc_exact_solve(), arrow_tsp_cc_lk_solve(), arrow_tsp_rai_solve(), btsp_bounds(), and main().
void arrow_xml_attribute_end (FILE * out) [inline]
Definition at line 81 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_attribute_int (char * name, int value, FILE * out) [inline]
Definition at line 39 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_attribute_start (char * name, FILE * out) [inline]
Definition at line 75 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_attribute_string (char * name, char * value, FILE * out) [inline]
Definition at line 45 of file xml.c.
void arrow_xml_element_bool (char * name, int value, FILE * out) [inline]
Writes an XML tag out for a boolean value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 33 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_close (char * name, FILE * out) [inline]
Definition at line 69 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_double (char * name, double value, FILE * out) [inline]
Writes an XML tag out for a double value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 21 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_end (FILE * out) [inline]
Definition at line 57 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_int (char * name, int value, FILE * out) [inline]
Writes an XML tag out for an integer value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 15 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_open (char * name, FILE * out) [inline]
Definition at line 63 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_start (char * name, FILE * out) [inline]
Definition at line 51 of file xml.c.
Referenced by arrow_btsp_result_print_xml(), and main().
void arrow_xml_element_string (char * name, char * value, FILE * out) [inline]
Writes an XML tag out for a string value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 27 of file xml.c.