Arrow: bin/cost-list.c File Reference
bin/cost-list.c File Reference
Prints cost matrix for delta feasibility problem.
#include "common.h"
#include "btsp.h"
Defines
#define NUM_OPTS 3
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
int lower_bound = -2
int upper_bound = INT_MAX
arrow_option options [NUM_OPTS]
char * desc = "Prints cost list for problem"
char * usage = "-i tsplib.tsp -d #"
Detailed Description
Prints cost matrix for delta feasibility problem.
Prints cost matrix for delta feasibility problem. For use for verifying problem optimality with Concorde.
Author:
John LaRusic
Definition in file cost-list.c.
Define Documentation
#define NUM_OPTS 3
Definition at line 20 of file cost-list.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file cost-list.c.
References arrow_options_parse(), arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), arrow_problem_info_destruct(), arrow_problem_info_get(), arrow_problem_read(), ARROW_TRUE, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, desc, input_file, lower_bound, NUM_OPTS, upper_bound, and usage.
Variable Documentation
char* desc = "Prints cost list for problem"
Definition at line 30 of file cost-list.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 15 of file cost-list.c.
int lower_bound = -2
Definition at line 16 of file cost-list.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE},
    {'l', "lower-bound", "initial lower bound",
        ARROW_OPTION_INT, &lower_bound, ARROW_FALSE, ARROW_TRUE},
    {'u', "upper-bound", "initial upper bound",
        ARROW_OPTION_INT, &upper_bound, ARROW_FALSE, ARROW_TRUE}
}
Definition at line 21 of file cost-list.c.
char* program_name
Program name
Definition at line 14 of file cost-list.c.
int upper_bound = INT_MAX
Definition at line 17 of file cost-list.c.
char* usage = "-i tsplib.tsp -d #"
Definition at line 31 of file cost-list.c.