Arrow: lib/btsp/feasible.c File Reference
lib/btsp/feasible.c File Reference
Bottleneck traveling salesman problem (BTSP) methods.
#include "common.h"
#include "btsp.h"
Functions
int arrow_btsp_feasible (arrow_problem *problem, int num_steps, arrow_btsp_solve_plan *steps, int min_cost, int max_cost, int *feasible, arrow_btsp_result *result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using min_cost <= costs <= max_cost.
Detailed Description
Bottleneck traveling salesman problem (BTSP) methods.
Heuristic for solving the bottleneck traveling salesman problem (BTSP).
Author:
John LaRusic
Definition in file feasible.c.
Function Documentation
int arrow_btsp_feasible (arrow_problem * problem, int num_steps, arrow_btsp_solve_plan * steps, int min_cost, int max_cost, int * feasible, arrow_btsp_result * result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using min_cost <= costs <= max_cost.
Parameters:
problem [in] problem to solve
num_steps [in] total number of steps in solve plan
steps [in] solve plan step details
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
feasible [out] true if a feasible tour exists, false otherwise
result [out] resulting BTSP tour found
TODO: Find a better way of doing this upper bound update
Definition at line 16 of file feasible.c.
References arrow_btsp_fun_apply(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_problem_destruct(), ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_tsp_solve(), ARROW_TSP_SOLVER_COUNT, arrow_btsp_solve_plan::attempts, arrow_btsp_fun::feasible, arrow_btsp_result::found_tour, arrow_btsp_solve_plan::fun, arrow_problem::get_cost, arrow_btsp_result::max_cost, arrow_btsp_result::min_cost, arrow_tsp_result::obj_value, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_tsp_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_tsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_solve_plan::tsp_params, and arrow_btsp_solve_plan::tsp_solver.
Referenced by arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib2(), and arrow_btsp_solve().