Arrow: lib/btsp/fun_cbtsp.c File Reference
lib/btsp/fun_cbtsp.c File Reference
Cost matrix functions for the constrained BTSP.
#include "common.h"
#include "btsp.h"
Data Structures
struct cbtsp_basic_data
Info for basic constrained cost matrix function.
struct cbtsp_shake_data
Info for shake constrained cost matrix function.
Functions
int cbtsp_basic_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int cbtsp_basic_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void cbtsp_basic_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int cbtsp_basic_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int cbtsp_shake_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int cbtsp_shake_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void cbtsp_shake_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int cbtsp_shake_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int arrow_btsp_fun_cbtsp_basic (int shallow, double feasible_length, int infinity, arrow_btsp_fun *fun)
Constrained BTSP to TSP function.
int arrow_btsp_fun_cbtsp_shake (int shallow, double feasible_length, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Constrained "Shake" BTSP to TSP function.
Detailed Description
Cost matrix functions for the constrained BTSP.
Cost matrix transformation functions for the constrained bottleneck traveling salesman problem (SBTSP).
Author:
John LaRusic
Definition in file fun_cbtsp.c.
Function Documentation
int arrow_btsp_fun_cbtsp_basic (int shallow, double feasible_length, int infinity, arrow_btsp_fun * fun)
Constrained BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
fun [out] function structure
Definition at line 132 of file fun_cbtsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, cbtsp_basic_destruct(), cbtsp_basic_feasible(), cbtsp_basic_get_cost(), cbtsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, cbtsp_basic_data::feasible_length, arrow_btsp_fun::get_cost, cbtsp_basic_data::infinity, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_cbtsp_shake (int shallow, double feasible_length, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Constrained "Shake" BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
feasible_length [in] length of feasible tour
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 156 of file fun_cbtsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), cbtsp_shake_destruct(), cbtsp_shake_feasible(), cbtsp_shake_get_cost(), cbtsp_shake_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, cbtsp_shake_data::feasible_length, arrow_btsp_fun::get_cost, cbtsp_shake_data::infinity, cbtsp_shake_data::info, arrow_btsp_fun::initialize, cbtsp_shake_data::random_list, cbtsp_shake_data::random_list_length, cbtsp_shake_data::random_max, cbtsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
void cbtsp_basic_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 216 of file fun_cbtsp.c.
References arrow_btsp_fun::data.
Referenced by arrow_btsp_fun_cbtsp_basic().
int cbtsp_basic_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
base_problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 226 of file fun_cbtsp.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_btsp_fun::data.
Referenced by arrow_btsp_fun_cbtsp_basic().
int cbtsp_basic_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 197 of file fun_cbtsp.c.
References arrow_btsp_fun::data, arrow_problem::get_cost, and cbtsp_basic_data::infinity.
Referenced by arrow_btsp_fun_cbtsp_basic().
int cbtsp_basic_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 210 of file fun_cbtsp.c.
References ARROW_SUCCESS.
Referenced by arrow_btsp_fun_cbtsp_basic().
void cbtsp_shake_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 273 of file fun_cbtsp.c.
References arrow_btsp_fun::data, and cbtsp_shake_data::random_list.
Referenced by arrow_btsp_fun_cbtsp_shake().
int cbtsp_shake_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
base_problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 286 of file fun_cbtsp.c.
References ARROW_FALSE, ARROW_TRUE, arrow_btsp_fun::data, cbtsp_shake_data::feasible_length, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_cbtsp_shake().
int cbtsp_shake_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 234 of file fun_cbtsp.c.
References arrow_print_error, arrow_problem_info_cost_index(), arrow_btsp_fun::data, arrow_problem::get_cost, cbtsp_shake_data::infinity, cbtsp_shake_data::info, and cbtsp_shake_data::random_list.
Referenced by arrow_btsp_fun_cbtsp_shake().
int cbtsp_shake_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 254 of file fun_cbtsp.c.
References arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_SUCCESS, arrow_util_random_between(), arrow_btsp_fun::data, cbtsp_shake_data::random_list, cbtsp_shake_data::random_list_length, cbtsp_shake_data::random_max, and cbtsp_shake_data::random_min.
Referenced by arrow_btsp_fun_cbtsp_shake().