Arrow: lib/baltsp/fun_baltsp.c File Reference
lib/baltsp/fun_baltsp.c File Reference
Cost matrix functions for the Balanced TSP.
#include "common.h"
#include "baltsp.h"
Data Structures
struct baltsp_shake_data
Info for shake type I cost matrix function.
Functions
int baltsp_basic_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int baltsp_basic_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void baltsp_basic_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int baltsp_basic_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int baltsp_ut_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int baltsp_ut_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int baltsp_shake_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int baltsp_shake_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void baltsp_shake_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int baltsp_ib_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int baltsp_ib_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int baltsp_dt2_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int baltsp_dt2_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void baltsp_dt2_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int baltsp_dt2_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int arrow_baltsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BalTSP to TSP function.
int arrow_baltsp_fun_ut (int shallow, arrow_btsp_fun *fun)
BalTSP to TSP function that favours values closer to the max_cost.
int arrow_baltsp_fun_shake (int shallow, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
BalTSP Controled Shake.
int arrow_baltsp_fun_ib (int shallow, arrow_btsp_fun *fun)
BalTSP Iterative Bottleneck transformation.
int arrow_baltsp_fun_dt2 (int shallow, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Detailed Description
Cost matrix functions for the Balanced TSP.
Cost matrix transformation functions for the balanced traveling salesman problem (BalTSP).
Author:
John LaRusic
Definition in file fun_baltsp.c.
Function Documentation
int arrow_baltsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BalTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 206 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_feasible(), baltsp_basic_get_cost(), baltsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_dt2 (int shallow, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Definition at line 278 of file fun_baltsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), baltsp_dt2_feasible(), baltsp_dt2_get_cost(), baltsp_dt2_initialize(), baltsp_shake_destruct(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, arrow_btsp_fun::initialize, baltsp_shake_data::random_list, baltsp_shake_data::random_list_length, baltsp_shake_data::random_max, baltsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_ib (int shallow, arrow_btsp_fun * fun)
BalTSP Iterative Bottleneck transformation.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 266 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_initialize(), baltsp_ib_feasible(), baltsp_ib_get_cost(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), and btsp_bounds().
int arrow_baltsp_fun_shake (int shallow, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
BalTSP Controled Shake.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 230 of file fun_baltsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), baltsp_basic_feasible(), baltsp_shake_destruct(), baltsp_shake_get_cost(), baltsp_shake_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, arrow_btsp_fun::initialize, baltsp_shake_data::random_list, baltsp_shake_data::random_list_length, baltsp_shake_data::random_max, baltsp_shake_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_baltsp_fun_ut (int shallow, arrow_btsp_fun * fun)
BalTSP to TSP function that favours values closer to the max_cost.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 218 of file fun_baltsp.c.
References ARROW_SUCCESS, baltsp_basic_destruct(), baltsp_basic_initialize(), baltsp_ut_feasible(), baltsp_ut_get_cost(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
void baltsp_basic_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 334 of file fun_baltsp.c.
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_ib(), and arrow_baltsp_fun_ut().
int baltsp_basic_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 338 of file fun_baltsp.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_baltsp_fun_basic(), and arrow_baltsp_fun_shake().
int baltsp_basic_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 316 of file fun_baltsp.c.
References arrow_problem::get_cost.
Referenced by arrow_baltsp_fun_basic().
int baltsp_basic_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 328 of file fun_baltsp.c.
References ARROW_SUCCESS.
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_ib(), and arrow_baltsp_fun_ut().
void baltsp_dt2_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
int baltsp_dt2_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 492 of file fun_baltsp.c.
References ARROW_FALSE, ARROW_TRUE, arrow_btsp_fun::data, baltsp_shake_data::random_list, and arrow_problem::size.
Referenced by arrow_baltsp_fun_dt2().
int baltsp_dt2_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 441 of file fun_baltsp.c.
References arrow_print_error, arrow_problem_info_cost_index(), arrow_util_random_between(), arrow_btsp_fun::data, arrow_problem::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, baltsp_shake_data::random_list, baltsp_shake_data::random_max, baltsp_shake_data::random_min, and arrow_problem::size.
Referenced by arrow_baltsp_fun_dt2().
int baltsp_dt2_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 466 of file fun_baltsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, baltsp_shake_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, baltsp_shake_data::info, and baltsp_shake_data::random_list.
Referenced by arrow_baltsp_fun_dt2().
int baltsp_ib_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 433 of file fun_baltsp.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_problem::size.
Referenced by arrow_baltsp_fun_ib().
int baltsp_ib_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 420 of file fun_baltsp.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_baltsp_fun_ib().
void baltsp_shake_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 407 of file fun_baltsp.c.
References arrow_btsp_fun::data, and baltsp_shake_data::random_list.
Referenced by arrow_baltsp_fun_dt2(), and arrow_baltsp_fun_shake().
int baltsp_shake_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 366 of file fun_baltsp.c.
References arrow_print_error, arrow_problem_info_cost_index(), arrow_btsp_fun::data, arrow_problem::get_cost, baltsp_shake_data::infinity, baltsp_shake_data::info, and baltsp_shake_data::random_list.
Referenced by arrow_baltsp_fun_shake().
int baltsp_shake_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 387 of file fun_baltsp.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_SUCCESS, arrow_util_random_between(), arrow_btsp_fun::data, baltsp_shake_data::random_list, baltsp_shake_data::random_list_length, baltsp_shake_data::random_max, and baltsp_shake_data::random_min.
Referenced by arrow_baltsp_fun_shake(), and baltsp_dt2_initialize().
int baltsp_ut_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 358 of file fun_baltsp.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_problem::size.
Referenced by arrow_baltsp_fun_ut().
int baltsp_ut_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 345 of file fun_baltsp.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_baltsp_fun_ut().