Arrow: lib/btsp/fun_abtsp.c File Reference
lib/btsp/fun_abtsp.c File Reference
Cost matrix functions for the asymmetric BTSP.
#include "common.h"
#include "btsp.h"
Functions
int atsp_basic_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
int atsp_basic_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void atsp_basic_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int atsp_basic_feasible (arrow_btsp_fun *fun, arrow_problem *problem, int delta, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function for asymmetric problem instances.
Detailed Description
Cost matrix functions for the asymmetric BTSP.
Cost matrix transformation functions for the asymmetric bottleneck traveling salesman problem (SBTSP).
Author:
John LaRusic
Definition in file fun_abtsp.c.
Function Documentation
int arrow_btsp_fun_basic_atsp (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function for asymmetric problem instances.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 61 of file fun_abtsp.c.
References ARROW_SUCCESS, atsp_basic_destruct(), atsp_basic_feasible(), atsp_basic_get_cost(), atsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
void atsp_basic_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 97 of file fun_abtsp.c.
Referenced by arrow_btsp_fun_basic_atsp().
int atsp_basic_feasible (arrow_btsp_fun * fun, arrow_problem * problem, int delta, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
delta [in] delta parameter
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 101 of file fun_abtsp.c.
References ARROW_FALSE, ARROW_TRUE, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_basic_atsp().
int atsp_basic_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
delta [in] delta parameter
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 77 of file fun_abtsp.c.
References arrow_problem::get_cost.
Referenced by arrow_btsp_fun_basic_atsp().
int atsp_basic_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 91 of file fun_abtsp.c.
References ARROW_SUCCESS.
Referenced by arrow_btsp_fun_basic_atsp().