Arrow: lib/btsp/fun_btsp.c File Reference
lib/btsp/fun_btsp.c File Reference
Cost matrix functions for the symmetric BTSP.
#include "common.h"
#include "btsp.h"
Data Structures
struct btsp_shake_1_data
Info for shake type I cost matrix function.
Functions
int btsp_basic_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int btsp_basic_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void btsp_basic_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int btsp_basic_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int btsp_shake_1_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int btsp_shake_1_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void btsp_shake_1_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int btsp_asym_shift_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
void btsp_asym_shift_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int btsp_asym_shift_feasible (arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function.
int arrow_btsp_fun_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Controlled Type I Shake.
int arrow_btsp_fun_asym_shift (int shallow, int shift, arrow_btsp_fun *fun)
Shifts all costs by given amount; used to remove negative costs.
Detailed Description
Cost matrix functions for the symmetric BTSP.
Cost matrix transformation functions for the symmetric bottleneck traveling salesman problem (SBTSP).
Author:
John LaRusic
Definition in file fun_btsp.c.
Function Documentation
int arrow_btsp_fun_asym_shift (int shallow, int shift, arrow_btsp_fun * fun)
Shifts all costs by given amount; used to remove negative costs.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
shift [in] value to shift all costs by
fun [out] function structure
Definition at line 191 of file fun_btsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, btsp_asym_shift_destruct(), btsp_asym_shift_feasible(), btsp_asym_shift_get_cost(), btsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 143 of file fun_btsp.c.
References ARROW_SUCCESS, btsp_basic_destruct(), btsp_basic_feasible(), btsp_basic_get_cost(), btsp_basic_initialize(), arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Controlled Type I Shake.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 155 of file fun_btsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), btsp_basic_feasible(), btsp_shake_1_destruct(), btsp_shake_1_get_cost(), btsp_shake_1_initialize(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, btsp_shake_1_data::infinity, btsp_shake_1_data::info, arrow_btsp_fun::initialize, btsp_shake_1_data::random_list, btsp_shake_1_data::random_list_length, btsp_shake_1_data::random_max, btsp_shake_1_data::random_min, and arrow_btsp_fun::shallow.
Referenced by main().
void btsp_asym_shift_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 349 of file fun_btsp.c.
References arrow_btsp_fun::data.
Referenced by arrow_btsp_fun_asym_shift().
int btsp_asym_shift_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 359 of file fun_btsp.c.
References btsp_basic_feasible(), arrow_btsp_fun::data, and arrow_problem::size.
Referenced by arrow_btsp_fun_asym_shift().
int btsp_asym_shift_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 334 of file fun_btsp.c.
References arrow_btsp_fun::data, and arrow_problem::get_cost.
Referenced by arrow_btsp_fun_asym_shift().
void btsp_basic_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 237 of file fun_btsp.c.
Referenced by arrow_btsp_fun_basic().
int btsp_basic_feasible (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 241 of file fun_btsp.c.
References arrow_debug, ARROW_FALSE, ARROW_TRUE, arrow_problem::fixed_edges, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_btsp_fun_basic(), arrow_btsp_fun_shake_1(), and btsp_asym_shift_feasible().
int btsp_basic_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 217 of file fun_btsp.c.
References arrow_problem::get_cost.
Referenced by arrow_btsp_fun_basic().
int btsp_basic_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 231 of file fun_btsp.c.
References ARROW_SUCCESS.
Referenced by arrow_btsp_fun_asym_shift(), and arrow_btsp_fun_basic().
void btsp_shake_1_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 321 of file fun_btsp.c.
References arrow_btsp_fun::data, and btsp_shake_1_data::random_list.
Referenced by arrow_btsp_fun_shake_1().
int btsp_shake_1_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 278 of file fun_btsp.c.
References arrow_print_error, arrow_problem_info_cost_index(), arrow_btsp_fun::data, arrow_problem::get_cost, btsp_shake_1_data::infinity, btsp_shake_1_data::info, and btsp_shake_1_data::random_list.
Referenced by arrow_btsp_fun_shake_1().
int btsp_shake_1_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 301 of file fun_btsp.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_SUCCESS, arrow_util_random_between(), arrow_btsp_fun::data, btsp_shake_1_data::random_list, btsp_shake_1_data::random_list_length, btsp_shake_1_data::random_max, and btsp_shake_1_data::random_min.
Referenced by arrow_btsp_fun_shake_1().