Arrow: lib/btsp/fun.c File Reference
lib/btsp/fun.c File Reference
Cost matrix transformation functions.
#include "common.h"
#include "btsp.h"
Data Structures
struct fun_data
Functions
int apply_shallow (arrow_btsp_fun *fun, arrow_problem *old_problem, int min_cost, int max_cost, arrow_problem *new_problem)
Creates a shallow data structure with data applied with given cost matrix function and some base problem.
int apply_deep (arrow_btsp_fun *fun, arrow_problem *old_problem, int min_cost, int max_cost, arrow_problem *new_problem)
Creates a deep data structure with data applied with given cost matrix function and some base problem.
int fun_get_cost (arrow_problem *this, int i, int j)
Cost function for problems based upon cost matrix functions.
void fun_destruct (arrow_problem *problem)
Destructs problem based upon cost matrix functions.
int cc_get_cost (arrow_problem *problem, int i, int j)
Cost function for problems based upon Concorde's data structure.
void cc_destruct (arrow_problem *problem)
Destructs problems based upon Concorde's data structure.
int arrow_btsp_fun_apply (arrow_btsp_fun *fun, arrow_problem *old_problem, int min_cost, int max_cost, arrow_problem *new_problem)
Applies the given function to the given problem to create a new problem.
void arrow_btsp_fun_destruct (arrow_btsp_fun *fun)
Destructs a function structure.
Detailed Description
Cost matrix transformation functions.
Cost matrix transformation functions for the bottleneck traveling salesman problem (BTSP).
Author:
John LaRusic
Definition in file fun.c.
Function Documentation
int apply_deep (arrow_btsp_fun * fun, arrow_problem * old_problem, int min_cost, int max_cost, arrow_problem * new_problem)
Creates a deep data structure with data applied with given cost matrix function and some base problem.
Parameters:
fun [in] the cost matrix function
old_problem [in] the base problem
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
new_problem [out] the newly created, "deep" problem
Definition at line 149 of file fun.c.
References ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, arrow_util_CCdatagroup_init_matrix(), cc_destruct(), cc_get_cost(), arrow_problem::data, arrow_problem::destruct, arrow_problem::get_cost, arrow_btsp_fun::get_cost, arrow_problem::size, and arrow_problem::type.
Referenced by arrow_btsp_fun_apply().
int apply_shallow (arrow_btsp_fun * fun, arrow_problem * old_problem, int min_cost, int max_cost, arrow_problem * new_problem)
Creates a shallow data structure with data applied with given cost matrix function and some base problem.
Parameters:
fun [in] the cost matrix function
old_problem [in] the base problem
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
new_problem [out] the newly created, "shallow" problem
Definition at line 125 of file fun.c.
References ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_DATA_BTSP_FUN, ARROW_SUCCESS, fun_data::base_problem, arrow_problem::data, arrow_problem::destruct, fun_data::fun, fun_destruct(), fun_get_cost(), arrow_problem::get_cost, fun_data::max_cost, fun_data::min_cost, and arrow_problem::type.
Referenced by arrow_btsp_fun_apply().
int arrow_btsp_fun_apply (arrow_btsp_fun * fun, arrow_problem * old_problem, int min_cost, int max_cost, arrow_problem * new_problem)
Applies the given function to the given problem to create a new problem.
Parameters:
fun [in] function structure
old_problem [in] existing problem
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
new_problem [out] new problem to create
Definition at line 93 of file fun.c.
References apply_deep(), apply_shallow(), ARROW_FAILURE, arrow_print_error, arrow_problem::fixed_edges, arrow_btsp_fun::initialize, arrow_problem::name, arrow_btsp_fun::shallow, arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_feasible(), btsp_bounds(), and main().
void arrow_btsp_fun_destruct (arrow_btsp_fun * fun)
Destructs a function structure.
Parameters:
fun [out] function structure
Definition at line 115 of file fun.c.
References arrow_btsp_fun::destruct.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_solve_plan_destruct(), btsp_bounds(), and main().
void cc_destruct (arrow_problem * problem)
Destructs problems based upon Concorde's data structure.
Parameters:
problem [in] problem structure
Definition at line 206 of file fun.c.
References arrow_problem::data.
Referenced by apply_deep().
int cc_get_cost (arrow_problem * problem, int i, int j)
Cost function for problems based upon Concorde's data structure.
Parameters:
problem [in] problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
cost between node i and node j
Definition at line 199 of file fun.c.
References arrow_problem::data.
Referenced by apply_deep().
void fun_destruct (arrow_problem * problem)
Destructs problem based upon cost matrix functions.
Parameters:
problem [in] problem structure
Definition at line 192 of file fun.c.
References arrow_problem::data.
Referenced by apply_shallow().
int fun_get_cost (arrow_problem * this, int i, int j)
Cost function for problems based upon cost matrix functions.
Parameters:
this [in] problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
cost between node i and node j
Definition at line 185 of file fun.c.
References fun_data::base_problem, fun_data::fun, arrow_btsp_fun::get_cost, fun_data::max_cost, and fun_data::min_cost.
Referenced by apply_shallow().