Arrow: lib/btsp/fun_sbtsp.c File Reference
lib/btsp/fun_sbtsp.c File Reference
Cost matrix functions for the symmetric BTSP.
#include "common.h"
#include "btsp.h"
Data Structures
struct sbtsp_shake_1_data
Info for shake type I cost matrix function.
Functions
int sbtsp_basic_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
int sbtsp_basic_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void sbtsp_basic_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int sbtsp_basic_feasible (arrow_btsp_fun *fun, arrow_problem *problem, int delta, double tour_length, int *tour)
Determines if the given tour is feasible or not.
int sbtsp_shake_1_get_cost (arrow_btsp_fun *fun, arrow_problem *base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
int sbtsp_shake_1_initialize (arrow_btsp_fun *fun)
Initializes the function data.
void sbtsp_shake_1_destruct (arrow_btsp_fun *fun)
Destructs the function data.
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun *fun)
Basic BTSP to TSP function.
int arrow_btsp_fun_sbtsp_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info *info, arrow_btsp_fun *fun)
Controlled Type I Shake.
Detailed Description
Cost matrix functions for the symmetric BTSP.
Cost matrix transformation functions for the symmetric bottleneck traveling salesman problem (SBTSP).
Author:
John LaRusic
Definition in file fun_sbtsp.c.
Function Documentation
int arrow_btsp_fun_basic (int shallow, arrow_btsp_fun * fun)
Basic BTSP to TSP function.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
fun [out] function structure
Definition at line 105 of file fun_sbtsp.c.
References ARROW_SUCCESS, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, arrow_btsp_fun::initialize, sbtsp_basic_destruct(), sbtsp_basic_feasible(), sbtsp_basic_get_cost(), sbtsp_basic_initialize(), and arrow_btsp_fun::shallow.
Referenced by main().
int arrow_btsp_fun_sbtsp_shake_1 (int shallow, int infinity, int random_min, int random_max, arrow_problem_info * info, arrow_btsp_fun * fun)
Controlled Type I Shake.
Parameters:
shallow [in] ARROW_TRUE for shallow copy, ARROW_FALSE for deep
infinity [in] value to use as "infinity"
random_min [in] minimum random value to generate
random_max [in] maximum random value to generate
info [in] information about the original problem
fun [out] function structure
Definition at line 117 of file fun_sbtsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_problem_info::cost_list_length, arrow_btsp_fun::data, arrow_btsp_fun::destruct, arrow_btsp_fun::feasible, arrow_btsp_fun::get_cost, sbtsp_shake_1_data::infinity, sbtsp_shake_1_data::info, arrow_btsp_fun::initialize, sbtsp_shake_1_data::random_list, sbtsp_shake_1_data::random_list_length, sbtsp_shake_1_data::random_max, sbtsp_shake_1_data::random_min, sbtsp_basic_feasible(), sbtsp_shake_1_destruct(), sbtsp_shake_1_get_cost(), sbtsp_shake_1_initialize(), and arrow_btsp_fun::shallow.
Referenced by main().
void sbtsp_basic_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 170 of file fun_sbtsp.c.
Referenced by arrow_btsp_fun_basic().
int sbtsp_basic_feasible (arrow_btsp_fun * fun, arrow_problem * problem, int delta, double tour_length, int * tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
delta [in] delta parameter
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Definition at line 174 of file fun_sbtsp.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_btsp_fun_basic(), and arrow_btsp_fun_sbtsp_shake_1().
int sbtsp_basic_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
delta [in] delta parameter
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 156 of file fun_sbtsp.c.
References arrow_problem::get_cost.
Referenced by arrow_btsp_fun_basic().
int sbtsp_basic_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 164 of file fun_sbtsp.c.
References ARROW_SUCCESS.
Referenced by arrow_btsp_fun_basic().
void sbtsp_shake_1_destruct (arrow_btsp_fun * fun)
Destructs the function data.
Parameters:
fun [out] the function structure to destruct
Definition at line 220 of file fun_sbtsp.c.
References arrow_btsp_fun::data, and sbtsp_shake_1_data::random_list.
Referenced by arrow_btsp_fun_sbtsp_shake_1().
int sbtsp_shake_1_get_cost (arrow_btsp_fun * fun, arrow_problem * base_problem, int delta, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
base_problem [in] problem structure
delta [in] delta parameter
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Definition at line 181 of file fun_sbtsp.c.
References arrow_print_error, arrow_problem_info_cost_index(), arrow_btsp_fun::data, arrow_problem::get_cost, sbtsp_shake_1_data::infinity, sbtsp_shake_1_data::info, and sbtsp_shake_1_data::random_list.
Referenced by arrow_btsp_fun_sbtsp_shake_1().
int sbtsp_shake_1_initialize (arrow_btsp_fun * fun)
Initializes the function data.
Parameters:
fun [out] the function structure to initialize
Definition at line 201 of file fun_sbtsp.c.
References arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_array(), ARROW_SUCCESS, arrow_util_random_between(), arrow_btsp_fun::data, sbtsp_shake_1_data::random_list, sbtsp_shake_1_data::random_list_length, sbtsp_shake_1_data::random_max, and sbtsp_shake_1_data::random_min.
Referenced by arrow_btsp_fun_sbtsp_shake_1().