Arrow: Bottleneck Biconnected Spanning Subgraph
Bottleneck Biconnected Spanning Subgraph
[Executables]
int main (int argc, char *argv[])
Entry point to program.
void print_help (char *program_name)
Prints usage/help message.
void print_version (char *program_name)
Prints version message.
void print_usage (char *program_name)
Prints usage message.
Function Documentation
int main (int argc, char * argv[])
Entry point to program.
Definition at line 61 of file bbssp.c.
References long_options, print_help(), print_usage(), print_version(), and short_options.
void print_help (char * program_name)
Prints usage/help message.
Parameters:
program_name [in] name of program
Definition at line 104 of file bbssp.c.
References print_usage().
Referenced by main().
void print_usage (char * program_name)
Prints usage message.
Parameters:
program_name [in] name of program
Definition at line 132 of file bbssp.c.
Referenced by main(), and print_help().
void print_version (char * program_name)
Prints version message.
Parameters:
program_name [in] name of program
Definition at line 118 of file bbssp.c.
Referenced by main().