Arrow: lib/common/heap.c File Reference
lib/common/heap.c File Reference
Binary heap implementation.
#include "common.h"
Functions
void siftup (arrow_heap *heap, int i)
Sifts nodes up as necessary to maintain heap property.
void siftdown (arrow_heap *heap, int i)
Sifts nodes down as necessary to maintain heap property.
int parent (arrow_heap *heap, int i)
Returns the position of the parent to the given node.
int is_leaf (arrow_heap *heap, int i)
Determines if the given node is a leaf node in the heap tree.
int left_child (arrow_heap *heap, int i)
Returns the position of the left child to the given node.
int right_child (arrow_heap *heap, int i)
Returns the position of the right child to the given node.
int min_child (arrow_heap *heap, int i)
Returns the smaller of the two child nodes to the given node.
void swap_nodes (arrow_heap *heap, int i, int j)
Swaps the two given nodes in the heap tree.
int arrow_heap_init (arrow_heap *heap, int max_size)
Initializes a new binary heap.
void arrow_heap_destruct (arrow_heap *heap)
Destructs a binary heap.
void arrow_heap_empty (arrow_heap *heap)
Empties the heap of items.
int arrow_heap_insert (arrow_heap *heap, int key, int value)
Inserts a new (key,value) pair into the heap.
int arrow_heap_in (arrow_heap *heap, int value)
Determines if the given value is present in the heap.
void arrow_heap_change_key (arrow_heap *heap, int key, int value)
Changes the key for the given value in the heap.
int arrow_heap_get_min (arrow_heap *heap)
Returns the value with the smallest key in the heap.
void arrow_heap_delete_min (arrow_heap *heap)
Removes the value with the smallest key from the heap.
void arrow_heap_print (arrow_heap *heap)
Prints heap structure.
Detailed Description
Binary heap implementation.
Methods for working with Arrow's binary heap data structure.
Author:
John LaRusic
Definition in file heap.c.
Function Documentation
void arrow_heap_change_key (arrow_heap * heap, int key, int value)
Changes the key for the given value in the heap.
Parameters:
heap [out] heap structure
key [in] the new key
value [in] node value to change
Definition at line 177 of file heap.c.
References arrow_heap::keys, arrow_heap::pos, siftdown(), and siftup().
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_delete_min (arrow_heap * heap)
Removes the value with the smallest key from the heap.
heap [out] heap structure
Definition at line 196 of file heap.c.
References arrow_heap::pos, siftdown(), arrow_heap::size, swap_nodes(), and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_destruct (arrow_heap * heap)
Destructs a binary heap.
Parameters:
heap [out] heap structure
Definition at line 117 of file heap.c.
References arrow_heap::keys, arrow_heap::pos, and arrow_heap::values.
Referenced by arrow_heap_init(), destroy_data(), and destruct_data().
void arrow_heap_empty (arrow_heap * heap)
Empties the heap of items.
Parameters:
heap [out] heap structure
Definition at line 128 of file heap.c.
References arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
int arrow_heap_get_min (arrow_heap * heap) [inline]
Returns the value with the smallest key in the heap.
heap [in] heap structure
Returns:
The value with the smallest key in the heap.
Definition at line 190 of file heap.c.
References arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
int arrow_heap_in (arrow_heap * heap, int value)
Determines if the given value is present in the heap.
Parameters:
heap [in] heap structure
value [in] value to check
Returns:
True or false, if the value is present in the heap
Definition at line 171 of file heap.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_heap::pos.
Referenced by dijkstra().
int arrow_heap_init (arrow_heap * heap, int max_size)
Initializes a new binary heap.
Parameters:
heap [out] heap structure
max_size [in] maximum size of heap
Definition at line 89 of file heap.c.
References ARROW_FAILURE, arrow_heap_destruct(), ARROW_SUCCESS, arrow_util_create_int_array(), arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
Referenced by init_data().
int arrow_heap_insert (arrow_heap * heap, int key, int value)
Inserts a new (key,value) pair into the heap.
Parameters:
heap [out] heap structure
key [in] key to insert
value [in] value to insert -- must be between 0 and [n-1] and not a duplicate value.
Definition at line 141 of file heap.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, siftup(), arrow_heap::size, and arrow_heap::values.
Referenced by dijkstra(), and min_span_tree().
void arrow_heap_print (arrow_heap * heap)
Prints heap structure.
heap [in] heap structure
Definition at line 206 of file heap.c.
References arrow_heap::keys, arrow_heap::max_size, arrow_heap::pos, arrow_heap::size, and arrow_heap::values.
int is_leaf (arrow_heap * heap, int i) [inline]
Determines if the given node is a leaf node in the heap tree.
Parameters:
heap [out] heap structure
i [in] node position
Returns:
ARROW_TRUE is node is a leaf, ARROW_FALSE otherwise
Definition at line 268 of file heap.c.
References ARROW_FALSE, ARROW_TRUE, and arrow_heap::size.
Referenced by min_child(), and siftdown().
int left_child (arrow_heap * heap, int i) [inline]
Returns the position of the left child to the given node.
Parameters:
heap [out] heap structure
i [in] node position
Returns:
position of left child node, or -1 if no child exists
Definition at line 274 of file heap.c.
References arrow_heap::size.
Referenced by min_child().
int min_child (arrow_heap * heap, int i)
Returns the smaller of the two child nodes to the given node.
Parameters:
heap [out] heap structure
i [in] node position
Returns:
The smaller of the left and right nodes, or -1 if node is leaf
Definition at line 288 of file heap.c.
References is_leaf(), arrow_heap::keys, left_child(), and right_child().
Referenced by siftdown().
int parent (arrow_heap * heap, int i) [inline]
Returns the position of the parent to the given node.
Parameters:
heap [out] heap structure
i [in] node position
Returns:
position of parent node, or -1 if the node is the parent
Definition at line 259 of file heap.c.
Referenced by arrow_bbssp_biconnected(), and siftup().
int right_child (arrow_heap * heap, int i) [inline]
Returns the position of the right child to the given node.
Parameters:
heap [out] heap structure
i [in] node position
Returns:
position of right child node, or -1 if no child exists
Definition at line 281 of file heap.c.
References arrow_heap::size.
Referenced by min_child().
void siftdown (arrow_heap * heap, int i)
Sifts nodes down as necessary to maintain heap property.
Parameters:
heap [out] heap structure
i [in] node to sift down from
Definition at line 242 of file heap.c.
References is_leaf(), arrow_heap::keys, min_child(), and swap_nodes().
Referenced by arrow_heap_change_key(), and arrow_heap_delete_min().
void siftup (arrow_heap * heap, int i)
Sifts nodes up as necessary to maintain heap property.
Parameters:
heap [out] heap structure
i [in] node to sift up from
Definition at line 225 of file heap.c.
References arrow_heap::keys, parent(), and swap_nodes().
Referenced by arrow_heap_change_key(), and arrow_heap_insert().
void swap_nodes (arrow_heap * heap, int i, int j)
Swaps the two given nodes in the heap tree.
Parameters:
heap [out] heap structure
i [in] first node position
j [in] second node position
Definition at line 302 of file heap.c.
References arrow_heap::keys, arrow_heap::pos, and arrow_heap::values.
Referenced by arrow_heap_delete_min(), siftdown(), and siftup().