Arrow: bin/histogram_data.c File Reference
bin/histogram_data.c File Reference
Edge length histogram data collector.
#include "arrow.h"
Defines
#define NUM_OPTS 1
Functions
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file = NULL
arrow_option options [NUM_OPTS]
char * desc = "Prints a list of every cost in problem (for histogram.py)"
char * usage = "-i tsplib.tsp"
Detailed Description
Edge length histogram data collector.
Prints out a list of every edge length present in given problem. Used in conjunction with a Python script for generating a histogram plot.
Author:
John LaRusic
Definition in file histogram_data.c.
Define Documentation
#define NUM_OPTS 1
Definition at line 17 of file histogram_data.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file histogram_data.c.
References ARROW_DEV_NULL, arrow_options_parse(), arrow_problem_destruct(), arrow_problem_read(), arrow_util_redirect_stdout_to_file(), arrow_util_restore_stdout(), desc, arrow_problem::get_cost, input_file, NUM_OPTS, arrow_problem::size, and usage.
Variable Documentation
char* desc = "Prints a list of every cost in problem (for histogram.py)"
Definition at line 23 of file histogram_data.c.
char* input_file = NULL
Given input TSPLIB file
Definition at line 14 of file histogram_data.c.
arrow_option options[NUM_OPTS]
Initial value:
{
    {'i', "input", "TSPLIB input file",
        ARROW_OPTION_STRING, &input_file, ARROW_TRUE, ARROW_TRUE}
}
Definition at line 18 of file histogram_data.c.
char* program_name
Program name
Definition at line 13 of file histogram_data.c.
char* usage = "-i tsplib.tsp"
Definition at line 24 of file histogram_data.c.