Arrow: include/lb.h File Reference
include/lb.h File Reference
Lower bound functions for the bottleneck TSP.
Data Structures
struct arrow_bound_result
A lower bound result.
Functions
int arrow_2mb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the 2-max bound (2MB) on the given problem.
int arrow_bap_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck assignment problem (BAP).
int arrow_bap_has_assignment (arrow_problem *problem, int min_cost, int max_cost, int *result)
Determines if the problem has an assignment using only costs min_cost <= c_ij <= max_cost.
int arrow_bbssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
int arrow_bbssp_biconnected (arrow_problem *problem, int min_cost, int max_cost, int *result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
int arrow_bscssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
int arrow_bscssp_connected (arrow_problem *problem, int min_cost, int max_cost, int *result)
Determines if the problem is strongly connected using only costs min_cost <= c_ij <= max_cost.
int arrow_cbap_solve (arrow_problem *problem, arrow_problem_info *info, double max_length, arrow_bound_result *result)
Solves the constrained bottleneck assignment problem (CBAP).
int arrow_cbap_lap (arrow_problem *problem, double *result)
Solves the linear assignment problem (LAP).
int arrow_cbst_solve (arrow_problem *problem, arrow_problem_info *info, double max_length, arrow_bound_result *result)
Constrained bottleneck spanning tree (CBST) solver.
int arrow_cbst_mst_solve (arrow_problem *problem, arrow_problem_info *info, int *tree, int *max_cost, double *length)
Minimum spanning tree (MST) solver.
int arrow_dcbpb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the degree constrained bottleneck paths bound (DCBPB).
Detailed Description
Lower bound functions for the bottleneck TSP.
Lower bound functions for the bottleneck TSP.
Author:
John LaRusic
Definition in file lb.h.
Function Documentation
int arrow_2mb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the 2-max bound (2MB) on the given problem.
Parameters:
problem [in] problem data
result [out] 2MB solution
Definition at line 17 of file 2mb.c.
References ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::get_cost, max(), arrow_bound_result::obj_value, arrow_problem::size, arrow_problem::symmetric, and arrow_bound_result::total_time.
Referenced by main().
int arrow_bap_has_assignment (arrow_problem * problem, int min_cost, int max_cost, int * result)
Determines if the problem has an assignment using only costs min_cost <= c_ij <= max_cost.
Parameters:
problem [in] problem data
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
result [out] ARROW_TRUE if an assignment is possible.
Definition at line 178 of file bap.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_create_int_matrix(), ford_fulkerson_labeling(), initialize_flow_data(), shortest_augmenting_path(), and arrow_problem::size.
Referenced by balanced_lb_feasible(), and dt2_lb_feasible().
int arrow_bap_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck assignment problem (BAP).
Parameters:
problem [in] problem data
info [in] problem info
result [out] BBSSP solution
Definition at line 70 of file bap.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_create_int_matrix(), arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, delta, ford_fulkerson_labeling(), initialize_flow_data(), arrow_bound_result::obj_value, shortest_augmenting_path(), arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
int arrow_bbssp_biconnected (arrow_problem * problem, int min_cost, int max_cost, int * result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
Parameters:
problem [in] problem data
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
result [out] ARROW_TRUE if biconnected, ARROW_FALSE otherwise.
Definition at line 94 of file bbssp.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_TRUE, arrow_util_create_int_array(), find_art_points(), parent(), and arrow_problem::size.
Referenced by arrow_bbssp_solve(), balanced_lb_feasible(), and dt2_lb_feasible().
int arrow_bbssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BBSSP solution
Definition at line 46 of file bbssp.c.
References arrow_bbssp_biconnected(), ARROW_FAILURE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem_info::max_cost, arrow_bound_result::obj_value, and arrow_bound_result::total_time.
Referenced by btsp_lower_bound(), and main().
int arrow_bscssp_connected (arrow_problem * problem, int min_cost, int max_cost, int * result)
Determines if the problem is strongly connected using only costs min_cost <= c_ij <= max_cost.
Parameters:
problem [in] problem data
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
result [out] ARROW_TRUE if strongly connected
Definition at line 80 of file bscssp.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_problem::size, and strongly_connected_dfs().
Referenced by arrow_bscssp_solve(), balanced_lb_feasible(), and dt2_lb_feasible().
int arrow_bscssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BSCSSP solution
Definition at line 37 of file bscssp.c.
References arrow_bscssp_connected(), ARROW_FAILURE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, and arrow_bound_result::total_time.
Referenced by main().
int arrow_cbap_lap (arrow_problem * problem, double * result)
Solves the linear assignment problem (LAP).
Parameters:
problem [in] problem data
result [out] LAP solution
Definition at line 124 of file cbap.c.
References ARROW_FAILURE, ARROW_SUCCESS, destruct_data(), init_data(), lap(), and arrow_problem::size.
int arrow_cbap_solve (arrow_problem * problem, arrow_problem_info * info, double max_length, arrow_bound_result * result)
Solves the constrained bottleneck assignment problem (CBAP).
Parameters:
problem [in] problem data
info [in] problem info
max_length [in] the maximum length of the assignment
result [out] CBAP solution
Definition at line 51 of file cbap.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_binary_search(), arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, delta, destruct_data(), arrow_problem::get_cost, init_data(), lap(), length, arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
int arrow_cbst_mst_solve (arrow_problem * problem, arrow_problem_info * info, int * tree, int * max_cost, double * length)
Minimum spanning tree (MST) solver.
Parameters:
problem [in] problem data
info [in] problem info data
tree [out] MST tree (tree[i] gives precessor for node i)
max_cost [out] the largest cost in the tree
length [out] the length of all edges in the tree
Definition at line 96 of file cbst.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, destroy_data(), init_data(), arrow_problem_info::max_cost, min_span_tree(), and arrow_problem::size.
int arrow_cbst_solve (arrow_problem * problem, arrow_problem_info * info, double max_length, arrow_bound_result * result)
Constrained bottleneck spanning tree (CBST) solver.
Parameters:
problem [in] problem data
info [in] problem info data
max_length [in] maximum spanning tree length
result [out] bound result
Definition at line 46 of file cbst.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_zeit(), init_data(), length, arrow_problem_info::max_cost, min_span_tree(), arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
int arrow_dcbpb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the degree constrained bottleneck paths bound (DCBPB).
Parameters:
problem [in] problem data
result [out] BPB solution
Definition at line 40 of file dcbpb.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_create_int_matrix(), arrow_util_zeit(), bottleneck_paths(), arrow_problem::get_cost, max(), arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().