Arrow: lib/bbssp.c File Reference
lib/bbssp.c File Reference
Bottleneck biconnected spanning subgraph problem implemenation.
#include "arrow.h"
Functions
int find_art_points (arrow_problem *problem, int max_cost, int node, int depth_num, int root_children, int *visited, int *depth, int *low, int *parent, int *art_point)
Recursively searches for articulation points in the graph using only costs less than or equal to 'max_cost' out from the given node.
int arrow_bbssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
int arrow_bbssp_biconnected (arrow_problem *problem, int max_cost, int *result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
Detailed Description
Bottleneck biconnected spanning subgraph problem implemenation.
Implemenation of the bottleneck biconnected spanning subgraph problem (BBSSP) that's used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file bbssp.c.
Function Documentation
int arrow_bbssp_biconnected (arrow_problem * problem, int max_cost, int * result)
Determines if the graph is biconnected using only edges with costs less than or equal to the given value.
Parameters:
problem [in] problem data
max_cost [in] value to check biconnectivity question against
result [out] ARROW_TRUE if biconnected, ARROW_FALSE otherwise.
Definition at line 94 of file bbssp.c.
References ARROW_ERROR_FATAL, ARROW_FALSE, ARROW_TRUE, arrow_util_create_int_array(), find_art_points(), and arrow_problem::size.
Referenced by arrow_bbssp_solve().
int arrow_bbssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck biconnected spanning subgraph problem (BBSSP) on the given problem.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BBSSP solution
Definition at line 44 of file bbssp.c.
References arrow_bbssp_biconnected(), ARROW_ERROR_FATAL, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, arrow_problem::symmetric, and arrow_bound_result::total_time.
Referenced by main().
int find_art_points (arrow_problem * problem, int max_cost, int node, int depth_num, int root_children, int * visited, int * depth, int * low, int * parent, int * art_point)
Recursively searches for articulation points in the graph using only costs less than or equal to 'max_cost' out from the given node.
Parameters:
problem [in] problem data structure
max_cost [in] the largest cost to consider as being in the graph
node [in] the node to search outward from
depth_num [in] level at which the given node was first discovered
root_children [in] count of the number of children of the root
visited [out] indicates if a node has been visited or not
depth [out] indicates the discovery depth of a node
low [out] indicates a back edge for some descendent of a node (e.g. the discovery depth of the node closest to the root and reachable from the given node by following zero or more edges downward and then at most one back edge)
parent [out] indicates the closest "parent" of a node
art_point [out] indicates if the node is an articulation point
Definition at line 168 of file bbssp.c.
References ARROW_SUCCESS, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_bbssp_biconnected().