Arrow: lib/tsp/tsp.c File Reference
lib/tsp/tsp.c File Reference
Wrapper for calling TSP solvers and heuristics.
#include "common.h"
#include "tsp.h"
Functions
int arrow_tsp_solve (int tsp_solver, arrow_problem *problem, void *params, arrow_tsp_result *result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
void arrow_tsp_short_name (int tsp_solver, FILE *out)
Prints out the short name for the given solver.
void arrow_tsp_long_name (int tsp_solver, FILE *out)
Prints out the long name for the given solver.
Detailed Description
Wrapper for calling TSP solvers and heuristics.
Wrapper for solvers and heuristics for the traveling salesman problem.
Author:
John LaRusic
Definition in file tsp.c.
Function Documentation
void arrow_tsp_long_name (int tsp_solver, FILE * out)
Prints out the long name for the given solver.
Parameters:
tsp_solver [in] the TSP solver in question
out [out] the file handle to print out to.
Definition at line 61 of file tsp.c.
References arrow_print_error, ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, and ARROW_TSP_RAI.
Referenced by arrow_btsp_result_print_pretty().
void arrow_tsp_short_name (int tsp_solver, FILE * out)
Prints out the short name for the given solver.
Parameters:
tsp_solver [in] the TSP solver in question
out [out] the file handle to print out to.
Definition at line 45 of file tsp.c.
References arrow_print_error, ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, and ARROW_TSP_RAI.
Referenced by arrow_btsp_result_print_xml().
int arrow_tsp_solve (int tsp_solver, arrow_problem * problem, void * params, arrow_tsp_result * result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Solves TSP with for requested TSP solver.
Parameters:
tsp_solver [in] the TSP solver to use
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 20 of file tsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_TSP_CC_EXACT, arrow_tsp_cc_exact_solve(), ARROW_TSP_CC_LK, arrow_tsp_cc_lk_solve(), ARROW_TSP_RAI, and arrow_tsp_rai_solve().
Referenced by feasible().