Arrow: lib/btsp.c File Reference
lib/btsp.c File Reference
Bottleneck traveling salesman problem (BTSP) methods.
#include "arrow.h"
Functions
int feasible (arrow_problem *problem, int num_steps, arrow_btsp_solve_plan *steps, int delta, int *tour_exists, arrow_btsp_result *result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using costs <= delta.
int arrow_btsp_result_init (arrow_problem *problem, arrow_btsp_result *result)
Initializes the BTSP result structure.
void arrow_btsp_result_destruct (arrow_btsp_result *result)
Destructs a BTSP result structure.
void arrow_btsp_params_init (arrow_btsp_params *params)
Inititalizes BTSP parameter structure.
void arrow_btsp_params_destruct (arrow_btsp_params *params)
Destructs a BTSP parameters structure.
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan *plan)
Inititalizes BTSP solve plan structure.
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan *plan)
Destructs a BTSP solve plan structure.
int arrow_btsp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, arrow_btsp_result *result)
Solves TSP with Concorde's exact solver.
Detailed Description
Bottleneck traveling salesman problem (BTSP) methods.
Heuristic for solving the bottleneck traveling salesman problem (BTSP).
Author:
John LaRusic
Definition in file btsp.c.
Function Documentation
void arrow_btsp_params_destruct (arrow_btsp_params * params)
Destructs a BTSP parameters structure.
Parameters:
params [out] BTSP parameters structure
Definition at line 71 of file btsp.c.
References arrow_btsp_solve_plan_destruct(), arrow_btsp_params::num_steps, and arrow_btsp_params::steps.
Referenced by main().
void arrow_btsp_params_init (arrow_btsp_params * params)
Inititalizes BTSP parameter structure.
Parameters:
params [out] BTSP parameters structure
Definition at line 60 of file btsp.c.
References ARROW_FALSE, arrow_btsp_params::confirm_sol, arrow_btsp_params::find_short_tour, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_params::supress_ebst, and arrow_btsp_params::upper_bound.
Referenced by main().
void arrow_btsp_result_destruct (arrow_btsp_result * result)
Destructs a BTSP result structure.
Parameters:
result [out] BTSP result structure
Definition at line 53 of file btsp.c.
References arrow_btsp_result::tour.
Referenced by arrow_btsp_solve(), and main().
int arrow_btsp_result_init (arrow_problem * problem, arrow_btsp_result * result)
Initializes the BTSP result structure.
Parameters:
problem [in] problem to solve
result [out] BTSP result structure
Definition at line 33 of file btsp.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_btsp_result::bin_search_steps, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, arrow_btsp_result::found_tour, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_result::obj_value, arrow_problem::size, arrow_btsp_result::total_time, arrow_btsp_result::tour, and arrow_btsp_result::tour_length.
Referenced by arrow_btsp_solve(), and main().
int arrow_btsp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, arrow_btsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
info [in] extra problem info
params [in] parameters for solver (can be NULL)
result [out] BTSP solution
Definition at line 98 of file btsp.c.
References arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_binary_search(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, feasible(), arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_params::steps, arrow_btsp_params::supress_ebst, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, upper_bound, and arrow_btsp_params::upper_bound.
Referenced by main().
void arrow_btsp_solve_plan_destruct (arrow_btsp_solve_plan * plan)
Destructs a BTSP solve plan structure.
Parameters:
plan [out] BTSP solve plan structure
Definition at line 91 of file btsp.c.
References arrow_btsp_fun_destruct(), arrow_tsp_lk_params_destruct(), arrow_btsp_solve_plan::fun, and arrow_btsp_solve_plan::lk_params.
Referenced by arrow_btsp_params_destruct().
void arrow_btsp_solve_plan_init (arrow_btsp_solve_plan * plan)
Inititalizes BTSP solve plan structure.
Parameters:
plan [out] BTSP solve plan structure
Definition at line 84 of file btsp.c.
References arrow_btsp_solve_plan::attempts, and arrow_btsp_solve_plan::plan_type.
int feasible (arrow_problem * problem, int num_steps, arrow_btsp_solve_plan * steps, int delta, int * tour_exists, arrow_btsp_result * result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using costs <= delta.
Parameters:
problem [in] problem to solve
num_steps [in] total number of steps in solve plan
steps [in] solve plan step details
delta [in] delta parameter for feasibility problem.
tour_exists [out] true if a feasible tour exists, false otherwise
result [out] resulting BTSP tour found
Definition at line 275 of file btsp.c.
References arrow_btsp_fun_apply(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_problem_destruct(), ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_exact_solve(), arrow_tsp_lk_solve(), arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_btsp_solve_plan::attempts, arrow_btsp_result::exact_attempts, arrow_btsp_result::exact_time, arrow_btsp_fun::feasible, arrow_btsp_result::found_tour, arrow_btsp_solve_plan::fun, arrow_problem::get_cost, arrow_btsp_result::linkern_attempts, arrow_btsp_result::linkern_time, arrow_btsp_solve_plan::lk_params, arrow_tsp_result::obj_value, arrow_btsp_result::obj_value, arrow_btsp_solve_plan::plan_type, arrow_problem::size, arrow_tsp_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_tsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_solve_plan::upper_bound_update, and arrow_btsp_solve_plan::use_exact_solver.
Referenced by arrow_btsp_solve().