Arrow: lib/baltsp/baltsp-db.c File Reference
lib/baltsp/baltsp-db.c File Reference
Balanced traveling salesman problem iterative bottleneck algorithm.
#include "common.h"
#include "lb.h"
#include "btsp.h"
#include "baltsp.h"
Functions
int btsp_lower_bound (arrow_problem *problem, arrow_problem_info *info, int *lower_bound)
Calculates the best BTSP lower bound.
int btsp_bounds (arrow_problem *problem, arrow_problem_info *info, int *max_index, int *btsp_lbs, int *best_gap, int *best_low, int *best_high, double *total_time)
Calculates BTSP lower bounds for each unique cost.
int baltsp_bounds_tree (arrow_problem_info *info, int *btsp_lbs, int max_index, arrow_bintree *tree)
Calculates a sorted tree of unique BalTSP lower bounds.
int fill_tiers (arrow_problem_info *info, int *btsp_lbs, int max_index, int *baltsp_lb, int num_baltsp_lbs, arrow_llist *tiers)
Fills the tiers of linked lists corresponding to BalTSP lower bounds.
int init_tiers (int num_tiers, arrow_llist **tiers)
Initializes tiers.
void destruct_tiers (int num_tiers, arrow_llist **tiers)
Destructs tiers.
int find_cost_order (arrow_problem_info *info, int max_index, int *btsp_lbs, int *cost_order)
Fills cost_order with a good order for processing them with the IB-algorithm.
int arrow_balanced_tsp_db (arrow_problem *btsp_problem, arrow_problem *mstsp_problem, arrow_problem_info *info, arrow_baltsp_params *params, arrow_btsp_params *btsp_params, double *lb_time, arrow_btsp_result *tour_result)
Detailed Description
Balanced traveling salesman problem iterative bottleneck algorithm.
Heuristic for solving the balanced traveling salesman problem iterative bottleneck algorithm (BalTSP IB-Algorithm).
Author:
John LaRusic
Definition in file baltsp-db.c.
Function Documentation
int arrow_balanced_tsp_db (arrow_problem * btsp_problem, arrow_problem * mstsp_problem, arrow_problem_info * info, arrow_baltsp_params * params, arrow_btsp_params * btsp_params, double * lb_time, arrow_btsp_result * tour_result)
Definition at line 100 of file baltsp-db.c.
References arrow_baltsp_fun_ib(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_btsp_solve(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, btsp_lower_bound(), arrow_baltsp_params::btsp_max_cost, arrow_baltsp_params::btsp_min_cost, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_result::found_tour, arrow_btsp_params::infinity, arrow_btsp_params::lower_bound, arrow_baltsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_baltsp_params::mstsp_min_cost, arrow_baltsp_params::num_steps, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_problem::symmetric, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_params::upper_bound, and arrow_baltsp_params::with_improvements.
Referenced by main().
int baltsp_bounds_tree (arrow_problem_info * info, int * btsp_lbs, int max_index, arrow_bintree * tree)
Calculates a sorted tree of unique BalTSP lower bounds.
Parameters:
info [in] problem info
btsp_lbs [out] array of BTSP bounds for each cost
max_index [in] largest index to bother searching
tree [out] sorted tree of unique BalTSP lower bounds
Definition at line 547 of file baltsp-db.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, and arrow_problem_info::cost_list.
Referenced by find_cost_order().
int btsp_bounds (arrow_problem * problem, arrow_problem_info * info, int * max_index, int * btsp_lbs, int * best_gap, int * best_low, int * best_high, double * total_time)
Calculates BTSP lower bounds for each unique cost.
Parameters:
problem [in] problem structure
info [in] problem info
max_index [in/out] largest index to bother searching (can change if lower bounds infeasible for some value)
btsp_lbs [out] array of BTSP bounds for each cost
best_gap [out] smallest gap bound calculated
best_low [out] lower cost value for the best gap bound
best_high [out] upper cost value for the best gap bound
total_time [out] total time spent calculating lower bound values
Definition at line 468 of file baltsp-db.c.
References arrow_baltsp_fun_ib(), arrow_btsp_fun_apply(), arrow_btsp_fun_destruct(), arrow_debug, ARROW_FAILURE, arrow_print_error, arrow_problem_destruct(), ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), btsp_lower_bound(), arrow_problem_info::cost_list, and arrow_problem_info::max_cost.
Referenced by arrow_balanced_tsp_ib().
int btsp_lower_bound (arrow_problem * problem, arrow_problem_info * info, int * lower_bound)
Calculates the best BTSP lower bound.
Parameters:
problem [in] problem structure
lower_bound [out] the best lower bound value
Definition at line 452 of file baltsp-db.c.
References arrow_bbssp_solve(), arrow_debug, ARROW_FAILURE, ARROW_SUCCESS, and arrow_bound_result::obj_value.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), and btsp_bounds().
void destruct_tiers (int num_tiers, arrow_llist ** tiers)
Destructs tiers.
Parameters:
num_tiers [in] number of tiers to destroy
tiers [out] array of linked lists to destroy
Definition at line 626 of file baltsp-db.c.
References arrow_llist_destruct().
Referenced by find_cost_order().
int fill_tiers (arrow_problem_info * info, int * btsp_lbs, int max_index, int * baltsp_lb, int num_baltsp_lbs, arrow_llist * tiers)
Fills the tiers of linked lists corresponding to BalTSP lower bounds.
Parameters:
info [in] problem info
btsp_lbs [out] array of BTSP bounds for each cost
max_index [in] largest index to bother searching
baltsp_lbs [in] array of BalTSP lower bounds
num_baltsp_lbs [in] size of baltsp_lbs array
tiers [out] array of linked lists to be filled
Definition at line 568 of file baltsp-db.c.
References arrow_hash_cost_list(), arrow_hash_destruct(), arrow_hash_search(), arrow_llist_insert_tail(), arrow_print_error, ARROW_SUCCESS, and arrow_problem_info::cost_list.
Referenced by find_cost_order().
int find_cost_order (arrow_problem_info * info, int max_index, int * btsp_lbs, int * cost_order)
Fills cost_order with a good order for processing them with the IB-algorithm.
Parameters:
info [in] problem info
max_index [in] largest index to bother searching
btsp_lbs [in] array of BTSP bounds for each cost
cost_order [out] specifically ordered array of costs
Definition at line 643 of file baltsp-db.c.
References arrow_bintree_destruct(), arrow_bintree_to_array(), ARROW_FAILURE, arrow_llist_remove_head(), arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), baltsp_bounds_tree(), destruct_tiers(), fill_tiers(), init_tiers(), arrow_llist::size, and arrow_bintree::size.
Referenced by arrow_balanced_tsp_ib().
int init_tiers (int num_tiers, arrow_llist ** tiers)
Initializes tiers.
Parameters:
num_tiers [in] number of tiers to create
tiers [out] array of linked lists to create
Definition at line 602 of file baltsp-db.c.
References ARROW_FAILURE, arrow_llist_init(), arrow_print_error, and ARROW_SUCCESS.
Referenced by find_cost_order().