Arrow: lib/lb/cbst.c File Reference
lib/lb/cbst.c File Reference
Constrained bottleneck spanning tree bound implemenation.
#include "common.h"
#include "lb.h"
Functions
int init_data (int n, arrow_heap *heap, int **cur_tree, int **in_heap, int **d)
void destroy_data (arrow_heap *heap, int **cur_tree, int **in_heap, int **d)
void min_span_tree (arrow_problem *problem, int C, int exclude_cost, int *cur_tree, int *tree, int *max_cost, double *length, arrow_heap *heap, int *in_heap, int *d)
Solves a (slightly modified!) minimum spanning tree problem.
int arrow_cbst_solve (arrow_problem *problem, arrow_problem_info *info, double max_length, arrow_bound_result *result)
Constrained bottleneck spanning tree (CBST) solver.
int arrow_cbst_mst_solve (arrow_problem *problem, arrow_problem_info *info, int *tree, int *max_cost, double *length)
Minimum spanning tree (MST) solver.
Detailed Description
Constrained bottleneck spanning tree bound implemenation.
Implemenation of the Constrained bottleneck spanning tree (CBST) bound used as a lower bound for the symmetric constrained bottleneck TSP objective value.
Author:
John LaRusic
Definition in file cbst.c.
Function Documentation
int arrow_cbst_mst_solve (arrow_problem * problem, arrow_problem_info * info, int * tree, int * max_cost, double * length)
Minimum spanning tree (MST) solver.
Parameters:
problem [in] problem data
info [in] problem info data
tree [out] MST tree (tree[i] gives precessor for node i)
max_cost [out] the largest cost in the tree
length [out] the length of all edges in the tree
Definition at line 96 of file cbst.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, destroy_data(), init_data(), arrow_problem_info::max_cost, min_span_tree(), and arrow_problem::size.
int arrow_cbst_solve (arrow_problem * problem, arrow_problem_info * info, double max_length, arrow_bound_result * result)
Constrained bottleneck spanning tree (CBST) solver.
Parameters:
problem [in] problem data
info [in] problem info data
max_length [in] maximum spanning tree length
result [out] bound result
Definition at line 46 of file cbst.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_zeit(), init_data(), length, arrow_problem_info::max_cost, min_span_tree(), arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
void destroy_data (arrow_heap * heap, int ** cur_tree, int ** in_heap, int ** d)
Definition at line 226 of file cbst.c.
References arrow_heap_destruct().
Referenced by arrow_cbst_mst_solve(), and init_data().
int init_data (int n, arrow_heap * heap, int ** cur_tree, int ** in_heap, int ** d)
Definition at line 197 of file cbst.c.
References ARROW_FAILURE, arrow_heap_init(), ARROW_SUCCESS, arrow_util_create_int_array(), and destroy_data().
void min_span_tree (arrow_problem * problem, int C, int exclude_cost, int * cur_tree, int * tree, int * max_cost, double * length, arrow_heap * heap, int * in_heap, int * d)
Solves a (slightly modified!) minimum spanning tree problem.
Parameters:
problem [in] problem structure
C [in] largest cost in problem
exclude_cost [in] excludes costs less than this value except...
cur_tree [in] includes any edge costs found in this tree
tree [out] the resulting minimum spanning tree
max_cost [out] the largest cost in the resulting tree
length [out] the total length of the resulting tree
heap [out] a temporary heap structure
in_heap [out] a temporary integer array
d [out] a temporary integer array
Definition at line 123 of file cbst.c.
References arrow_heap_change_key(), arrow_heap_delete_min(), arrow_heap_empty(), arrow_heap_get_min(), arrow_heap_insert(), arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_cbst_mst_solve(), and arrow_cbst_solve().