Arrow: lib/bscssp.c File Reference
lib/bscssp.c File Reference
Bottleneck strongly connected spanning subgraph problem implemenation.
#include "arrow.h"
Functions
int strongly_connected (arrow_problem *problem, int delta, int *result)
Determines if the given graph is strongly connected.
void strongly_connected_dfs (arrow_problem *problem, int delta, int i, int transpose, int *visited)
Performs a recursive depth-first search to test for connectivity.
int arrow_bscssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
Detailed Description
Bottleneck strongly connected spanning subgraph problem implemenation.
Implemenation of the bottleneck strongly connected spanning subgraph problem (BSCSSP) that's used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file bscssp.c.
Function Documentation
int arrow_bscssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BSCSSP solution
Definition at line 43 of file bscssp.c.
References ARROW_ERROR_FATAL, ARROW_FAILURE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, strongly_connected(), and arrow_bound_result::total_time.
Referenced by main().
int strongly_connected (arrow_problem * problem, int delta, int * result)
Determines if the given graph is strongly connected.
Parameters:
problem [in] the problem instance
delta [in] delta parameter
result [out] the result!
Definition at line 86 of file bscssp.c.
References ARROW_ERROR_FATAL, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_problem::size, and strongly_connected_dfs().
Referenced by arrow_bscssp_solve().
void strongly_connected_dfs (arrow_problem * problem, int delta, int i, int transpose, int * visited)
Performs a recursive depth-first search to test for connectivity.
Parameters:
problem [in] the problem instance
delta [in] delta parameter
i [in] node index to search from
transpose [in] if true, calculates costs with transposed cost matrix
visited [out] array that marks nodes that have been visited
Definition at line 133 of file bscssp.c.
References ARROW_TRUE, arrow_problem::get_cost, and arrow_problem::size.
Referenced by strongly_connected().