Arrow: lib/lb/dcbpb.c File Reference
lib/lb/dcbpb.c File Reference
Degree constarined bottleneck paths bound.
#include "common.h"
#include "lb.h"
Functions
void bottleneck_paths (arrow_problem *problem, int ignore, int **b)
Solves the all-pairs bottleneck paths problem (a simple modification of the Floyd-Warshall alg for all-pairs shortest paths).
int max (int i, int j, int k, int l)
int arrow_dcbpb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the degree constrained bottleneck paths bound (DCBPB).
Detailed Description
Degree constarined bottleneck paths bound.
Implemenation of the degree constrained bottleneck paths bound (DCBPB) used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file dcbpb.c.
Function Documentation
int arrow_dcbpb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the degree constrained bottleneck paths bound (DCBPB).
Parameters:
problem [in] problem data
result [out] BPB solution
Definition at line 40 of file dcbpb.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_create_int_matrix(), arrow_util_zeit(), bottleneck_paths(), arrow_problem::get_cost, max(), arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
void bottleneck_paths (arrow_problem * problem, int ignore, int ** b)
Solves the all-pairs bottleneck paths problem (a simple modification of the Floyd-Warshall alg for all-pairs shortest paths).
Parameters:
problem [in] problem data
ignore [in] vertex number to ignore
b [out] array will hold bottleneck path value for each pair of source/sink nodes
Definition at line 179 of file dcbpb.c.
References arrow_problem::get_cost, max(), and arrow_problem::size.
Referenced by arrow_dcbpb_solve().
int max (int i, int j, int k, int l)
Definition at line 216 of file dcbpb.c.
Referenced by arrow_2mb_solve(), arrow_dcbpb_solve(), bottleneck_paths(), max2(), and max3().