Arrow: lib/common/hash.c File Reference
lib/common/hash.c File Reference
Minimal perfect hashing functions.
#include "common.h"
Functions
int arrow_hash_cost_list (int *cost_list, int cost_list_length, arrow_hash *hash)
Creates a hash table from a list of unique costs.
void arrow_hash_destruct (arrow_hash *hash)
Destructs a hashtable data structure.
unsigned int arrow_hash_search (arrow_hash *hash, int key)
Finds id associated with key in hashtable.
Detailed Description
Minimal perfect hashing functions.
Methods for generating a minimal perfect hash.
Author:
John LaRusic
Definition in file hash.c.
Function Documentation
int arrow_hash_cost_list (int * cost_list, int cost_list_length, arrow_hash * hash)
Creates a hash table from a list of unique costs.
Parameters:
cost_list [in] list of costs
cost_list_length [in] length of cost list
hash [out] hashtable data structure
Definition at line 12 of file hash.c.
References ARROW_HASH_BUFFER_LENGTH, ARROW_SUCCESS, arrow_hash::data, arrow_hash::num_keys, arrow_hash::source, arrow_hash::vector, and arrow_hash::vector_space.
Referenced by arrow_problem_info_get().
void arrow_hash_destruct (arrow_hash * hash)
Destructs a hashtable data structure.
Parameters:
hash [out] hashtable data structure
Definition at line 40 of file hash.c.
References arrow_hash::data, arrow_hash::num_keys, arrow_hash::source, arrow_hash::vector, and arrow_hash::vector_space.
Referenced by arrow_problem_info_destruct().
unsigned int arrow_hash_search (arrow_hash * hash, int key)
Finds id associated with key in hashtable.
Parameters:
hash [in] hash table data structure
key [in] key to look up
Returns:
the id of the associated key
Definition at line 50 of file hash.c.
References ARROW_HASH_BUFFER_LENGTH, and arrow_hash::data.
Referenced by arrow_problem_info_cost_index(), and main().