Arrow: lib/lb/2mb.c File Reference
lib/lb/2mb.c File Reference
2-max bound implemenation.
#include "common.h"
#include "lb.h"
Functions
int arrow_2mb_solve (arrow_problem *problem, arrow_bound_result *result)
Solves the 2-max bound (2MB) on the given problem.
Detailed Description
2-max bound implemenation.
Implemenation of the 2-max bound (2MB) used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file 2mb.c.
Function Documentation
int arrow_2mb_solve (arrow_problem * problem, arrow_bound_result * result)
Solves the 2-max bound (2MB) on the given problem.
Parameters:
problem [in] problem data
result [out] 2MB solution
Definition at line 17 of file 2mb.c.
References ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::get_cost, max(), arrow_bound_result::obj_value, arrow_problem::size, arrow_problem::symmetric, and arrow_bound_result::total_time.
Referenced by main().