Arrow: lib/bap.c File Reference
lib/bap.c File Reference
Bottleneck assignment problem (BAP) implemenation.
#include "arrow.h"
Functions
void initialize_flow_data (arrow_problem *problem, int delta, int s, int t, int **res, int *m, int *dist, int *pred)
void shortest_augmenting_path (int n, int s, int t, int stop, int **res, int *dist, int *pred, int *flow)
void ford_fulkerson_labeling (int n, int s, int t, int **res, int *label, int *pred, int *flow, int *list)
int arrow_bap_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Detailed Description
Bottleneck assignment problem (BAP) implemenation.
Implemenation of the bottleneck assignment problem (BAP) that's used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file bap.c.
Function Documentation
int arrow_bap_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Definition at line 67 of file bap.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_create_int_matrix(), arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, ford_fulkerson_labeling(), initialize_flow_data(), arrow_bound_result::obj_value, shortest_augmenting_path(), arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
void ford_fulkerson_labeling (int n, int s, int t, int ** res, int * label, int * pred, int * flow, int * list)
Definition at line 251 of file bap.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_bap_solve().
void initialize_flow_data (arrow_problem * problem, int delta, int s, int t, int ** res, int * m, int * dist, int * pred)
Definition at line 152 of file bap.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_bap_solve().
void shortest_augmenting_path (int n, int s, int t, int stop, int ** res, int * dist, int * pred, int * flow)
Definition at line 193 of file bap.c.
References ARROW_FALSE, ARROW_SUCCESS, and ARROW_TRUE.
Referenced by arrow_bap_solve().