Arrow: lib/lb/bap.c File Reference
lib/lb/bap.c File Reference
Bottleneck assignment problem (BAP) implemenation.
#include "common.h"
#include "lb.h"
Functions
void initialize_flow_data (arrow_problem *problem, int min_cost, int max_cost, int s, int t, int **res, int *m, int *dist, int *pred)
void shortest_augmenting_path (int n, int s, int t, int stop, int **res, int *dist, int *pred, int *flow)
void ford_fulkerson_labeling (int n, int s, int t, int **res, int *label, int *pred, int *flow, int *list)
int arrow_bap_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck assignment problem (BAP).
int arrow_bap_has_assignment (arrow_problem *problem, int min_cost, int max_cost, int *result)
Determines if the problem has an assignment using only costs min_cost <= c_ij <= max_cost.
Detailed Description
Bottleneck assignment problem (BAP) implemenation.
Implemenation of the bottleneck assignment problem (BAP) that's used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file bap.c.
Function Documentation
int arrow_bap_has_assignment (arrow_problem * problem, int min_cost, int max_cost, int * result)
Determines if the problem has an assignment using only costs min_cost <= c_ij <= max_cost.
Parameters:
problem [in] problem data
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
result [out] ARROW_TRUE if an assignment is possible.
Definition at line 178 of file bap.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_create_int_matrix(), ford_fulkerson_labeling(), initialize_flow_data(), shortest_augmenting_path(), and arrow_problem::size.
Referenced by balanced_lb_feasible(), and dt2_lb_feasible().
int arrow_bap_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck assignment problem (BAP).
Parameters:
problem [in] problem data
info [in] problem info
result [out] BBSSP solution
Definition at line 70 of file bap.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_create_int_matrix(), arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, delta, ford_fulkerson_labeling(), initialize_flow_data(), arrow_bound_result::obj_value, shortest_augmenting_path(), arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
void ford_fulkerson_labeling (int n, int s, int t, int ** res, int * label, int * pred, int * flow, int * list)
Definition at line 367 of file bap.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_bap_has_assignment(), and arrow_bap_solve().
void initialize_flow_data (arrow_problem * problem, int min_cost, int max_cost, int s, int t, int ** res, int * m, int * dist, int * pred)
Definition at line 247 of file bap.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_bap_has_assignment(), and arrow_bap_solve().
void shortest_augmenting_path (int n, int s, int t, int stop, int ** res, int * dist, int * pred, int * flow)
Definition at line 297 of file bap.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by arrow_bap_has_assignment(), and arrow_bap_solve().