Arrow: lib/lb/cbap.c File Reference
lib/lb/cbap.c File Reference
Contrained bottleneck assignment problem algorithm.
#include "common.h"
#include "lb.h"
Functions
int init_data (int n, int **x, int **y, int **pi, int **d, int **pred, int **label, arrow_heap *heap)
void destruct_data (int **x, int **y, int **pi, int **d, int **pred, int **label, arrow_heap *heap)
double lap (arrow_problem *problem, int delta, int *x, int *y, int *pi, int *d, int *pred, int *label, arrow_heap *heap)
void dijkstra (arrow_problem *problem, int delta, int *x, int *y, int *pi, int s, int *t, int *d, int *pred, int *label, arrow_heap *heap)
void augment (arrow_problem *problem, int s, int t, int *pred, int *x, int *y)
int arrow_cbap_solve (arrow_problem *problem, arrow_problem_info *info, double max_length, arrow_bound_result *result)
Solves the constrained bottleneck assignment problem (CBAP).
int arrow_cbap_lap (arrow_problem *problem, double *result)
Solves the linear assignment problem (LAP).
Detailed Description
Contrained bottleneck assignment problem algorithm.
Implemenation of the contrained bottleneck assignment problem (CBAP) that's used as a lower bound for the contrained BTSP objective value.
NOTE: This code is an almost verbatim copy of C++ code written by Jonker (a copy may be found at http://www.magiclogic.com/assignment.html). The code will not compile along side Concorde, and requires a full cost matrix (which we need to avoid for large problems). Therefore, the best option was to implement a C version using our problem data structure.
This code is explained in the paper: "A Shortest Augmenting Path Algorithm for Dense and Sparse Linear Assignment Problems," Computing 38, 325-340, 1987 by R. Jonker and A. Volgenant, University of Amsterdam.
Author:
John LaRusic
Definition in file cbap.c.
Function Documentation
int arrow_cbap_lap (arrow_problem * problem, double * result)
Solves the linear assignment problem (LAP).
Parameters:
problem [in] problem data
result [out] LAP solution
Definition at line 124 of file cbap.c.
References ARROW_FAILURE, ARROW_SUCCESS, destruct_data(), init_data(), lap(), and arrow_problem::size.
int arrow_cbap_solve (arrow_problem * problem, arrow_problem_info * info, double max_length, arrow_bound_result * result)
Solves the constrained bottleneck assignment problem (CBAP).
Parameters:
problem [in] problem data
info [in] problem info
max_length [in] the maximum length of the assignment
result [out] CBAP solution
Definition at line 51 of file cbap.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, arrow_util_binary_search(), arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, delta, destruct_data(), arrow_problem::get_cost, init_data(), lap(), length, arrow_bound_result::obj_value, arrow_problem::size, and arrow_bound_result::total_time.
Referenced by main().
void augment (arrow_problem * problem, int s, int t, int * pred, int * x, int * y)
Definition at line 327 of file cbap.c.
Referenced by lap().
void destruct_data (int ** x, int ** y, int ** pi, int ** d, int ** pred, int ** label, arrow_heap * heap)
Definition at line 175 of file cbap.c.
References arrow_heap_destruct().
Referenced by arrow_cbap_lap(), arrow_cbap_solve(), and init_data().
void dijkstra (arrow_problem * problem, int delta, int * x, int * y, int * pi, int s, int * t, int * d, int * pred, int * label, arrow_heap * heap)
Definition at line 232 of file cbap.c.
References arrow_heap_change_key(), arrow_heap_delete_min(), arrow_heap_empty(), arrow_heap_get_min(), arrow_heap_in(), arrow_heap_insert(), arrow_print_error, arrow_problem::get_cost, arrow_heap::size, arrow_problem::size, and start.
Referenced by lap().
int init_data (int n, int ** x, int ** y, int ** pi, int ** d, int ** pred, int ** label, arrow_heap * heap)
Definition at line 149 of file cbap.c.
References ARROW_FAILURE, arrow_heap_init(), ARROW_SUCCESS, arrow_util_create_int_array(), and destruct_data().
Referenced by arrow_cbap_lap(), arrow_cbap_solve(), arrow_cbst_mst_solve(), and arrow_cbst_solve().
double lap (arrow_problem * problem, int delta, int * x, int * y, int * pi, int * d, int * pred, int * label, arrow_heap * heap)
Definition at line 188 of file cbap.c.
References augment(), dijkstra(), arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_cbap_lap(), and arrow_cbap_solve().