Arrow: lib/baltsp/baltsp-dt.c File Reference
lib/baltsp/baltsp-dt.c File Reference
Balanced traveling salesman problem double threshold algorithm.
#include "common.h"
#include "lb.h"
#include "btsp.h"
#include "baltsp.h"
Functions
int balanced_lb_feasible (arrow_problem *problem, int min_cost, int max_cost, int *is_feasible)
Determines if a tour is feasible given min/max costs based upon lower bounds for the BTSP.
int arrow_balanced_tsp_dt (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, int lb_only, int with_improvements, arrow_bound_result *lb_result, arrow_btsp_result *tour_result)
Detailed Description
Balanced traveling salesman problem double threshold algorithm.
Heuristic for solving the balanced traveling salesman problem double threshold algorithm (BalTSP DT-Algorithm).
Author:
John LaRusic
Definition in file baltsp-dt.c.
Function Documentation
int arrow_balanced_tsp_dt (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, int lb_only, int with_improvements, arrow_bound_result * lb_result, arrow_btsp_result * tour_result)
Definition at line 35 of file baltsp-dt.c.
References arrow_btsp_feasible(), arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, arrow_problem_abtsp_to_sbtsp(), arrow_problem_destruct(), arrow_problem_info_cost_index(), ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_SOLVER_COUNT, arrow_util_sbtsp_to_abstp_tour(), arrow_util_zeit(), balanced_lb_feasible(), arrow_btsp_result::bin_search_steps, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_btsp_params::deep_copy, arrow_btsp_result::found_tour, arrow_btsp_params::infinity, arrow_btsp_params::lower_bound, max(), arrow_btsp_result::max_cost, arrow_problem_info::max_cost, arrow_btsp_result::min_cost, arrow_btsp_params::num_steps, arrow_bound_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_params::steps, arrow_problem::symmetric, arrow_bound_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, and arrow_btsp_params::upper_bound.
Referenced by main().
int balanced_lb_feasible (arrow_problem * problem, int min_cost, int max_cost, int * is_feasible)
Determines if a tour is feasible given min/max costs based upon lower bounds for the BTSP.
Parameters:
problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
is_feasible [out] ARROW_TRUE if tour feasibly could exist
Definition at line 264 of file baltsp-dt.c.
References arrow_bap_has_assignment(), arrow_bbssp_biconnected(), arrow_bscssp_connected(), ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, and arrow_problem::symmetric.
Referenced by arrow_balanced_tsp_dt().