Arrow: lib/btsp/btsp.c File Reference
lib/btsp/btsp.c File Reference
Bottleneck traveling salesman problem (BTSP) methods.
#include "common.h"
#include "btsp.h"
Functions
int feasible (arrow_problem *problem, int num_steps, arrow_btsp_solve_plan *steps, int delta, int *feasible, arrow_btsp_result *result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using costs <= delta.
int arrow_btsp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_btsp_params *params, arrow_btsp_result *result)
Solves TSP with Concorde's exact solver.
Detailed Description
Bottleneck traveling salesman problem (BTSP) methods.
Heuristic for solving the bottleneck traveling salesman problem (BTSP).
Author:
John LaRusic
Definition in file btsp.c.
Function Documentation
int arrow_btsp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_btsp_params * params, arrow_btsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
info [in] extra problem info
params [in] parameters for solver (can be NULL)
result [out] BTSP solution
Definition at line 34 of file btsp.c.
References arrow_btsp_result_destruct(), arrow_btsp_result_init(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, ARROW_TSP_CC_EXACT, ARROW_TSP_SOLVER_COUNT, arrow_util_binary_search(), arrow_util_zeit(), arrow_btsp_result::bin_search_steps, arrow_btsp_params::confirm_plan, arrow_btsp_params::confirm_sol, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, feasible(), arrow_btsp_params::find_short_tour, arrow_btsp_result::found_tour, arrow_btsp_params::lower_bound, arrow_btsp_params::num_steps, arrow_btsp_result::obj_value, arrow_btsp_result::optimal, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_btsp_params::steps, arrow_btsp_params::supress_ebst, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_btsp_result::tour_length, upper_bound, and arrow_btsp_params::upper_bound.
Referenced by main().
int feasible (arrow_problem * problem, int num_steps, arrow_btsp_solve_plan * steps, int delta, int * feasible, arrow_btsp_result * result)
Solves the feasibility problem which attempts to determine if there is a Hamiltonian cycle using costs <= delta.
Parameters:
problem [in] problem to solve
num_steps [in] total number of steps in solve plan
steps [in] solve plan step details
delta [in] delta parameter for feasibility problem.
feasible [out] true if a feasible tour exists, false otherwise
result [out] resulting BTSP tour found
TODO: Find a better way of doing this upper bound update
Definition at line 257 of file btsp.c.
References arrow_btsp_fun_apply(), arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_problem_destruct(), ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_tsp_solve(), ARROW_TSP_SOLVER_COUNT, arrow_btsp_solve_plan::attempts, arrow_btsp_fun::feasible, arrow_btsp_result::found_tour, arrow_btsp_solve_plan::fun, arrow_problem::get_cost, arrow_tsp_result::obj_value, arrow_btsp_result::obj_value, arrow_problem::size, arrow_btsp_result::solver_attempts, arrow_btsp_result::solver_time, arrow_tsp_result::total_time, arrow_btsp_result::total_time, arrow_btsp_result::tour, arrow_tsp_result::tour, arrow_btsp_result::tour_length, arrow_btsp_solve_plan::tsp_params, and arrow_btsp_solve_plan::tsp_solver.
Referenced by arrow_btsp_solve().