Arrow: lib/tsp.c File Reference
lib/tsp.c File Reference
TSP solver and Lin-Kernighan heuristic.
#include "arrow.h"
Functions
int build_initial_tour (arrow_problem *problem, CCedgegengroup *plan, CCrandstate *rstate, int *initial_tour)
int arrow_tsp_result_init (arrow_problem *problem, arrow_tsp_result *result)
Initializes the TSP result structure.
void arrow_tsp_result_destruct (arrow_tsp_result *result)
Destructs a TSP result structure.
void arrow_tsp_lk_params_init (arrow_problem *problem, arrow_tsp_lk_params *params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
void arrow_tsp_lk_params_destruct (arrow_tsp_lk_params *params)
Destructs a LK parameters structure.
int arrow_tsp_exact_solve (arrow_problem *problem, int *initial_tour, arrow_tsp_result *result)
Solves TSP with Concorde's exact solver.
int arrow_tsp_lk_solve (arrow_problem *problem, arrow_tsp_lk_params *params, arrow_tsp_result *result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Detailed Description
TSP solver and Lin-Kernighan heuristic.
Wrapper for calling Concorde's TSP solver and Lin-Kernighan heuristic.
Author:
John LaRusic
Definition in file tsp.c.
Function Documentation
int arrow_tsp_exact_solve (arrow_problem * problem, int * initial_tour, arrow_tsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
in_tour [in] an initial tour (can be NULL)
result [out] TSP solution
Definition at line 66 of file tsp.c.
References ARROW_FAILURE, ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::data, arrow_tsp_result::found_tour, arrow_problem::name, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
void arrow_tsp_lk_params_destruct (arrow_tsp_lk_params * params)
Destructs a LK parameters structure.
Parameters:
result [out] LK parameters structure
Definition at line 59 of file tsp.c.
References arrow_tsp_lk_params::initial_tour.
Referenced by arrow_btsp_solve_plan_destruct(), arrow_tsp_lk_solve(), and main().
void arrow_tsp_lk_params_init (arrow_problem * problem, arrow_tsp_lk_params * params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
Parameters:
problem [in] problem to solve
params [out] LK parameters structure
Definition at line 47 of file tsp.c.
References arrow_tsp_lk_params::initial_tour, arrow_tsp_lk_params::kick_type, arrow_tsp_lk_params::kicks, arrow_tsp_lk_params::length_bound, arrow_tsp_lk_params::random_restarts, arrow_problem::size, arrow_tsp_lk_params::stall_count, and arrow_tsp_lk_params::time_bound.
Referenced by arrow_tsp_lk_solve(), and main().
int arrow_tsp_lk_solve (arrow_problem * problem, arrow_tsp_lk_params * params, arrow_tsp_result * result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Parameters:
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 102 of file tsp.c.
References arrow_debug, ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_lk_params_destruct(), arrow_tsp_lk_params_init(), arrow_util_zeit(), build_initial_tour(), CONCORDE_FAILURE, arrow_problem::data, arrow_tsp_result::found_tour, arrow_tsp_lk_params::initial_tour, arrow_tsp_lk_params::kick_type, arrow_tsp_lk_params::kicks, arrow_tsp_lk_params::length_bound, arrow_tsp_result::obj_value, arrow_tsp_lk_params::random_restarts, arrow_problem::size, arrow_tsp_lk_params::stall_count, arrow_tsp_lk_params::time_bound, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
void arrow_tsp_result_destruct (arrow_tsp_result * result)
Destructs a TSP result structure.
Parameters:
result [out] TSP result structure
Definition at line 37 of file tsp.c.
References arrow_tsp_result::tour.
Referenced by feasible(), and main().
int arrow_tsp_result_init (arrow_problem * problem, arrow_tsp_result * result)
Initializes the TSP result structure.
Parameters:
problem [in] problem to solve
result [out] TSP result structure
Definition at line 23 of file tsp.c.
References ARROW_ERROR_FATAL, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_tsp_result::found_tour, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
int build_initial_tour (arrow_problem * problem, CCedgegengroup * plan, CCrandstate * rstate, int * initial_tour)
Definition at line 273 of file tsp.c.
References ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_SUCCESS, CONCORDE_FAILURE, arrow_problem::data, and arrow_problem::size.
Referenced by arrow_tsp_lk_solve().