Arrow: lib/lb/bscssp.c File Reference
lib/lb/bscssp.c File Reference
Bottleneck strongly connected spanning subgraph problem implemenation.
#include "common.h"
#include "lb.h"
Functions
void strongly_connected_dfs (arrow_problem *problem, int min_cost, int max_cost, int i, int transpose, int *visited)
Performs a recursive depth-first search to test for connectivity.
int arrow_bscssp_solve (arrow_problem *problem, arrow_problem_info *info, arrow_bound_result *result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
int arrow_bscssp_connected (arrow_problem *problem, int min_cost, int max_cost, int *result)
Determines if the problem is strongly connected using only costs min_cost <= c_ij <= max_cost.
Detailed Description
Bottleneck strongly connected spanning subgraph problem implemenation.
Implemenation of the bottleneck strongly connected spanning subgraph problem (BSCSSP) that's used as a lower bound for the Bottleneck TSP objective value.
Author:
John LaRusic
Definition in file bscssp.c.
Function Documentation
int arrow_bscssp_connected (arrow_problem * problem, int min_cost, int max_cost, int * result)
Determines if the problem is strongly connected using only costs min_cost <= c_ij <= max_cost.
Parameters:
problem [in] problem data
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
result [out] ARROW_TRUE if strongly connected
Definition at line 80 of file bscssp.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_problem::size, and strongly_connected_dfs().
Referenced by arrow_bscssp_solve(), balanced_lb_feasible(), and dt2_lb_feasible().
int arrow_bscssp_solve (arrow_problem * problem, arrow_problem_info * info, arrow_bound_result * result)
Solves the bottleneck strongly connected spanning subgraph problem (BSCSSP) on the given graph.
Parameters:
problem [in] problem data
info [in] problem info
result [out] BSCSSP solution
Definition at line 37 of file bscssp.c.
References arrow_bscssp_connected(), ARROW_FAILURE, ARROW_SUCCESS, ARROW_TRUE, arrow_util_zeit(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_bound_result::obj_value, and arrow_bound_result::total_time.
Referenced by main().
void strongly_connected_dfs (arrow_problem * problem, int min_cost, int max_cost, int i, int transpose, int * visited)
Performs a recursive depth-first search to test for connectivity.
Parameters:
problem [in] the problem instance
min_cost [in] minimum cost to consider in problem
max_cost [in] maximum cost to consider in problem
i [in] node index to search from
transpose [in] if true, calculates costs with transposed cost matrix
visited [out] array that marks nodes that have been visited
Definition at line 128 of file bscssp.c.
References ARROW_TRUE, arrow_problem::get_cost, and arrow_problem::size.
Referenced by arrow_bscssp_connected().