Arrow: bin/linkern.c File Reference
bin/linkern.c File Reference
Lin-Kernighan TSP heuristic.
#include "common.h"
#include "lb.h"
#include "tsp.h"
#include "btsp.h"
Functions
void print_help ()
Prints help/usage message.
void print_version ()
Prints version message.
void print_usage ()
Prints usage message.
void read_args (int argc, char *argv[])
Reads program arguments.
int main (int argc, char *argv[])
Variables
char * program_name
char * input_file
int random_restarts = -1
int stall_count = -1
int kicks = -1
Detailed Description
Lin-Kernighan TSP heuristic.
Runs the Lin-Kernighan TSP heuristic on the given input file. This is really nothing more than a wrapper to Concorde, and is for testing purposes only. Use Concorde's executable for access to solve options.
Author:
John LaRusic
Definition in file linkern.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 51 of file linkern.c.
References arrow_print_error, arrow_problem_destruct(), arrow_problem_read(), arrow_tsp_cc_lk_params_destruct(), arrow_tsp_cc_lk_params_init(), arrow_tsp_result_destruct(), arrow_tsp_result_init(), arrow_tsp_result::found_tour, input_file, arrow_tsp_cc_lk_params::kicks, kicks, arrow_tsp_result::obj_value, program_name, arrow_tsp_cc_lk_params::random_restarts, random_restarts, read_args(), arrow_tsp_cc_lk_params::stall_count, stall_count, and arrow_tsp_result::total_time.
void print_help ()
Prints help/usage message.
Definition at line 92 of file linkern.c.
References print_usage(), and program_name.
Referenced by arrow_options_parse(), and read_args().
void print_usage ()
Prints usage message.
Definition at line 122 of file linkern.c.
References program_name.
Referenced by arrow_options_parse(), print_help(), and read_args().
void print_version ()
Prints version message.
Definition at line 107 of file linkern.c.
References program_name.
Referenced by arrow_options_parse(), and read_args().
void read_args (int argc, char * argv[])
Reads program arguments.
Definition at line 128 of file linkern.c.
References arrow_print_error, input_file, kicks, print_help(), print_usage(), print_version(), random_restarts, and stall_count.
Referenced by main().
Variable Documentation
char* input_file
Given input TSPLIB file
Definition at line 42 of file linkern.c.
int kicks = -1
Definition at line 45 of file linkern.c.
char* program_name
Program name
Definition at line 41 of file linkern.c.
int random_restarts = -1
Definition at line 43 of file linkern.c.
int stall_count = -1
Definition at line 44 of file linkern.c.