Arrow: lib/common/llist.c File Reference
lib/common/llist.c File Reference
Linked list implementation.
#include "common.h"
Functions
int construct_item (arrow_llist_item **item, int value)
Constructs a new item structure with the given value.
void arrow_llist_init (arrow_llist *list)
Initializes a new linked list.
void arrow_llist_destruct (arrow_llist *list)
Destructs contents of a linked list.
void arrow_llist_swap (arrow_llist *a, arrow_llist *b)
Swaps the two given lists.
int arrow_llist_insert_head (arrow_llist *list, int value)
Inserts a new item at the head of the list.
int arrow_llist_insert_tail (arrow_llist *list, int value)
Inserts a new item at the tail of the list.
int arrow_llist_insert_after (arrow_llist *list, arrow_llist_item *item, int value)
Inserts a new item after the given item in the list. NOTE: procedure makes no attempt to verify given item is in the list!
void arrow_llist_remove_head (arrow_llist *list, int *value)
Removes the head item in the list.
void arrow_llist_remove_tail (arrow_llist *list, int *value)
Removes the tail item in the list. NOTE: O(n) procedure!
void arrow_llist_remove_after (arrow_llist *list, arrow_llist_item *item, int *value)
Removes the item after the given one in the list. NOTE: procedure makes no attempt to verify given item is in the list!
void arrow_llist_print (arrow_llist *list)
Prints a list of items in the list.
void arrow_llist_to_array (arrow_llist *list, int *array)
Copys data from linked list into array. Assume array is big enough to handle linked list!
Detailed Description
Linked list implementation.
Methods for working with a linked list structure.
Author:
John LaRusic
Definition in file llist.c.
Function Documentation
void arrow_llist_destruct (arrow_llist * list)
Destructs contents of a linked list.
Parameters:
list [out] list structure
Definition at line 31 of file llist.c.
References arrow_llist_remove_head(), and arrow_llist::size.
Referenced by arrow_tsp_rai_solve(), destruct_tiers(), and improve_tour().
void arrow_llist_init (arrow_llist * list)
Initializes a new linked list.
Parameters:
list [out] linked list structure
Definition at line 23 of file llist.c.
References arrow_llist::head, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_tsp_rai_solve(), and init_tiers().
int arrow_llist_insert_after (arrow_llist * list, arrow_llist_item * item, int value)
Inserts a new item after the given item in the list. NOTE: procedure makes no attempt to verify given item is in the list!
Parameters:
list [out] linked list structure
item [in] linked list item
value [in] value to insert
Definition at line 101 of file llist.c.
References ARROW_FAILURE, arrow_llist_insert_tail(), arrow_print_error, ARROW_SUCCESS, construct_item(), arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by construct_tour().
int arrow_llist_insert_head (arrow_llist * list, int value)
Inserts a new item at the head of the list.
Parameters:
list [out] linked list structure
value [in] value to insert
Definition at line 55 of file llist.c.
References ARROW_FAILURE, ARROW_SUCCESS, construct_item(), arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
int arrow_llist_insert_tail (arrow_llist * list, int value)
Inserts a new item at the tail of the list.
Parameters:
list [out] linked list structure
value [in] value to insert
Definition at line 78 of file llist.c.
References ARROW_FAILURE, ARROW_SUCCESS, construct_item(), arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_llist_insert_after(), arrow_tsp_rai_solve(), construct_tour(), fill_tiers(), and improve_tour().
void arrow_llist_print (arrow_llist * list)
Prints a list of items in the list.
Parameters:
list [in] linked list structure
Definition at line 201 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, and arrow_llist::size.
void arrow_llist_remove_after (arrow_llist * list, arrow_llist_item * item, int * value)
Removes the item after the given one in the list. NOTE: procedure makes no attempt to verify given item is in the list!
Parameters:
list [out] linked list structure
item [in] linked list item
value [out] value of removed item
Definition at line 179 of file llist.c.
References arrow_llist_remove_head(), arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
void arrow_llist_remove_head (arrow_llist * list, int * value)
Removes the head item in the list.
Parameters:
list [out] linked list structure
value [out] value of removed item
Definition at line 128 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
Referenced by arrow_llist_destruct(), arrow_llist_remove_after(), arrow_llist_remove_tail(), and find_cost_order().
void arrow_llist_remove_tail (arrow_llist * list, int * value)
Removes the tail item in the list. NOTE: O(n) procedure!
Parameters:
list [out] linked list structure
value [out] value of removed item
Definition at line 153 of file llist.c.
References arrow_llist_remove_head(), arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, arrow_llist::size, and arrow_llist::tail.
void arrow_llist_swap (arrow_llist * a, arrow_llist * b)
Swaps the two given lists.
Parameters:
a [out] the first list
b [out] the second list
Definition at line 39 of file llist.c.
References arrow_llist::head, arrow_llist::size, and arrow_llist::tail.
Referenced by improve_tour().
void arrow_llist_to_array (arrow_llist * list, int * array)
Copys data from linked list into array. Assume array is big enough to handle linked list!
Parameters:
list [in] linked list structure
array [out] array to copy items into
Definition at line 214 of file llist.c.
References arrow_llist_item::data, arrow_llist::head, and arrow_llist_item::next.
Referenced by arrow_tsp_rai_solve().
int construct_item (arrow_llist_item ** item, int value)
Constructs a new item structure with the given value.
Parameters:
item [out] pointer to item structure
value [in] value to assign to new item
Definition at line 231 of file llist.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_llist_insert_after(), arrow_llist_insert_head(), and arrow_llist_insert_tail().