Arrow: lib/common/options.c File Reference
lib/common/options.c File Reference
Helper for parsing program options.
#include "common.h"
Functions
void print_usage (char *program_name, char *usage)
void print_version (char *program_name)
void print_help (int num_opts, arrow_option options[], char *description)
int arrow_options_parse (int num_opts, arrow_option options[], char *description, char *usage, int argc, char *argv[], int *opt_ind)
Parses program options.
Detailed Description
Helper for parsing program options.
For helping parse all those pesky program options!
Author:
John LaRusic
Definition in file options.c.
Function Documentation
int arrow_options_parse (int num_opts, arrow_option options[], char * description, char * usage, int argc, char * argv[], int * opt_ind)
Parses program options.
Parameters:
num_opts [in] the number of program options
options [out] array of program options
description [in] description of program
usage [in] usage message
argc [in] number of program arguments
argv [out] array of program arguments (might be rearranged)
opt_ind [out] index first program option appears at
Definition at line 24 of file options.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_OPTION_DOUBLE, ARROW_OPTION_INT, ARROW_OPTION_STRING, arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_option::long_option, print_help(), print_usage(), print_version(), and arrow_option::short_option.
Referenced by main().
void print_help (int num_opts, arrow_option options[], char * description)
Definition at line 208 of file options.c.
void print_usage (char * program_name, char * usage)
Definition at line 187 of file options.c.
void print_version (char * program_name)
Definition at line 193 of file options.c.
References ARROW_VERSION.