Arrow: lib/common/problem.c File Reference
lib/common/problem.c File Reference
Functions for working with problem data.
#include "common.h"
Data Structures
struct full_matrix_data
struct abtsp_data
struct mstsp_data
Functions
int is_symmetric (char *file_name)
Determines if the given file is a symmetric TSPLIB file.
int is_asymmetric (char *file_name)
Determines if the given file is an asymmetric TSPLIB file.
int read_stsp (char *file_name, arrow_problem *problem)
Reads an symmetric TSPLIB file (*.tsp).
int concorde_get_cost (arrow_problem *problem, int i, int j)
Retrieves cost between nodes i and j from Concorde's structure.
void concorde_destruct (arrow_problem *problem)
Destructs Concorde's data structure.
int read_atsp (char *file_name, arrow_problem *problem)
Reads an asymmetric TSPLIB file (*.atsp).
int full_matrix_get_cost (arrow_problem *problem, int i, int j)
Edge length function for full matrix data.
void full_matrix_destruct (arrow_problem *problem)
Destructs data structure of a full matrix problem.
int abtsp_get_cost (arrow_problem *problem, int i, int j)
Edge length function for ABTSP->SBTSP data.
void abtsp_destruct (arrow_problem *problem)
Destructs data structure of a ABTSP->SBTSP problem.
int mstsp_get_cost (arrow_problem *problem, int i, int j)
Edge length function for MSTSP->BTSP data.
void mstsp_destruct (arrow_problem *problem)
Destructs data structure of a MSTSP->BTSP problem.
int arrow_problem_read (char *file_name, arrow_problem *problem)
Reads a problem from a TSPLIB file.
void arrow_problem_destruct (arrow_problem *problem)
Deallocates problem data structure.
int arrow_problem_info_get (arrow_problem *problem, int create_hash, arrow_problem_info *info)
Builds ordered cost list and finds min/max cost in a problem.
void arrow_problem_info_destruct (arrow_problem_info *info)
Deallocates problem info data structure.
int arrow_problem_info_cost_index (arrow_problem_info *info, int cost, int *pos)
Finds the position of the given cost into the sorted list.
int arrow_problem_max_cost (arrow_problem *problem)
Finds the largest cost in a problem (cheaper than calling arrow_problem_info_get).
void arrow_problem_print (arrow_problem *problem, int pretty)
Prints out information about a problem.
int arrow_problem_read_tour (char *file_name, int size, int *tour)
Reads a TSPLIB tour file.
int arrow_problem_abtsp_to_sbtsp (int shallow, arrow_problem *old_problem, int infinity, arrow_problem *new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
int arrow_problem_mstsp_to_btsp (int shallow, arrow_problem *old_problem, int max_cost, arrow_problem *new_problem)
Transforms a MSTSP problem into the equivalent BTSP problem.
Detailed Description
Functions for working with problem data.
Function implementations for working with problem data, generally manipulating the arrow_problem data structure.
Author:
John LaRusic
Definition in file problem.c.
Function Documentation
void abtsp_destruct (arrow_problem * problem)
Destructs data structure of a ABTSP->SBTSP problem.
Parameters:
problem [in] pointer to arrow_problem structure
Definition at line 713 of file problem.c.
Referenced by arrow_problem_abtsp_to_sbtsp().
int abtsp_get_cost (arrow_problem * problem, int i, int j)
Edge length function for ABTSP->SBTSP data.
Parameters:
problem [in] pointer to arrow_problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
The cost between nodes i and j
Definition at line 697 of file problem.c.
References abtsp_data::base, arrow_problem::get_cost, abtsp_data::infinity, and arrow_problem::size.
Referenced by arrow_problem_abtsp_to_sbtsp().
int arrow_problem_abtsp_to_sbtsp (int shallow, arrow_problem * old_problem, int infinity, arrow_problem * new_problem)
Transforms an asymmetric BTSP problem of n nodes into a symmetric BTSP problem with 2n nodes.
Parameters:
shallow [in] if true only a shallow copy of data will be created
old_problem [in] the asymmetric problem
infinity [in] value to use as "infinity"
new_problem [out] the new symmetric problem
Definition at line 379 of file problem.c.
References abtsp_destruct(), abtsp_get_cost(), ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_ABTSP_TO_SBTSP, ARROW_SUCCESS, ARROW_TRUE, abtsp_data::base, arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, arrow_problem::get_cost, abtsp_data::infinity, arrow_problem::name, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), and main().
void arrow_problem_destruct (arrow_problem * problem)
Deallocates problem data structure.
Parameters:
problem [out] problem data structure
Definition at line 176 of file problem.c.
References arrow_problem::data, and arrow_problem::destruct.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), arrow_btsp_feasible(), btsp_bounds(), and main().
int arrow_problem_info_cost_index (arrow_problem_info * info, int cost, int * pos)
Finds the position of the given cost into the sorted list.
Parameters:
info [in] problem info data structure
cost [in] cost to look up
pos [out] position of given cost in sorted list
Definition at line 247 of file problem.c.
References ARROW_FAILURE, arrow_hash_search(), arrow_print_error, ARROW_SUCCESS, arrow_util_binary_search(), arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem_info::hash, and arrow_hash::num_keys.
Referenced by arrow_balanced_tsp_db(), arrow_balanced_tsp_dt(), arrow_balanced_tsp_dt2(), arrow_balanced_tsp_ib(), arrow_balanced_tsp_ib2(), arrow_balanced_tsp_lb(), baltsp_dt2_get_cost(), baltsp_shake_get_cost(), btsp_shake_1_get_cost(), cbtsp_shake_get_cost(), and main().
void arrow_problem_info_destruct (arrow_problem_info * info)
Deallocates problem info data structure.
Parameters:
info [in] problem info data structure
Definition at line 238 of file problem.c.
References arrow_hash_destruct(), arrow_problem_info::cost_list, arrow_problem_info::hash, and arrow_hash::num_keys.
Referenced by main().
int arrow_problem_info_get (arrow_problem * problem, int create_hash, arrow_problem_info * info)
Builds ordered cost list and finds min/max cost in a problem.
Parameters:
problem [in] problem data structure
create_hash [in] if true will also create hash table of cost list
info [out] problem info data structure
Definition at line 186 of file problem.c.
References arrow_bintree_destruct(), arrow_bintree_init(), arrow_bintree_insert(), arrow_bintree_to_new_array(), arrow_hash_cost_list(), ARROW_SUCCESS, ARROW_TRUE, arrow_problem_info::cost_list, arrow_problem_info::cost_list_length, arrow_problem::get_cost, arrow_problem_info::hash, arrow_problem_info::max_cost, arrow_problem_info::min_cost, arrow_hash::num_keys, arrow_bintree::size, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
int arrow_problem_max_cost (arrow_problem * problem)
Finds the largest cost in a problem (cheaper than calling arrow_problem_info_get).
Parameters:
problem [in] problem data structure
Returns:
The largest cost in the problem.
Definition at line 272 of file problem.c.
References ARROW_TRUE, arrow_problem::get_cost, arrow_problem::size, and arrow_problem::symmetric.
Referenced by main().
int arrow_problem_mstsp_to_btsp (int shallow, arrow_problem * old_problem, int max_cost, arrow_problem * new_problem)
Transforms a MSTSP problem into the equivalent BTSP problem.
Parameters:
shallow [in] if true only a shallow copy of data will be created
old_problem [in] the MSTSP problem
max_cost [in] the maximum cost in old_problem
new_problem [out] the new BTSP problem
Definition at line 406 of file problem.c.
References ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_MSTSP_TO_BTSP, ARROW_SUCCESS, mstsp_data::base, arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, arrow_problem::get_cost, mstsp_data::max_cost, mstsp_destruct(), mstsp_get_cost(), arrow_problem::name, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by main().
void arrow_problem_print (arrow_problem * problem, int pretty)
Prints out information about a problem.
Parameters:
problem [in] problem data structure
pretty [in] if ARROW_TRUE, formats output to 8 nodes/row
Definition at line 295 of file problem.c.
References arrow_problem::get_cost, arrow_problem::shallow, arrow_problem::size, and arrow_problem::symmetric.
int arrow_problem_read (char * file_name, arrow_problem * problem)
Reads a problem from a TSPLIB file.
Parameters:
file_name [in] path to TSPLIB file
problem [out] problem data structure
Definition at line 141 of file problem.c.
References ARROW_FAILURE, arrow_print_error, is_asymmetric(), is_symmetric(), arrow_problem::name, read_atsp(), and read_stsp().
Referenced by main().
int arrow_problem_read_tour (char * file_name, int size, int * tour)
Reads a TSPLIB tour file.
Parameters:
file_name [in] the TSPLIB tour file to read
size [in] the number of cities in the tour
tour [out] an array to hold the tour in node-node format
Definition at line 370 of file problem.c.
References ARROW_FAILURE, ARROW_SUCCESS, and CONCORDE_SUCCESS.
Referenced by main().
void concorde_destruct (arrow_problem * problem)
Destructs Concorde's data structure.
Parameters:
problem [in] pointer to arrow_problem structure
Definition at line 499 of file problem.c.
References arrow_problem::data.
Referenced by read_stsp().
int concorde_get_cost (arrow_problem * problem, int i, int j)
Retrieves cost between nodes i and j from Concorde's structure.
Parameters:
problem [in] pointer to arrow_problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
cost between node i and node j
Definition at line 492 of file problem.c.
References arrow_problem::data.
Referenced by read_stsp().
void full_matrix_destruct (arrow_problem * problem)
Destructs data structure of a full matrix problem.
Parameters:
problem [in] pointer to arrow_problem structure
Definition at line 686 of file problem.c.
References full_matrix_data::adj, full_matrix_data::adjspace, and arrow_problem::data.
Referenced by read_atsp().
int full_matrix_get_cost (arrow_problem * problem, int i, int j)
Edge length function for full matrix data.
Parameters:
problem [in] pointer to arrow_problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
The cost between nodes i and j
Definition at line 679 of file problem.c.
References full_matrix_data::adj, and arrow_problem::data.
Referenced by read_atsp().
int is_asymmetric (char * file_name)
Determines if the given file is an asymmetric TSPLIB file.
Parameters:
file_name [in] the path to the TSPLIB file
Returns:
ARROW_TRUE if the file is for asymmetric data, ARROW_FALSE if not
Definition at line 447 of file problem.c.
References arrow_util_regex_match().
Referenced by arrow_problem_read().
int is_symmetric (char * file_name)
Determines if the given file is a symmetric TSPLIB file.
Parameters:
file_name [in] the path to the TSPLIB file
Returns:
ARROW_TRUE if the file is for symmetric data, ARROW_FALSE if not
Definition at line 441 of file problem.c.
References arrow_util_regex_match().
Referenced by arrow_problem_read().
void mstsp_destruct (arrow_problem * problem)
Destructs data structure of a MSTSP->BTSP problem.
Parameters:
problem [in] pointer to arrow_problem structure
Definition at line 726 of file problem.c.
Referenced by arrow_problem_mstsp_to_btsp().
int mstsp_get_cost (arrow_problem * problem, int i, int j)
Edge length function for MSTSP->BTSP data.
Parameters:
problem [in] pointer to arrow_problem structure
i [in] id of starting node
j [in] id of ending node
Returns:
The cost between nodes i and j
Definition at line 719 of file problem.c.
References mstsp_data::base, arrow_problem::get_cost, and mstsp_data::max_cost.
Referenced by arrow_problem_mstsp_to_btsp().
int read_atsp (char * file_name, arrow_problem * problem)
Reads an asymmetric TSPLIB file (*.atsp).
Parameters:
file_name [in] the path to the TSPLIB file
problem [out] problem structure
Definition at line 509 of file problem.c.
References full_matrix_data::adj, full_matrix_data::adjspace, arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_PROBLEM_DATA_FULL_MATRIX, ARROW_SUCCESS, arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, full_matrix_destruct(), full_matrix_get_cost(), arrow_problem::get_cost, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by arrow_problem_read().
int read_stsp (char * file_name, arrow_problem * problem)
Reads an symmetric TSPLIB file (*.tsp).
Parameters:
file_name [in] the path to the TSPLIB file
problem [out] problem structure
Definition at line 453 of file problem.c.
References arrow_debug, ARROW_FAILURE, ARROW_FALSE, arrow_print_error, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, ARROW_TRUE, concorde_destruct(), concorde_get_cost(), arrow_problem::data, arrow_problem::destruct, arrow_problem::fixed_edges, arrow_problem::get_cost, arrow_problem::shallow, arrow_problem::size, arrow_problem::symmetric, and arrow_problem::type.
Referenced by arrow_problem_read().