Arrow: lib/tsp/rai.c File Reference
lib/tsp/rai.c File Reference
Random arbitrary insertion TSP heuristic.
#include "common.h"
#include "tsp.h"
Functions
void construct_tour (arrow_problem *problem, int solve_btsp, int *node_list, int list_size, arrow_llist *tour, double *length, arrow_llist_item **ins_list)
Given a set of nodes to insert, inserts them as cheaply as possible into a partial tour.
void improve_tour (arrow_problem *problem, int solve_btsp, arrow_llist *best_tour, double *length, arrow_llist *tour, arrow_llist_item **ins_list, int *node_list)
Attempts to improve upon the given tour by removing a random path and reinserting the removed nodes in a random order as cheaply as possible..
int min2 (int i, int j)
Returns the min of the two values.
int max2 (int i, int j)
Returns the max of the two values.
int max3 (int i, int j, int k)
Returns the max of the three values.
int arrow_tsp_rai_solve (arrow_problem *problem, arrow_tsp_rai_params *params, arrow_tsp_result *result)
Detailed Description
Random arbitrary insertion TSP heuristic.
Random arbitrary insertion (RAI) TSP heuristic.
Author:
John LaRusic
Definition in file rai.c.
Function Documentation
int arrow_tsp_rai_solve (arrow_problem * problem, arrow_tsp_rai_params * params, arrow_tsp_result * result)
Definition at line 91 of file rai.c.
References arrow_debug, ARROW_FAILURE, arrow_llist_destruct(), arrow_llist_init(), arrow_llist_insert_tail(), arrow_llist_to_array(), arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_permute_array(), arrow_util_zeit(), construct_tour(), arrow_tsp_result::found_tour, improve_tour(), arrow_tsp_rai_params::iterations, length, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_rai_params::solve_btsp, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by arrow_tsp_solve().
void construct_tour (arrow_problem * problem, int solve_btsp, int * node_list, int list_size, arrow_llist * tour, double * length, arrow_llist_item ** ins_list)
Given a set of nodes to insert, inserts them as cheaply as possible into a partial tour.
Parameters:
problem [in] problem data
solve_btsp [in] if ARROW_TRUE, attempts to construct tour by minimizing the maximum cost, otherwise constructs tour by minimizing the largest cost
node_list [in] the list of nodes to insert into the partial tour
list_size [in] the number of nodes in the node list
tour [out] initially a partial tour, at termination is a full tour of n nodes
length [out] the length of the tour (or largest cost in tour if solve_btsp = ARROW_TRUE)
ins_list [out] a temporary array of pointers to linked list items
Definition at line 253 of file rai.c.
References arrow_llist_insert_after(), arrow_llist_insert_tail(), arrow_util_random_between(), arrow_llist_item::data, arrow_problem::get_cost, arrow_llist::head, max3(), arrow_llist_item::next, and arrow_llist::size.
Referenced by arrow_tsp_rai_solve(), and improve_tour().
void improve_tour (arrow_problem * problem, int solve_btsp, arrow_llist * best_tour, double * length, arrow_llist * tour, arrow_llist_item ** ins_list, int * node_list)
Attempts to improve upon the given tour by removing a random path and reinserting the removed nodes in a random order as cheaply as possible..
Parameters:
problem [in] problem data
solve_btsp [in] if ARROW_TRUE, attempts to construct tour by minimizing the maximum cost, otherwise constructs tour by minimizing the largest cost
best_tour [out] the best tour found so far; if a better tour is found this pointer will be changed to point to the new best tour
length [out] the length of the tour (or largest cost in tour if solve_btsp = ARROW_TRUE)
tour [out] initially a partial tour, at termination is a full tour of n nodes
ins_list [out] a temporary array of pointers to linked list items
node_list [out] temporary array of integers of size n
Definition at line 177 of file rai.c.
References arrow_debug, arrow_llist_destruct(), arrow_llist_insert_tail(), arrow_llist_swap(), arrow_util_permute_array(), arrow_util_random_between(), construct_tour(), arrow_llist_item::data, arrow_llist::head, arrow_llist_item::next, and arrow_problem::size.
Referenced by arrow_tsp_rai_solve().
int max2 (int i, int j)
Returns the max of the two values.
Parameters:
i [in] first number
j [in] second number
Returns:
the largest of i, j
Definition at line 401 of file rai.c.
References max().
int max3 (int i, int j, int k)
Returns the max of the three values.
Parameters:
i [in] first number
j [in] second number
k [in] third number
Returns:
the largest of i, j, k
Definition at line 409 of file rai.c.
References max().
Referenced by construct_tour().
int min2 (int i, int j)
Returns the min of the two values.
Parameters:
i [in] first number
j [in] second number
Returns:
the smallest of i, j
Definition at line 393 of file rai.c.