Arrow: arrow_btsp_fun Struct Reference
arrow_btsp_fun Struct Reference
BTSP Cost matrix function definition.
#include <btsp.h>
Data Fields
void * data
int shallow
int(* get_cost)(struct arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
int(* initialize)(struct arrow_btsp_fun *fun)
Initializes the function structure for a new problem.
void(* destruct)(struct arrow_btsp_fun *fun)
Destructs the function structure.
int(* feasible)(struct arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
Detailed Description
BTSP Cost matrix function definition.
Definition at line 44 of file btsp.h.
Field Documentation
void* arrow_btsp_fun::data
data required by function
Definition at line 46 of file btsp.h.
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), baltsp_dt2_feasible(), baltsp_dt2_get_cost(), baltsp_dt2_initialize(), baltsp_shake_destruct(), baltsp_shake_get_cost(), baltsp_shake_initialize(), btsp_asym_shift_destruct(), btsp_asym_shift_feasible(), btsp_asym_shift_get_cost(), btsp_shake_1_destruct(), btsp_shake_1_get_cost(), btsp_shake_1_initialize(), cbtsp_basic_destruct(), cbtsp_basic_feasible(), cbtsp_basic_get_cost(), cbtsp_shake_destruct(), cbtsp_shake_feasible(), cbtsp_shake_get_cost(), and cbtsp_shake_initialize().
void(* arrow_btsp_fun::destruct)(struct arrow_btsp_fun *fun)
Destructs the function structure.
Parameters:
fun [out] function structure
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_destruct(), and arrow_btsp_fun_shake_1().
int(* arrow_btsp_fun::feasible)(struct arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, double tour_length, int *tour)
Determines if the given tour is feasible or not.
Parameters:
fun [in] function structure
problem [in] the problem to check against
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
tour_length [in] the length of the given tour
tour [in] the tour in node-node format
Returns:
ARROW_TRUE if the tour is feasible, ARROW_FALSE if not
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_feasible(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), and arrow_btsp_fun_shake_1().
int(* arrow_btsp_fun::get_cost)(struct arrow_btsp_fun *fun, arrow_problem *base_problem, int min_cost, int max_cost, int i, int j)
Retrieves cost between nodes i and j from the function.
Parameters:
fun [in] function structure
problem [in] problem structure
min_cost [in] min_cost to consider for active edges
max_cost [in] max_cost to consider for active edges
i [in] id of start node
j [in] id of end node
Returns:
cost between node i and node j
Referenced by apply_deep(), arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), arrow_btsp_fun_shake_1(), and fun_get_cost().
int(* arrow_btsp_fun::initialize)(struct arrow_btsp_fun *fun)
Initializes the function structure for a new problem.
Parameters:
fun [out] function structure
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_fun_apply(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), and arrow_btsp_fun_shake_1().
int arrow_btsp_fun::shallow
indicates use of shallow copy of data
Definition at line 47 of file btsp.h.
Referenced by arrow_baltsp_fun_basic(), arrow_baltsp_fun_dt2(), arrow_baltsp_fun_ib(), arrow_baltsp_fun_shake(), arrow_baltsp_fun_ut(), arrow_btsp_fun_apply(), arrow_btsp_fun_asym_shift(), arrow_btsp_fun_basic(), arrow_btsp_fun_cbtsp_basic(), arrow_btsp_fun_cbtsp_shake(), and arrow_btsp_fun_shake_1().
The documentation for this struct was generated from the following file:
include/btsp.h