Arrow: bin/tour_info.c File Reference
bin/tour_info.c File Reference
Tour information.
#include "arrow.h"
#include <getopt.h>
Functions
void print_help ()
Prints help/usage message.
void print_version ()
Prints version message.
void print_usage ()
Prints usage message.
void read_args (int argc, char *argv[])
Reads program arguments.
void print_xml_output (double length, int max_cost, int min_cost, int argc, char *argv[])
Prints output in XML format.
int main (int argc, char *argv[])
Variables
char * program_name
char * problem_file
char * tour_file
int xml_output = ARROW_FALSE
Detailed Description
Tour information.
Displays tour information for a given problem input and tour input
Author:
John LaRusic
Definition in file tour_info.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 53 of file tour_info.c.
References ARROW_DEV_NULL, arrow_print_error, arrow_problem_destruct(), arrow_problem_read(), arrow_problem_read_tour(), ARROW_SUCCESS, arrow_util_create_int_array(), arrow_util_redirect_stdout_to_file(), arrow_util_restore_stdout(), arrow_problem::get_cost, length, print_xml_output(), problem_file, program_name, read_args(), arrow_problem::size, tour_file, and xml_output.
void print_help ()
Prints help/usage message.
void print_usage ()
Prints usage message.
void print_version ()
Prints version message.
void print_xml_output (double length, int max_cost, int min_cost, int argc, char * argv[])
Prints output in XML format.
Definition at line 214 of file tour_info.c.
References problem_file, and tour_file.
Referenced by main().
void read_args (int argc, char * argv[])
Reads program arguments.
Variable Documentation
char* problem_file
Given TSPLIB problem file
Definition at line 45 of file tour_info.c.
Referenced by main(), and print_xml_output().
char* program_name
Program name
Definition at line 44 of file tour_info.c.
char* tour_file
Given TSPLIB tour file
Definition at line 46 of file tour_info.c.
int xml_output = ARROW_FALSE
Output output in XML format (or not)
Definition at line 47 of file tour_info.c.
Referenced by main().