Arrow: include/tsp.h File Reference
include/tsp.h File Reference
Solvers and heuristics for the traveling salesman problem.
Data Structures
struct arrow_tsp_cc_lk_params
LK algorithm parameters.
struct arrow_tsp_rai_params
LK algorithm parameters.
struct arrow_tsp_result
TSP result (including result from LK heuristic).
Defines
#define ARROW_TSP_SOLVER_COUNT 4
#define ARROW_TSP_CC_EXACT 0
#define ARROW_TSP_CC_LK 1
#define ARROW_TSP_RAI 2
#define ARROW_TSP_PATCHING 3
Functions
void arrow_tsp_cc_lk_params_init (arrow_problem *problem, arrow_tsp_cc_lk_params *params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
void arrow_tsp_cc_lk_params_destruct (arrow_tsp_cc_lk_params *params)
Destructs a LK parameters structure.
int arrow_tsp_cc_exact_solve (arrow_problem *problem, int *initial_tour, arrow_tsp_result *result)
Solves TSP with Concorde's exact solver.
int arrow_tsp_cc_lk_solve (arrow_problem *problem, arrow_tsp_cc_lk_params *params, arrow_tsp_result *result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
int arrow_tsp_rai_solve (arrow_problem *problem, arrow_tsp_rai_params *params, arrow_tsp_result *result)
int arrow_tsp_result_init (arrow_problem *problem, arrow_tsp_result *result)
Initializes the TSP result structure.
void arrow_tsp_result_destruct (arrow_tsp_result *result)
Destructs a TSP result structure.
int arrow_tsp_solve (int tsp_solver, arrow_problem *problem, void *params, arrow_tsp_result *result)
Solves TSP with for requested TSP solver.
void arrow_tsp_short_name (int tsp_solver, FILE *out)
Prints out the short name for the given solver.
void arrow_tsp_long_name (int tsp_solver, FILE *out)
Prints out the long name for the given solver.
Detailed Description
Solvers and heuristics for the traveling salesman problem.
Solvers and heuristics for the traveling salesman problem.
Author:
John LaRusic
Definition in file tsp.h.
Define Documentation
#define ARROW_TSP_CC_EXACT 0
Definition at line 19 of file tsp.h.
Referenced by arrow_btsp_solve(), arrow_btsp_solve_plan_destruct(), arrow_tsp_long_name(), arrow_tsp_short_name(), arrow_tsp_solve(), and main().
#define ARROW_TSP_CC_LK 1
Definition at line 20 of file tsp.h.
Referenced by arrow_btsp_solve_plan_destruct(), arrow_tsp_long_name(), arrow_tsp_short_name(), arrow_tsp_solve(), and main().
#define ARROW_TSP_PATCHING 3
Definition at line 22 of file tsp.h.
#define ARROW_TSP_RAI 2
Definition at line 21 of file tsp.h.
Referenced by arrow_tsp_long_name(), arrow_tsp_short_name(), arrow_tsp_solve(), and main().
#define ARROW_TSP_SOLVER_COUNT 4
Definition at line 18 of file tsp.h.
Referenced by arrow_btsp_result_init(), arrow_btsp_result_print_pretty(), arrow_btsp_result_print_xml(), arrow_btsp_solve(), and feasible().
Function Documentation
int arrow_tsp_cc_exact_solve (arrow_problem * problem, int * initial_tour, arrow_tsp_result * result)
Solves TSP with Concorde's exact solver.
Parameters:
problem [in] problem to solve
initial_tour [in] an initial tour (can be NULL)
result [out] TSP solution
Definition at line 62 of file cc.c.
References arrow_copy(), arrow_debug, arrow_edgelen(), ARROW_FAILURE, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, arrow_util_zeit(), arrow_problem::data, arrow_tsp_result::found_tour, arrow_problem::name, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, arrow_tsp_result::tour, and arrow_problem::type.
Referenced by arrow_tsp_solve(), and main().
void arrow_tsp_cc_lk_params_destruct (arrow_tsp_cc_lk_params * params)
Destructs a LK parameters structure.
Parameters:
params [out] LK parameters structure
Definition at line 55 of file cc.c.
References arrow_tsp_cc_lk_params::initial_tour.
Referenced by arrow_btsp_solve_plan_destruct(), arrow_tsp_cc_lk_solve(), and main().
void arrow_tsp_cc_lk_params_init (arrow_problem * problem, arrow_tsp_cc_lk_params * params)
Sets default parameters for Lin-Kernighan heuristic:
random_restarts = 0
stall_count = problem->size
kicks = (problem->size / 2), at least 500
kick_type = CC_LK_GEOMETRIC_KICK
time_bound = 0.0
length_bound = 0.0
initial_tour = NULL.
Parameters:
problem [in] problem to solve
params [out] LK parameters structure
Definition at line 42 of file cc.c.
References arrow_tsp_cc_lk_params::initial_tour, arrow_tsp_cc_lk_params::kick_type, arrow_tsp_cc_lk_params::kicks, arrow_tsp_cc_lk_params::length_bound, arrow_tsp_cc_lk_params::random_restarts, arrow_problem::size, arrow_tsp_cc_lk_params::stall_count, and arrow_tsp_cc_lk_params::time_bound.
Referenced by arrow_tsp_cc_lk_solve(), and main().
int arrow_tsp_cc_lk_solve (arrow_problem * problem, arrow_tsp_cc_lk_params * params, arrow_tsp_result * result)
Solves TSP with Concorde's Lin-Kernighan heuristic.
Parameters:
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 118 of file cc.c.
References arrow_copy(), arrow_debug, arrow_edgelen(), ARROW_FAILURE, arrow_print_error, ARROW_PROBLEM_DATA_CONCORDE, ARROW_SUCCESS, ARROW_TRUE, arrow_tsp_cc_lk_params_destruct(), arrow_tsp_cc_lk_params_init(), arrow_util_zeit(), build_initial_tour(), CONCORDE_FAILURE, arrow_problem::data, arrow_tsp_result::found_tour, arrow_tsp_cc_lk_params::initial_tour, arrow_tsp_cc_lk_params::kick_type, arrow_tsp_cc_lk_params::kicks, arrow_tsp_cc_lk_params::length_bound, arrow_tsp_result::obj_value, arrow_tsp_cc_lk_params::random_restarts, arrow_problem::size, arrow_tsp_cc_lk_params::stall_count, arrow_tsp_cc_lk_params::time_bound, arrow_tsp_result::total_time, arrow_tsp_result::tour, and arrow_problem::type.
Referenced by arrow_tsp_solve().
void arrow_tsp_long_name (int tsp_solver, FILE * out)
Prints out the long name for the given solver.
Parameters:
tsp_solver [in] the TSP solver in question
out [out] the file handle to print out to.
Definition at line 61 of file tsp.c.
References arrow_print_error, ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, and ARROW_TSP_RAI.
Referenced by arrow_btsp_result_print_pretty().
int arrow_tsp_rai_solve (arrow_problem * problem, arrow_tsp_rai_params * params, arrow_tsp_result * result)
Definition at line 91 of file rai.c.
References arrow_debug, ARROW_FAILURE, arrow_llist_destruct(), arrow_llist_init(), arrow_llist_insert_tail(), arrow_llist_to_array(), arrow_print_error, ARROW_SUCCESS, ARROW_TRUE, arrow_util_create_int_array(), arrow_util_permute_array(), arrow_util_zeit(), construct_tour(), arrow_tsp_result::found_tour, improve_tour(), arrow_tsp_rai_params::iterations, length, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_rai_params::solve_btsp, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by arrow_tsp_solve().
void arrow_tsp_result_destruct (arrow_tsp_result * result)
Destructs a TSP result structure.
Parameters:
result [out] TSP result structure
Definition at line 30 of file result.c.
References arrow_tsp_result::tour.
Referenced by feasible(), and main().
int arrow_tsp_result_init (arrow_problem * problem, arrow_tsp_result * result)
Initializes the TSP result structure.
Parameters:
problem [in] problem to solve
result [out] TSP result structure
Definition at line 16 of file result.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_tsp_result::found_tour, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by feasible(), and main().
void arrow_tsp_short_name (int tsp_solver, FILE * out)
Prints out the short name for the given solver.
Parameters:
tsp_solver [in] the TSP solver in question
out [out] the file handle to print out to.
Definition at line 45 of file tsp.c.
References arrow_print_error, ARROW_TSP_CC_EXACT, ARROW_TSP_CC_LK, and ARROW_TSP_RAI.
Referenced by arrow_btsp_result_print_xml().
int arrow_tsp_solve (int tsp_solver, arrow_problem * problem, void * params, arrow_tsp_result * result)
Solves TSP with for requested TSP solver.
Parameters:
tsp_solver [in] the TSP solver to use
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Solves TSP with for requested TSP solver.
Parameters:
tsp_solver [in] the TSP solver to use
problem [in] problem to solve
params [in] Lin-Kernighan params (can be NULL)
result [out] TSP solution
Definition at line 20 of file tsp.c.
References ARROW_FAILURE, arrow_print_error, ARROW_TSP_CC_EXACT, arrow_tsp_cc_exact_solve(), ARROW_TSP_CC_LK, arrow_tsp_cc_lk_solve(), ARROW_TSP_RAI, and arrow_tsp_rai_solve().
Referenced by feasible().