Arrow: lib/tsp/result.c File Reference
lib/tsp/result.c File Reference
TSP result structure and methods.
#include "common.h"
#include "btsp.h"
Functions
int arrow_tsp_result_init (arrow_problem *problem, arrow_tsp_result *result)
Initializes the TSP result structure.
void arrow_tsp_result_destruct (arrow_tsp_result *result)
Destructs a TSP result structure.
Detailed Description
TSP result structure and methods.
Traveling salesman problem results structure.
Author:
John LaRusic
Definition in file result.c.
Function Documentation
void arrow_tsp_result_destruct (arrow_tsp_result * result)
Destructs a TSP result structure.
Parameters:
result [out] TSP result structure
Definition at line 30 of file result.c.
References arrow_tsp_result::tour.
Referenced by arrow_btsp_feasible(), and main().
int arrow_tsp_result_init (arrow_problem * problem, arrow_tsp_result * result)
Initializes the TSP result structure.
Parameters:
problem [in] problem to solve
result [out] TSP result structure
Definition at line 16 of file result.c.
References ARROW_FAILURE, ARROW_FALSE, ARROW_SUCCESS, arrow_util_create_int_array(), arrow_tsp_result::found_tour, arrow_tsp_result::obj_value, arrow_problem::size, arrow_tsp_result::total_time, and arrow_tsp_result::tour.
Referenced by arrow_btsp_feasible(), and main().