Arrow: lib/util.c File Reference
lib/util.c File Reference
Useful utility functions.
#include "arrow.h"
Functions
int arrow_util_create_int_array (int size, int **array)
Creates an integer array.
int arrow_util_create_int_matrix (int rows, int cols, int ***matrix, int **space)
Creates a full integer matrix.
void arrow_util_print_error (const char *file_name, int line_num, const char *message)
Prints an error message to stderr with consistent formatting.
double arrow_util_zeit ()
Used to measure timings.
void arrow_util_redirect_stdout_to_file (const char *filename, int *old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup *from, CCdatagroup *to)
Makes a shallow copy of the Concorde CCdatagroup structure.
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup *dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
int arrow_util_binary_search (int *array, int size, int element, int *pos)
Performs a binary search to find the wanted element in a sorted integer array.
int arrow_util_regex_match (char *string, char *pattern)
Determines if the given string turns up a match for the given regular expression pattern.
void arrow_util_print_program_args (int argc, char *argv[], FILE *out)
Prints out the given program arguments to the specified file.
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
int arrow_util_random ()
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
int arrow_util_random_between (int min, int max)
Returns a random number between min and max.
void arrow_util_write_tour (arrow_problem *problem, char *comment, int *tour, FILE *out)
void arrow_util_sbtsp_to_abstp_tour (arrow_problem *problem, int *old_tour, int *new_tour)
Detailed Description
Useful utility functions.
Useful utility functions that have general purpose throughout the library.
Author:
John LaRusic
Definition in file util.c.
Function Documentation
int arrow_util_binary_search (int * array, int size, int element, int * pos)
Performs a binary search to find the wanted element in a sorted integer array.
Parameters:
array [in] the array to search (note: must be sorted in non-increasing order)
size [in] size of the array
element [in] the element to find in the array
pos [out] the index where the element can be found in the array
Definition at line 145 of file util.c.
References ARROW_FAILURE, and ARROW_SUCCESS.
Referenced by arrow_btsp_solve(), and constrained_shake_deep_apply().
int arrow_util_CCdatagroup_init_matrix (int size, CCdatagroup * dat)
Initializes an upper-diagonal matrix norm structure for Concorde that is ready to be filled in with values.
Parameters:
size [in] the number of cities/vertices
dat [out] the CCdatagroup structure to create
Definition at line 115 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_btsp_fun_apply(), and arrow_problem_abtsp_to_sbtsp().
void arrow_util_CCdatagroup_shallow_copy (CCdatagroup * from, CCdatagroup * to)
Makes a shallow copy of the Concorde CCdatagroup structure.
Parameters:
from [in] the CCdatagroup structure to copy from
to [out] the CCdatagroup structure to copy to
Definition at line 89 of file util.c.
int arrow_util_create_int_array (int size, int ** array) [inline]
Creates an integer array.
Parameters:
size [in] size of array
array [out] pointer to array that will be created
Definition at line 15 of file util.c.
References ARROW_FAILURE, arrow_print_error, and ARROW_SUCCESS.
Referenced by arrow_bap_solve(), arrow_bbssp_biconnected(), arrow_bintree_to_array(), arrow_btsp_result_init(), arrow_tsp_result_init(), arrow_util_create_int_matrix(), main(), and strongly_connected().
int arrow_util_create_int_matrix (int rows, int cols, int *** matrix, int ** space) [inline]
Creates a full integer matrix.
Parameters:
rows [in] number of rows
cols [in] number of columns
matrix [out] pointer to matrix that will be created
space [out] pointer to matrix space that will be created
Definition at line 27 of file util.c.
References ARROW_FAILURE, arrow_print_error, ARROW_SUCCESS, and arrow_util_create_int_array().
Referenced by arrow_bap_solve(), and arrow_dcbpb_solve().
void arrow_util_print_error (const char * file_name, int line_num, const char * message) [inline]
Prints an error message to stderr with consistent formatting.
Parameters:
file_name [in] file error occured in
line_num [in] line number error occured at
message [in] error message to write
Definition at line 56 of file util.c.
void arrow_util_print_program_args (int argc, char * argv[], FILE * out)
Prints out the given program arguments to the specified file.
Parameters:
argc [in] the number of arguments
argv [in] the program arugment array
out [in] the file handle to print out to
Definition at line 195 of file util.c.
Referenced by main().
int arrow_util_random () [inline]
Returns a random number between 0 and RAND_MAX (normally, RAND_MAX = INT_MAX).
Returns:
a random integer.
Definition at line 215 of file util.c.
int arrow_util_random_between (int min, int max) [inline]
Returns a random number between min and max.
Parameters:
min [in] the minimum random number to return
max [in] the maximum random number to return
Returns:
a random integer in the range [min, max]
Definition at line 221 of file util.c.
Referenced by constrained_shake_deep_apply().
void arrow_util_random_seed (int seed)
Seeds the random number generator. Pass a value of 0 to seed with the current time.
Parameters:
seed [in] the random number seed.
Definition at line 206 of file util.c.
Referenced by main().
void arrow_util_redirect_stdout_to_file (const char * filename, int * old_stream)
Redirects STDOUT stream to a file (can be used to completely surpress output by directing to /dev/null).
Parameters:
filename [in] name of file to direct STDOUT to
old_stream [out] existing file handle for STDOUT stream (necessary for restoring stream afterwards)
Definition at line 69 of file util.c.
Referenced by main().
int arrow_util_regex_match (char * string, char * pattern)
Determines if the given string turns up a match for the given regular expression pattern.
Parameters:
string [in] the string to match against
pattern [in] the regular expression pattern to match
Returns:
ARROW_TRUE if a match is found, ARROW_FALSE if not.
Definition at line 177 of file util.c.
References ARROW_FALSE, and ARROW_TRUE.
Referenced by is_asymmetric(), and is_symmetric().
void arrow_util_restore_stdout (int old_stream)
Restores STDOUT stream that's been redirected.
Parameters:
old_stream [in] existing file handle for STDOUT stream
Definition at line 78 of file util.c.
Referenced by main().
void arrow_util_sbtsp_to_abstp_tour (arrow_problem * problem, int * old_tour, int * new_tour)
Definition at line 246 of file util.c.
References arrow_problem::get_cost, and arrow_problem::size.
Referenced by main().
void arrow_util_write_tour (arrow_problem * problem, char * comment, int * tour, FILE * out)
Definition at line 227 of file util.c.
References arrow_problem::name, and arrow_problem::size.
Referenced by main().
double arrow_util_zeit () [inline]
Used to measure timings.
Returns:
a value representing the CPU time in seconds
Definition at line 63 of file util.c.
Referenced by arrow_2mb_solve(), arrow_bap_solve(), arrow_bbssp_solve(), arrow_bscssp_solve(), arrow_btsp_solve(), arrow_dcbpb_solve(), arrow_tsp_exact_solve(), arrow_tsp_lk_solve(), and main().