Arrow: lib/common/xml.c File Reference
lib/common/xml.c File Reference
Useful functions for writing XML.
#include "common.h"
Functions
void arrow_xml_element_int (char *name, int value, FILE *out)
Writes an XML tag out for an integer value.
void arrow_xml_element_double (char *name, double value, FILE *out)
Writes an XML tag out for a double value.
void arrow_xml_element_string (char *name, char *value, FILE *out)
Writes an XML tag out for a string value.
void arrow_xml_element_bool (char *name, int value, FILE *out)
Writes an XML tag out for a boolean value.
void arrow_xml_attribute_int (char *name, int value, FILE *out)
void arrow_xml_attribute_string (char *name, char *value, FILE *out)
void arrow_xml_element_start (char *name, FILE *out)
void arrow_xml_element_end (FILE *out)
void arrow_xml_element_open (char *name, FILE *out)
void arrow_xml_element_close (char *name, FILE *out)
void arrow_xml_attribute_start (char *name, FILE *out)
void arrow_xml_attribute_end (FILE *out)
Detailed Description
Useful functions for writing XML.
Useful functions for writing xml.
Author:
John LaRusic
Definition in file xml.c.
Function Documentation
void arrow_xml_attribute_end (FILE * out) [inline]
Definition at line 81 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_attribute_int (char * name, int value, FILE * out) [inline]
Definition at line 39 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_attribute_start (char * name, FILE * out) [inline]
Definition at line 75 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_attribute_string (char * name, char * value, FILE * out) [inline]
Definition at line 45 of file xml.c.
void arrow_xml_element_bool (char * name, int value, FILE * out) [inline]
Writes an XML tag out for a boolean value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 33 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_close (char * name, FILE * out) [inline]
Definition at line 69 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_double (char * name, double value, FILE * out) [inline]
Writes an XML tag out for a double value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 21 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_end (FILE * out) [inline]
Definition at line 57 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_int (char * name, int value, FILE * out) [inline]
Writes an XML tag out for an integer value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 15 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_open (char * name, FILE * out) [inline]
Definition at line 63 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_start (char * name, FILE * out) [inline]
Definition at line 51 of file xml.c.
Referenced by arrow_btsp_result_print_xml().
void arrow_xml_element_string (char * name, char * value, FILE * out) [inline]
Writes an XML tag out for a string value.
Parameters:
name [in] the tag name
value [in] the value to write
out [out] the stream to write to
Definition at line 27 of file xml.c.